### ISSUE TITLE
Feature request: ref argument for install_git

### ISSUE THREAD

**Issue by paulobrecht** [r-lib/remotes#105]
The `ref` argument in `install_github()` is very useful for reproducibility. In many cases, though, users of a repo not hosted on GitHub would still find the `ref` argument useful.

**Comment by gaborcsardi** [comment]
Good idea, PR is welcome. :) It is not too hard, just need to add a `git2r` code and an external `git` call, in this file: https://github.com/r-lib/remotes/blob/master/R/install-git.R

**Comment by gaborcsardi** [comment]
The `branch` argument can be a ref, AFAICT.

**Comment by jimhester** [comment]
That is correct!

**Comment by gaborcsardi** [comment]
I am not sure what you mean by "previous commits", but  this seems to work fine:
```r
remotes::install_git(
  "https://github.com/gaborcsardi/pkgconfig.git", 
  branch = "96a1413e2f14c0e218381b6439c564181594e65d")
packageDescription("pkgconfig")$RemoteSha
#> [1] "96a1413e2f14c0e218381b6439c564181594e65d"
```

Isn't this what you want?

**Comment by paulobrecht** [comment]
It does, thanks! I never would have guessed that 'branch' would accept a hash for a non-branch.

**Comment by jimhester** [comment]
We could probably deprecate the branch argument and add `ref` one.

**Comment by gaborcsardi** [comment]
Yeah, that would make sense.
