### ISSUE TITLE
Odd files at the top-level

### ISSUE THREAD

**Issue by jennybc** [r-lib/remotes#111]
Why do these files exist at the top-level of the package?

  * `install-github.R`
  * `install-github.Rin`

**Comment by gaborcsardi** [comment]
That's the file that makes this work: 
```r
source("https://raw.githubusercontent.com/r-lib/remotes/master/install-github.R")$value("r-lib/remotes")
```
And also used for this:
```
source("https://install-github.me/r-lib/remotes")
```

They are not part of the R package, so the top level makes sense.

**Comment by jennybc** [comment]
Aha! So related to self-installation.
