### ISSUE TITLE
Remotes doing something odd to package descriptions?

### ISSUE THREAD

**Issue by richfitz** [r-lib/remotes#117]
I have a package that passes R CMD check fine, installs with `devtools::install_github` and fails with `remotes::install_github`.

```
> remotes::install_github("vimc/vaultr", upgrade = FALSE)
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo vimc/vaultr@master
Installing package into ‘/home/rich/lib/R/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘vaultr’ ...
Error : Invalid DESCRIPTION file

Malformed Depends or Suggests or Imports or Enhances field.
Offending entries:
  Suggests:
processx
Entries must be names of packages optionally followed by '<=' or '>=',
white space, and a valid version number in parentheses.

See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.

ERROR: installing package DESCRIPTION failed for package ‘vaultr’
```

(on windows if I don't use upgrade = FALSE it downloads `jsonlite` every time for reasons that might be related).

This may well be something odd with my DESCRIPTION but I can't see what it is immediately.

This can be replicated with current CRAN remotes and the current github master

**Comment by gaborcsardi** [comment]
The problem is that you have two `Suggests` fields in `DESCRIPTION`. Still, the error message should be better....

**Comment by richfitz** [comment]
Thanks - you're of course right.  Sorry for the noise :)
