### ISSUE TITLE
Error with git remotes

### ISSUE THREAD

**Issue by ankane** [r-lib/remotes#140]
On the latest release and master, git remotes error with `Error: Unknown remote type: git`.

```r
remotes::install_deps(".")
```

`DESCRIPTION` file

```txt
Package: app
Imports: DBI
Remotes:
    git::https://github.com/r-dbi/DBI.git
```

It works with `github::r-dbi/DBI`. From the code, it looks like there are now `git2r` and `gitx` remotes, but those failed as well.

**Comment by gaborcsardi** [comment]
Do you have either git2r or system git installed?

**Comment by ankane** [comment]
Thanks @gaborcsardi, looks like reinstalling `git2r` fixed it. Now getting:

```
Error in is.list(val) : 
  trying to get slot "sha" from an object (class "git_commit") that is not an S4 object 
```

(R 3.5.1, git2r version 0.23.0, Mac High Sierra, remotes 1.1.1 and master). Any ideas?

**Comment by gaborcsardi** [comment]
Maybe a git2r compatibility issue. @jimhester will know.

**Comment by jimhester** [comment]
You will need to use the devel version of remotes with git2r 0.23.0, as that version of git2r broke compatibility with older versions and CRAN remotes has not been updated to support it.

**Comment by ankane** [comment]
Thanks, when I use git2r 0.23.0 and remotes master, I get the original error (`Unknown remote type: git`), but maybe it's an issue with installing remotes from GitHub/locally. I'll just wait until the next release of remotes to see if everything works.

**Comment by jimhester** [comment]
I know what the issue is, I will fix it soon.

**Comment by ankane** [comment]
Thanks @jimhester, it now gives a different error.

```
Error in vapply(remote, remote_sha, character(1), USE.NAMES = FALSE) : 
  values must be length 1,
 but FUN(X[[1]]) result is length 0
```

**Comment by jimhester** [comment]
Thanks, there was a recent regression relating to this, now fixed and tested for.

**Comment by ankane** [comment]
Works great, thanks!
