### ISSUE TITLE
Error:  formal argument "Ncpus" matched by multiple actual arguments

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/remotes#153]
I get this for `r-lib/rcmdcheck`:
```
Error in utils::install.packages(pkgs = pkgs, lib = lib, repos = myrepos,  :
  formal argument "Ncpus" matched by multiple actual arguments
```

Maybe we could just remove the `threads` argument, it seems that  `...` is passed down, anyway?

**Comment by jimhester** [comment]
Yeah that sounds fine to me

**Comment by gaborcsardi** [comment]
This is a breaking change though, so maybe we should fix it without removing the `threads` argument.

**Comment by jimhester** [comment]
I think some breaking changes are ok within reason, I am going to be releasing the remotes integrated devtools as 2.0.0 anyway.
