### ISSUE TITLE
SHA1 check is 100% false negative on `devtools::install`

### ISSUE THREAD

**Issue by vspinu** [r-lib/remotes#163]
No matter which files I change `devtools::install('xyz', quick = TRUE, build = FALSE, upgrade = FALSE, keep_source = TRUE)` shows 

```
Skipping install of 'xyz' from a local remote, the SHA1 (0.1) has not changed since last install.
  Use `force = TRUE` to force installation
Reloading attached mlvocab
```

Hopefully this is not an intended behavior as it's quite inconvenient. I don't see a good alternative except  for   `force=TRUE` which would re-compile the full package, thus not ideal either.

**Comment by jimhester** [comment]
After https://github.com/r-lib/devtools/commit/cc368444a39a784db4f71da9ed2f5f7cc831e1a2 if you run with `build = FALSE` or `quick = TRUE` (which sets `build = FALSE` by default) you will no longer see this behavior.

**Comment by jimhester** [comment]
Also FWIW it is not 100% false negative, the sha of a local package is the version number, if you had changed it it would have installed.

**Comment by vspinu** [comment]
Perfect. Thanks for the instant resolution!
