### ISSUE TITLE
Don't reference to "remotes" namespace, it breaks the install-github.R script

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/remotes#165]
Possible fix: https://github.com/r-lib/remotes/commit/3b70faecf0a97e4b797cc4815ed18e704c4c359e

I think I'll put the script into `inst` and the write some test cases for it, at some point.

**Comment by jimhester** [comment]
We should probably put a comment in the code as well, as it is a pretty odd work around unless you are thinking about the script case

**Comment by gaborcsardi** [comment]
Sure.
