### ISSUE TITLE
Remotes installation too aggressive?

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/remotes#167]
We talked about this before, probably, but maybe we should not install `Remotes` for packages in `Suggests`, if suggested packages are not requested otherwise?

At least it is quite strange that even if I set `dependencies = FALSE`, `install_github("r-lib/remotes")` still installs pkgbuild, because it is in `Remotes`.

One issue here is that we don't necessarily know the name of a remote, but I think we already handle that somewhere by requiring the new remote syntax to specify the package name explicitly, if it differs from the repo (or subdir?) name?

**Comment by jimhester** [comment]
Yeah we could probably do this. I can look into it
