### ISSUE TITLE
Random Travis failures

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/remotes#173]
E.g. 

```
── 2. Error: installing bioc packages (@test-bioc.R#79)  ───────────────────────
no lines available in input
1: withr::with_libpaths(lib, install_git("https://git.bioconductor.org/packages/Biobase", 
       branch = bioc_branch, lib = lib, quiet = TRUE)) at testthat/test-bioc.R:79
2: force(code)
3: install_git("https://git.bioconductor.org/packages/Biobase", branch = bioc_branch, 
       lib = lib, quiet = TRUE)
4: install_remotes(remotes, credentials = credentials, dependencies = dependencies, 
       upgrade = upgrade, force = force, quiet = quiet, build = build, build_opts = build_opts, 
       repos = repos, type = type, ...)
5: vapply(remotes, install_remote, ..., FUN.VALUE = character(1))
6: FUN(X[[i]], ...)
7: remote_sha(remote, local_sha)
8: remote_sha.xgit_remote(remote, local_sha)
9: read.delim(text = refs, stringsAsFactors = FALSE, sep = "\t", header = FALSE)
10: read.table(file = file, header = header, sep = sep, quote = quote, dec = dec, fill = fill, 
       comment.char = comment.char, ...)
11: stop("no lines available in input")
══ testthat results  ═══════════════════════════════════════════════════════════
OK: 463 SKIPPED: 2 FAILED: 2
1. Error: installing bioc packages (@test-bioc.R#79) 
2. Error: installing bioc packages (@test-bioc.R#79) 
```

https://travis-ci.org/r-lib/remotes/jobs/433975963

**Comment by gaborcsardi** [comment]
Yeah, we'll need a GH token just for remotes, I think.

**Comment by gaborcsardi** [comment]
OK, I added a GITHUB_PAT, this should solve it.

**Comment by gaborcsardi** [comment]
install_bioc probably fails because R-devel currently does not have a "matching" bioc version,  e.g. some  branch or tag does not exist in the bioc git repo. Or our R version  -> bioc version mappings are  wrong....

**Comment by gaborcsardi** [comment]
Actually, it is sg else. Not sure if bioc related, because the failure is from  install_git, only on  R devel, seemingly with external  git.  (https://github.com/r-lib/remotes/issues/173#issue-364370732)

**Comment by jimhester** [comment]
I think this is relatively new as well, R-devel was working until recently.

**Comment by jimhester** [comment]
So the change was https://github.com/wch/r-source/commit/f733c5886860c2573933a041471f6c28cc969b07, but there is no RELEASE_3.8 branch  for the Biobase, which is why this is failing.

**Comment by gaborcsardi** [comment]
Shall we check if there is a branch, and if not, then just use the HEAD?

**Comment by gaborcsardi** [comment]
Also, given the yaml file, should we remove the `bioc_install_repos()` logic, and just use the yaml?

**Comment by jimhester** [comment]
> Shall we check if there is a branch, and if not, then just use the HEAD?

Yeah I guess so or maybe just fail with a better error message than we do currently.

**Comment by gaborcsardi** [comment]
OK, the bioc failure is solved by simply removing that test, hopefully: 243165793ef59e5bbb1e6762b6fa6bd5dc0ca8c2 
We didn't need that test case.
