### ISSUE TITLE
install_bitbucket

### ISSUE THREAD

**Issue by overmar** [r-lib/remotes#175]
Currently the CRAN version has an issue with install_bioc not being installed, and the dev version crashes out on authentication as well due to the new API apparently not liking username:password@ at the beginning of the URL. Its an issue of stating --user username:password prior to https://api.bitbucket.org/2.0/ to get it to connect correctly.

**Comment by gaborcsardi** [comment]
That works for me as well, both with and w/o curl: 
```r
❯ Sys.unsetenv("R_REMOTES_STANDALONE")
❯ install_bitbucket("r-lib-testing/pkgconfig")
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  :
  cannot open URL 'https://api.bitbucket.org/2.0/repositories/r-lib-testing/pkgconfig/src/master/DESCRIPTION'
❯ install_bitbucket("r-lib-testing/pkgconfig", auth_user="r-lib-testing", password=<pass>)
Downloading bitbucket repo r-lib-testing/pkgconfig@master
   checking for file ‘/private/var/folders/59/0gkmw1yj2w7bf2dfc3jznv5w0000gn/T/RtmpP3bsF3/remotes5c642✔  checking for file ‘/private/var/folders/59/0gkmw1yj2w7bf2dfc3jznv5w0000gn/T/RtmpP3bsF3/remotes5c6426ed9adb/r-lib-testing-pkgconfig-e9d0190186f2/DESCRIPTION’
─  preparing ‘pkgconfig’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘pkgconfig_2.0.2.tar.gz’

Installing package into ‘/Users/gaborcsardi/r_pkgs’
(as ‘lib’ is unspecified)
* installing *source* package ‘pkgconfig’ ...
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (pkgconfig)

❯ Sys.setenv("R_REMOTES_STANDALONE" = "TRUE")
❯ install_bitbucket("r-lib-testing/pkgconfig", auth_user="r-lib-testing", password=<pass>)
Downloading bitbucket repo r-lib-testing/pkgconfig@master
* checking for file ‘/private/var/folders/59/0gkmw1yj2w7bf2dfc3jznv5w0000gn/T/RtmpP3bsF3/remotes5c64242d74c3/r-lib-testing-pkgconfig-e9d0190186f2/DESCRIPTION’ ... OK
* preparing ‘pkgconfig’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘pkgconfig_2.0.2.tar.gz’
Installing package into ‘/Users/gaborcsardi/r_pkgs’
(as ‘lib’ is unspecified)
* installing *source* package ‘pkgconfig’ ...
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (pkgconfig)
```

**Comment by overmar** [comment]
Ah ha, in the 2.0 version (or somewhere along the way) my user name stopped being my full email address and just the prefix. @gaborcsardi thank you for the example, it helped me figure out what I was doing wrong.

**Comment by gaborcsardi** [comment]
Np. Since this is not currently tested, please let us know if you see problems.
I'll also add a test case, now that I have a private repo on BitBucket. :)

**Comment by overmar** [comment]
Well if I can be of any help let me know. We use these a lot at work, so when it started acting up, I was the one in trouble for updating the package and breaking things. One thing I do notice, is in the past if you wanted another branch you could just specify @ in the repo, but now it looks like they have to be separated. Actually no... apparently all traffic is being routed through /commit/master regardless if you use ref

**Comment by gaborcsardi** [comment]
Oh, that's a bug, can you please open another issue.

**Comment by CharlesCara** [comment]
Sorry to reopen this, but could you explain the fix for this issue again?
On upgrading to devtools 2.0.1 I am having the same problem, despite changing my username from my email address:
`> install_bitbucket(repo = "myteam/myrepo",
+                            auth_user = "charlescara",
+                            password = <PassRedacted>)
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot open URL 'https://charlescara:<PassRedacted>@api.bitbucket.org/2.0/repositories/myteam/myrepo/src/master/DESCRIPTION'`

**Comment by overmar** [comment]
What version of remotes are you using? devtools::install_bitbucket is actually just a pass through to remotes::install_bitbucket

**Comment by CharlesCara** [comment]
I am on remotes version 2.0.2

**Comment by eblondel** [comment]
Hi all, i'm facing the same issue. devtools version 2.0.1. I've tried to access a private bitbucket repo. With either email or username it fails... @mbojan @CharlesCara did you get it work again?

**Comment by mbojan** [comment]
@eblondel no, but haven't tried since

**Comment by CharlesCara** [comment]
No I did not get this version of devtools to work - I had to downgrade to a pre 2.0.x version

**Comment by N1KG** [comment]
Hi, I am currently facing the same issue. install_bitbucket works on public repo but I get the following error when I try on a private repo :

Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot open URL 'https://api.bitbucket.org/2.0/repositories/<user_name>/<repo_name>/src/master/DESCRIPTION'

**Comment by shinobe-atobe** [comment]
Same here, It looks like something to do with the change in API terms on bitbucket since mid October:  https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/

A temporary workaround would be to make the reposity public so you dont need a username and password

```
install_bitbucket("disneystudios/project1", 
                  ref = "master", 
                  subdir = NULL, 
                  quiet = FALSE, 
                  auth_user = rstudioapi::askForPassword("Please enter Bitbucket username"), 
                  password = rstudioapi::askForPassword("Please enter Bitbucket password"))

Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
cannot open URL 'https://<user>:<pass>$$@api.bitbucket.org/2.0/repositories/disneystudios/project1/src/master/DESCRIPTION'
```

**Comment by overmar** [comment]
I have the current version working, but you can't use your email address as your username, ie rather than being overmar@????.com my username is just overmar.

**Comment by CharlesCara** [comment]
I would add that I also have now got installing from a private repository working.  Key is what @overmar said about using your username eg 'charlescara' instead of your email address.

**Comment by mbojan** [comment]
I can confirm it works for me when:

1. Setting Bitbucket username and password in environment variables `BITBUCKET_USER` and `BITBUCKET_PASSWORD` in your `~/.Renviron`. The user is just the username, not email address, like @overmar wrote above.
2. Calling simply  `remotes::install_bitbucket("user/repo")` will fetch and install a package from `user`'s private `repo`.

**Comment by shashj** [comment]
@CharlesCara @overmar It still doesn't work if you have special characters in your password like @

**Comment by overmar** [comment]
reinstall remotes from github, I got it to work with a password of `11Password@`, but this doesn't work in the most recent CRAN version
