### ISSUE TITLE
Make sure windows 10 with system tar works

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/remotes#180]
Because it seems to have problems....

**Comment by jimhester** [comment]
What do you mean by system tar? The one that comes with Rtools or something different? The rtools one seems to work fine (I just tested on Windows 10 with 

```r
Sys.setenv("TAR"="C:\\RBuildTools\\3.5\\bin\\tar.exe")
remotes::install_github("tidyverse/glue")
```

**Comment by gaborcsardi** [comment]
There is one that comes with the system I think

**Comment by jimhester** [comment]
I guess this one https://blogs.technet.microsoft.com/virtualization/2017/12/19/tar-and-curl-come-to-windows/, i'll try and see where it is located.

But if it is based on libarchive I don't think it should have any problems, will try to check.

**Comment by cderv** [comment]
If it can helps, I am on windows 10 and I have a tar binary located in `C:\Windows\System32\tar.exe`.
``` r
cat(processx::run("where", "tar")$stdout)
#> C:\Windows\System32\tar.exe
#> C:\Rtools\bin\tar.exe
```
If I could help with some tests, please tell me.

**Comment by gaborcsardi** [comment]
OK, I don't know what it was, but it seems to work fine now. I tried the current HEAD and also install-github.me (that's slightly older), and both work without Rtools, with the win10 system tar.
