### ISSUE TITLE
install_version should be build = FALSE

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/remotes#181]
Those are proper packages already.

**Comment by jimhester** [comment]
IIRC I believe the pkgbuild path should already detect this and not-rebuild, but maybe the non-pkgbuild path does not. I could also be wrong...

**Comment by gaborcsardi** [comment]
Hmmm, that's a bit strange, I mean that you specify `build = TRUE` but it does not (re)build. Maybe cleaner to have a `build  = "auto"` as well? Not super important....
