### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/remotes#188]
Prepare for release:

* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [x] `revdepcheck::revdep_check(num_workers = 4)`
* [x] [Polish NEWS](http://style.tidyverse.org/news.html#before-release)
* [x] If new failures, update `email.yml` then `revdepcheck::revdep_email_maintainers()`

Perform release:

* [x] Bump version (in DESCRIPTION and NEWS)
* [x] ~~`devtools::check_win_devel()` (again!)~~
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Tag release
* [x] `pkgdown::build_site()`
* [x] Bump dev version
* [x] ~~Write blog post~~
* [x] ~~Tweet~~
* [x] ~~Add link to blog post in pkgdown news menu~~

Template from <https://github.com/r-lib/usethis/issues/338>

**Comment by gaborcsardi** [comment]
@jimhester submitted!

**Comment by gaborcsardi** [comment]
> on its way to CRAN.

**Comment by gaborcsardi** [comment]
We should write a blog post, probably. Should we write it now, or once devtools is updated as well? 

@jimhester @hadley ?

**Comment by jimhester** [comment]
I was planning on a blog post summarizing the whole devtools saga I think. Barring major setbacks I should be able to get devtools out the door early next week.

**Comment by gaborcsardi** [comment]
Sounds good!
