### ISSUE TITLE
install_github without submodules

### ISSUE THREAD

**Issue by jonasfoe** [r-lib/remotes#201]
I used to instruct for a package which has several large submodules that are for dev purposes / keeping track of dependencies to be installed by remotes.
The submodules used to be ignored.

See: https://github.com/jpahle/CoRC
remotes::install_github("jpahle/CoRC")

Now it seems that this way it will try to pull the submodules.
Even if I do remotes::install_url("https://github.com/jpahle/CoRC/archive/master.zip") it does so:
`Downloading package from url: https://github.com/jpahle/CoRC/archive/master.zip
"C:\tools\git\bin\git.exe" clone --depth 1 --no-hardlinks --recurse-submodules https://github.com/copasi/copasi-dependencies.git C:\Users\*\AppData\Local\Temp\Rtmp8IUAJq\remotes49d04595c3c/CoRC-master/development/copasi-source/copasi-dependencies`

I am currently not sure what it does exactly as I can never get it to finish but I would need to have a way to force the zip download instead of the git pull.

**Comment by gaborcsardi** [comment]
Yes, we now automatically include submodules and AFAIR there is no way to avoid this. We'll need to add an argument, option or env var.  The difficulty is that sometimes you only want to ignore submodules of some packages, but I guess as a start we can just ignore all.

For now you can use the old version of remotes like this:
```
source("https://raw.githubusercontent.com/r-lib/remotes/0a5e4fdc51c1cfb69b071d45bdfa15a96098da0c/install-github.R")$value("jpahle/CoRC")
```

**Comment by gaborcsardi** [comment]
@jimhester I think we can have an argument that suppresses all submodules for a start?

**Comment by jonasfoe** [comment]
Thanks for the workaround. It just doesn't look like one that would inspire confidence in a user. But I'll take it for now.

What I mean is that when I run the aforementioned command I would expect for it to download the zip.
I am using install_url instead of install_github.
Instead it seems to trigger a git pull on the jpahle/CoRC repository.
The output as shown earlier:
`Downloading package from url: https://github.com/jpahle/CoRC/archive/master.zip "C:\tools\git\bin\git.exe" clone --depth 1 --no-hardlinks --recurse-submodules https://github.com/copasi/copasi-dependencies.git C:\Users\*\AppData\Local\Temp\Rtmp8IUAJq\remotes49d04595c3c/CoRC-master/development/copasi-source/copasi-dependencies`

**Comment by jonasfoe** [comment]
OK looks like it might download the zip and then try to fill in the submodules. Sorry about that.

**Comment by gaborcsardi** [comment]
> It just doesn't look like one that would inspire confidence in a user. 

Why? `remotes::install_github()` runs code 1) from remotes  and 2) from the package being installed
Sourcing that URL does exactly the same. Sources a file from remotes, and then the install process runs code from the package being installed.

> Instead it seems to trigger a git pull on the jpahle/CoRC repository.

All the install commands do the same thing, once they got the package. If you want to go that way, you can also just do 
```
download.file(...)
R  CMD build ...
remotes::install_deps(...)
R CMD INSTALL ...
```

**Comment by gaborcsardi** [comment]
But of course this is an issue that we'll fix soon.

**Comment by jonasfoe** [comment]
> > It just doesn't look like one that would inspire confidence in a user.
> 
> Why? `remotes::install_github()` runs code 1) from remotes and 2) from the package being installed
> Sourcing that URL does exactly the same. Sources a file from remotes, and then the install process runs code from the package being installed.

It just seems to me like it would appear as an obscure sequence of commands to a user instead of something for which they can try to follow the logic.
Thanks for the help though I'm looking forward to the fix.

**Comment by gaborcsardi** [comment]
@jonasfoe We are planning to fix this by observing `.Rbuildignore`, and not pulling submodules that are ignored by `R CMD build`. Will that fix your use case? AFAICT your submodules are covered by your  `.Rbuildignore`.

**Comment by jonasfoe** [comment]
Yes should be covered and sounds good to me.
