### ISSUE TITLE
Error with install_deps and Packrat

### ISSUE THREAD

**Issue by ankane** [r-lib/remotes#214]
Hey, I'm running into an error with `install_deps` and Packrat. Instructions to repro:

1. Create a new directory
2. Open an R console and run `packrat::init(); install.packages("remotes")`
3. Create a `DESCRIPTION` file with `Imports: DBI` (or any package)
4. Run `remotes::install_deps()`

Error

```
** testing if installed package can be loaded
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'packrat/init.R': No such file or directory
Execution halted
ERROR: loading failed
* removing ‘/some-path/packrat/lib/x86_64-apple-darwin17.6.0/3.5.1/DBI’
Error in i.p(...) : 
  (converted from warning) installation of package ‘DBI’ had non-zero exit status
```

Platform: Mac
Remotes: 2.0.0
Packrat: 0.4.9-14

This could also be a Packrat issue, but the error doesn't occur with devtools, so figured I'd start here.

**Comment by cderv** [comment]
FWIW, I have the same issue, **when in a packrat project** using https://install-github.me service. ie `source("https://install-github.me/r-dbi/DBI")` or even `source("https://install-github.me/r-lib/remotes")`

Regarding the error, it seems to come from `.Rprofile` of the packrat project. When I delete it, no more issue. It is as if the `.Rprofile` of the project is taken into account when *testing if installed package can be loaded*, but run in a working directory where `source("packrat/init.R")` does not work.

Both have a `safe_install_packages` function that calls `with_rprofile_user` that load the current `.Rprofile` (here the one of packrat project) and add some option. This could be the cause of error. 
in `remote` 📦, it can be deactivated by setting env var `R_REMOTES_NO_ERRORS_FROM_WARNINGS` to true. 

If I do that before `Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")` not more error when installing from a source with `remotes` 📦 
```r
# enter packrat project getting the packrat .libPaths
packrat::on()
# By default it is set to false, and we have an error
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
# issue is when installing from source, from inside a packrat project into the packrat lib
remotes::install_github("r-dbi/DBI")
```

Based on this small debugging lookout, I think the issue is related to this
https://github.com/r-lib/remotes/blob/169feb3e9a02db434932092472b60475cf855f07/R/install.R#L62-L70  

This use of the `.Rprofile` seems to lead to error, depending on what it is inside. And for packrat, it is sourcing a script that exist only in the packrat project. 
However, I am not sure where the installation function (`i.p` in remotes - dispatching to install function) is executed. As there is an error, it seems to be outside of the current working dir (the packrat project). You know more than me, and it may be obvious to you.

Hope it helps find how to fix this.

**Comment by jimhester** [comment]
I think this implies we should remove the following lines from `read_rprofile_user()`

https://github.com/r-lib/remotes/blob/15e515b6f1de35cc45a8f27d4830038b417a59cd/R/utils.R#L138-L141

Do you think that seems right @gaborcsardi? That way we would only source .Rprofiles if they are set by the envvar or in the home directory, not project .Rprofiles.

**Comment by gaborcsardi** [comment]
Yes, it seems like that makes sense. I don't have a strong opinion, sometimes the current behavior makes sense as well. But since it does break an existing use case, I agree, we should not read `./.Rprofile`

**Comment by ankane** [comment]
Thanks for getting to the bottom of it @cderv and the quick fix @jimhester

**Comment by ColeWunderlich** [comment]
This issue appears to be back with `remotes 2.1.0` and `packrat 0.5.0`  when attempting to install packages using `install_github()`

Error
```
Downloading GitHub repo bmbolstad/preprocessCore@master
   Error in file(filename, "r", encoding = encoding) : 
     cannot open the connection
   Calls: source -> file
   In addition: Warning message:
   In file(filename, "r", encoding = encoding) :
     cannot open file 'packrat/init.R': No such file or directory
   Execution halted
Error: Failed to install 'preprocessCore' from GitHub:
```

**Comment by gaborcsardi** [comment]
Can you please include a stack trace? The output of `traceback()`, right after the installation?

**Comment by gaborcsardi** [comment]
Also, the best would be to open another issue for this, as this one is already closed, and likely it is indeed a separate issue? Thanks.

**Comment by ColeWunderlich** [comment]
Here is the `traceback()`.  I can open another issue if you want but it seems related given that not being able to find the `packrat` `init.R` called from `.Rprofile` seems to be the root cause of the issue.

I have found that commenting out the (necessary) modifications from `packrat` to my `.Rprofile`bypasses this issue.

Traceback Dump:
```
8: stop(remote_install_error(remotes[[i]], e))
7: value[[3L]](cond)
6: tryCatchOne(expr, names, parentenv, handlers[[1L]])
5: tryCatchList(expr, classes, parentenv, handlers)
4: tryCatch(res[[i]] <- install_remote(remotes[[i]], ...), error = function(e) {
       stop(remote_install_error(remotes[[i]], e))
   })
3: install_remotes(remotes, auth_token = auth_token, host = host, 
       dependencies = dependencies, upgrade = upgrade, force = force, 
       quiet = quiet, build = build, build_opts = build_opts, build_manual = build_manual, 
       build_vignettes = build_vignettes, repos = repos, type = type, 
       ...)
2: pkgbuild::with_build_tools({
       ellipsis::check_dots_used(action = getOption("devtools.ellipsis_action", 
           rlang::warn))
       {
           remotes <- lapply(repo, github_remote, ref = ref, subdir = subdir, 
               auth_token = auth_token, host = host)
           install_remotes(remotes, auth_token = auth_token, host = host, 
               dependencies = dependencies, upgrade = upgrade, force = force, 
               quiet = quiet, build = build, build_opts = build_opts, 
               build_manual = build_manual, build_vignettes = build_vignettes, 
               repos = repos, type = type, ...)
       }
   }, required = FALSE)
1: devtools::install_github("bmbolstad/preprocessCore", force = T)
```

**Comment by boennecd** [comment]
The error happens in `pkgbuild::build` in `remotes::install`. This end up calling `callr::rcmd_safe` with `wd` not being equal to  `"."`. 
`callr::rcmd_safe` then calls `callr:::run_r` which calls `processx::run` [here](https://github.com/r-lib/callr/blob/6557ca4374f90d0a8400717a34071da783fa37e2/R/run.R#L17-L33) inside a `callr::with_envvar` where the first argument has 

```r
options$env["R_PROFILE_USER"]
#R>                           R_PROFILE_USER 
#R> "/tmp/Rtmp24neif/callr-upr-2fac655d42c0"  
readLines(options$env["R_PROFILE_USER"])
#R> [1] "options(\"packrat.dependency.discovery.disabled\"=TRUE)"                                                                                                                                                                                                                                                                                                               
#R> [2] ""                                                                                                                                                                                                                                                                                                                                                                      
#R> [3] "#### -- Packrat Autoloader (version 0.5.0) -- ####"                                                                                                                                                                                                                                                                                                                    
#R> [4] "source(\"packrat/init.R\")"                                                                                                                                                                                                                                                                                                                                            
#R> [5] "#### -- End Packrat Autoloader -- ####"                                                                                                                                                                                                                                                                                                                                
#R> [6] "options(repos=c(CRAN = \"https://cloud.r-project.org\"))"                                                                                                                                                                                                                                                                                                              
#R> [7] ".libPaths(c(\"/tmp/Rtmp24neif/temp_libpath2fac5cb0dc03\", \"/home/boennecd/Dropbox/skole_backup/postdoc/GSMVAPaper/packrat/lib/x86_64-pc-linux-gnu/3.6.1\", \"/home/boennecd/Dropbox/skole_backup/postdoc/GSMVAPaper/packrat/lib-ext/x86_64-pc-linux-gnu/3.6.1\", \"/home/boennecd/Dropbox/skole_backup/postdoc/GSMVAPaper/packrat/lib-R/x86_64-pc-linux-gnu/3.6.1\"))"
```

but the temporary directory is emtpy

```r
list.files(getwd())
#R character(0)
```

A quick solution is to change `.Rprofile` to something like

```r
(function(){
  old_wd <- getwd()
  on.exit(setwd(old_wd))
  setwd("YOUR-PATH-TO-DIR-W-RPROFILE")
  
  #### -- Packrat Autoloader (version 0.5.0) -- ####
  source("packrat/init.R")
  #### -- End Packrat Autoloader -- ####
})()
```

Of course, this is a horrible solution if your repository with other people.
