### ISSUE TITLE
Converting warnings into errors has other bad side-effects

### ISSUE THREAD

**Issue by hadley** [r-lib/remotes#221]
e.g. https://github.com/tidyverse/dplyr/pull/3940

**Comment by hadley** [comment]
How about we don't convert warnings to errors when `_R_CHECK_FORCE_SUGGESTS_=false` ? That will resolve the biggest travis pain point.

**Comment by gaborcsardi** [comment]
That is getting a bit complicated. I think we could just turn warnings off on Travis, no? The Travis job will fail if a required package is missing, and by default it will also fail if a suggested packages is missing.

**Comment by jimhester** [comment]
I wrote a simple implementation of this, I don't think it makes the logic too bad, and solves the common case when you have a Suggested package that is not installed.
