### ISSUE TITLE
Error after "Skipping (package), it is already being installed."

### ISSUE THREAD

**Issue by jsal13** [r-lib/remotes#225]
**Issue:** Installing a package (using a devtools::install_* function) with a dependency that already was installed by another package seems to give an error:

```
Skipping (package_name), it is already being installed
Error in vapply(remotes, install_remote, ..., FUN.VALUE = character(1)) :
  values must be type 'character',
 but FUN(X[[1]]) result is type 'logical'
Execution halted
```

**Setup**: I'm working in a Centos docker image (though the issue still happens on latest MacOS) with the following session info (with a truncated "loaded via a namespace (and not attached)" since this was done with nearly no packages; I included only what seemed important): 

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.5.1
        Package                Version
             BH               1.62.0-1
    R.methodsS3                  1.7.1
           R.oo                 1.22.0
        R.utils                  2.5.0
       devtools                  2.0.0
       pkgbuild                  1.0.2
      pkgconfig                  2.0.2
        pkgload                  1.0.1
      rcmdcheck                  1.3.0
        remotes                  2.0.1
          rlang                  0.3.0
       roxygen2                  6.1.0
```

**Reproduction Steps**:  This happens for a number of packages but I've found the following code in a docker image with the version of R above (3.5.1) will throw the error:

```
devtools::install_version("shiny", version="1.0.0", dependencies = c("Depends", "Imports"))
devtools::install_version("shinyBS", version="0.61", dependencies = c("Depends", "Imports"))
```

You may need to wrap this in `suppressWarnings` so that the warnings are not converted to an error.  The error should appear after the warning that "BH" has already been installed.

**Comment by jimhester** [comment]
this should be fixed by https://github.com/r-lib/remotes/pull/226

**Comment by mrustl** [comment]
@jimhester could you re-open the issue for the above referenced issues e.g. KWB-R/kwb.fakin#11

**Comment by gatsoulis** [comment]
Same issue here when trying to install packages using an Rscript called from a dockerfile. Tried all `devtools::install_` functions and all produce the same error. A bit more detail on when this happened.

Hostmachine running Ubuntu 17.10. Building a child docker from a parent with debian:testing, R 3.5.2 and devtools 2.0.1. It fails when trying to install `magrittr`, `stringr` and `httr` in this order. Just the two of them seem to work for some weird reason. Putting the installation of `httr` first seems to work (but fails when other packages follow, e.g. noticed with `curl`). Example:

```

**Comment by maurolepore** [comment]
I get a similar error when trying to install a package from drat repository on Travis CI  running on mac. I don't get the on Travis  CI running on Linux.

Maybe this issue belongs to <https://github.com/travis-ci/travis-ci/>?

---

https://travis-ci.org/forestgeo/fgeo.tool/builds/489369672

```
Installing package dependencies
1.18s$ Rscript -e 'if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools")'
6.06s$ Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'
fgeo.x (1.1.2 -> NA) [local]
Error in if (!file.info(path)$isdir) { : 
  missing value where TRUE/FALSE needed
Calls: <Anonymous> ... update.package_deps -> install_remotes -> vapply -> FUN -> source_pkg
In addition: Warning message:
In file.copy(x$path, bundle, recursive = TRUE) :
  problem copying /Users/usernlivt8Gy/fgeo.x_1.1.2.tar.gz to /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T//RtmpYOD1vb/file14a5353e97439/fgeo.x_1.1.2.tar.gz: No such file or directory
Execution halted
```

.travis.yml

```
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
  - os: osx
  - r: devel
  - r: release
    after_success: Rscript -e 'covr::coveralls()'
    before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
  - r: oldrel
  - r: 3.3
  - r: 3.2

```

DESCRIPTION

```
# ... more stuff
Additional_repositories: https://forestgeo.github.io/drat/
Suggests: 
    fgeo.x (>= 1.1.2)
# ... more stuff
```

**Comment by dokato** [comment]
It looks like I'm still having this one:
```
Skipping purrr, it is already being installed
Error in vapply(remotes, install_remote, ..., FUN.VALUE = character(1)) : 
  values must be type 'character',
 but FUN(X[[3]]) result is type 'logical'
```

with versions:
```
devtools_2.0.1   
remotes_2.0.2
```
