### ISSUE TITLE
Incompatibility in `install_bitbucket`: `dependencies = TRUE` not working if `upgrade = FALSE`

### ISSUE THREAD

**Issue by r-cheologist** [r-lib/remotes#229]
When running

    remotes::install_bitbucket(
      repo   = "graumannlabtools/ReporteR",
      subdir =  "ReporteR.base/", # '/' currently still necessary in the released version
      dependencies = NA,
      upgrade = FALSE)

the install fails because dependency packages are not being installed. This is fixed by switching to `upgrade = TRUE`, which is clearly counter intuitive - installation of dependencies should still work if one does not want to upgrade installed packages, no?

**Comment by jimhester** [comment]
This is already fixed in the development version of remotes.
