### ISSUE TITLE
install_local() should not clone submodules

### ISSUE THREAD

**Issue by tnagler** [r-lib/remotes#236]
### Issue

My [R package repo](https://github.com/tnagler/wdm-r) contains a git submodule in `/inst`. When running `revdep_check()`, I got an error: `install_local()` tries to clone the submodule from github, but the folder  `/inst` already exitsts. 

### Reprex

``` r
wdm_local_install <- function() {
  ## clone wdm repo from github
  dir <- tempfile()
  src_repo <- "https://github.com/tnagler/wdm-r"
  git_cmd <- paste("clone --recursive --depth=1", shQuote(src_repo), shQuote(dir))
  remotes:::git(git_cmd)
  on.exit(unlink(dir), add = TRUE)
  
  ## try to install from local sources
  lib <- tempfile()
  dir.create(lib)
  on.exit(unlink(lib), add = TRUE)
  install_local(dir, lib = lib)  # errror
}

wdm_local_install()
```

## Error
```
'/usr/bin/git' clone --depth 1 --no-hardlinks --recurse-submodules https://github.com/tnagler/wdm.git /tmp/RtmpuVfHy7/file60be2c766781/file60be2c0e184c/inst
fatal: destination path '/tmp/RtmpuVfHy7/file60be2c766781/file60be2c0e184c/inst' already exists and is not an empty directory.
Error: Command failed (128)
In addition: Warning message:
In system(full, intern = TRUE, ignore.stderr = quiet) :
  Error: Command failed (128) 
```
## Solution
I assume `install_local()` is not supposed to update submodules from non-local remotes. A straightforwad fix is:
``` r
  if (!inherits(remote, "local_remote")) {
    update_submodules(source, quiet)
  }
```

**Comment by tnagler** [comment]
Just realized that there is a unit test that checks whether the function clones submodules. Isn't it rather counterintuitive that `install_local()` connects to an online repository?

If that behavior is intentional, another solution is to update only if the submodule folder does not exist. I.e., adding 
```r
  to_ignore <- to_ignore | dir.exists(file.path(source, info$path))
```
in `update_submodules()`.

Happy to create a new PR when the intended behavior is settled.

**Comment by jimhester** [comment]
If you don't' want a submodule to be used add it to `.Rbuildignore` and it will not be fetched.

**Comment by tnagler** [comment]
The submodule contents are required for building the package. The issue is that the submodule contents are already available locally (which is necessary for development). `install_remotes()` first copies the local contents in `inst` and then tries to clone the submodule into `inst`, which fails because the content is already there.

**Comment by pat-s** [comment]
> If you don't want a submodule to be used add it to .Rbuildignore and it will not be fetched.

Worked for me. However, it is important to add the submodule directory without a `/` at the end, otherwise it won't be ignored.

**Comment by tnagler** [comment]
My workaround: temporarily rename/remove `.gitmodules`, so that `remotes` does not try to clone something that is already present locally. 

I still find it weird that `install_local` fetches a non-local version of submodules that are already available in the local package folder.

**Comment by karimn** [comment]
I'm also seeing this problem with a submodule causing problems installing with `local_install()`. Adding the submodule folder to `.Rbuildignore` didn't help, but temporarily removing the `.gitmodules` worked. I agree with @tnagler that this seems like a weird behavior.

```
> devtools::install_local("../boundr", force = T)
'/usr/bin/git' clone --depth 1 --no-hardlinks --recurse-submodules git@github.com:karimn/multilvlr.git /home/karim/Code/rtemp/Rtmp8P1KW6/file3393449690779/boundr/multilvlr
fatal: destination path '/home/karim/Code/rtemp/Rtmp8P1KW6/file3393449690779/boundr/multilvlr' already exists and is not an empty directory.
Error: Failed to install 'boundr' from local:
  Command failed (128)
In addition: Warning message:
In system(full, intern = TRUE, ignore.stderr = quiet) :
  running command ''/usr/bin/git' clone --depth 1 --no-hardlinks --recurse-submodules git@github.com:karimn/multilvlr.git /home/karim/Code/rtemp/Rtmp8P1KW6/file3393449690779/boundr/multilvlr' had status 128
```
