### ISSUE TITLE
update_packages(): Option to exclude specific packages

### ISSUE THREAD

**Issue by pat-s** [r-lib/remotes#241]
Would you accept a PR that enables the option of passing a vector of pkgs that should not be updated when calling `update_packages()`?

I would like to use it primarily on Travis. There I call `remotes::update_packages(T)` which updates all the base packages as well (Matrix, survival, mgcv, lattice). 
These base packages never get cached (for some reason) and get updated in every build currently.

**Comment by jimhester** [comment]
Why are you calling `remotes::update_packages(T)` on travis, the install functions already automatically update any package dependencies.

If you really want to do this you can use something like

```r
installed_packages <- installed.packages()[, "Package"]
remotes::update_packages(setdiff(installed_packages, c("Matrix", "survival", "mgcv", "lattice")))
```

**Comment by pat-s** [comment]
> Why are you calling remotes::update_packages(T) on travis, the install functions already automatically update any package dependencies.

Do the install functions also update the deps of the deps? I think that's why we did it back then. We once had troubles with a not updated dep that causes some issues and decided afterwards to explicitly call `update_packages(T)` in every build so that we are "safe". 

I also had the `setdiff()` idea in mind but did not apply it - sometimes it' easier than one thinks ;)

I'll check if we can maybe get rid of the `update_packages(T)` call in our setup and if that is actually done automatically. I'll keep you updated. Thanks for the quick help!

**Comment by jimhester** [comment]
Yes the update is done automatically for all recursive dependencies.
