### ISSUE TITLE
Update package description...

### ISSUE THREAD

**Issue by jeroen** [r-lib/remotes#242]
> Description: Download and install R packages stored in 'GitHub',
    'BitBucket', or plain 'subversion' or 'git' repositories. This package
    is a lightweight replacement of the 'install_*' functions in 'devtools'.
    Indeed most of the code was copied over from 'devtools'.

I think this is no longer accurate, and it should say that `remotes` provides the 'install_*' implementations in 'devtools'?

**Comment by JamesCuster** [comment]
I will do this
