### ISSUE TITLE
Ability to prevent a remote from being used

### ISSUE THREAD

**Issue by Paxanator** [r-lib/remotes#244]
_Originally posted by @gaborcsardi in https://github.com/r-lib/remotes/issues/210#issuecomment-437126612_

When installing R packages there are many transient dependencies that are required to install. Prior to remotes the way these dependencies were installed was via CRAN. 

With remotes we can now install from many different locations which is great! However, for rate limited remotes, such as Github, it's possible for a process to be blocked from using its service. It also creates a dependency on an api that may have issues. Both of these issues can result in CI/CD build failures.

Would it be possible to create or set some variable that could prevent some types of remotes being used, and skip over the packages that require them, or try them from a different remote?

I am happy to contribute it if so

Thanks!

**Comment by gaborcsardi** [comment]
remotes installs everything from the users' default repos, meaning usually CRAN. It only installs from other sources if a package _explicitly needs_  a different version.

**Comment by Paxanator** [comment]
Thanks for the reply @gaborcsardi ,

Say i have the following packages:
Package A 
Package B whose current version is 2.1

So you're saying if Package A relies on Package B < version 2 then it will use github to install Package A? What about >= version 2?

Essentially I'm driving at I would like to prevent remotes from relying on github in some cases. If it's the case that that's the only way to install exact or relative versions for some packages, then I suppose we can close this issue.

**Comment by gaborcsardi** [comment]
> Essentially I'm driving at I would like to prevent remotes from relying on github in some cases.

Remotes never installs from GitHub, unless a package explicitly requests a GitHub version. 

E.g. pkgman requests the GitHub version of pkgdepends here: https://github.com/r-lib/pkgman/blob/208eef2b379b789da2f9db7f5b12ff521ea853d2/DESCRIPTION#L32
(`r-lib/pkgdepends` is short for `github::r-lib/pkgdepends`)

Except for the four packages under `Remotes` there, which are explicitly requested from GitHub, the rest will be installed from CRAN.

remotes could not even install then from GitHub, even if it wanted to. If `DESCRIPTION` has something like `Imports: filelock`, remotes has no idea where that package is on GitHub. In general there is no way to determine the GitHub repository from just a package name. Many CRAN packages  do not even have repositories on GitHub.

I am not sure what you mean by the version requirements, but again, no version requirement will make remotes install packages from GitHub. Only `Remotes` fields do.
