### ISSUE TITLE
install_github() calls utils::select.list() which gives a misleading prompt

### ISSUE THREAD

**Issue by nzxwang** [r-lib/remotes#245]
install_github() gives the option to update dependencies but gives a very misleading prompt "enter an empty line to cancel". Maybe utils::select.list correctly asks the user to cancel the **upgrade**, but this is rather misleading when it is called from within install_github() as the user is lead to believe the the installation will be cancelled
```
> remotes::install_github("cfhammill/lenses", force=T)
Downloading GitHub repo cfhammill/lenses@master
These packages have more recent versions available.
Which would you like to update?

1:   Rcpp (0.12.19 -> 1.0.0) [CRAN]

Enter one or more numbers separated by spaces, or an empty line to cancel
1: 
```

https://github.com/r-lib/remotes/blob/master/R/deps.R#L577

**Comment by rachwhatsit** [comment]
I'm getting this error when I install a local package I'm developing...

**Comment by jimhester** [comment]
This is a duplicate to #207
