### ISSUE TITLE
install_github - "Error: 'setInternet2' is Defunct"

### ISSUE THREAD

**Issue by jesse-smith** [r-lib/remotes#250]
When attempting to install packages using 'remotes::install_github', this error appears:
```
> remotes::install_github("r-lib/devtools")
Error: 'setInternet2' is defunct.
See help("Defunct")
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.1 tools_3.5.1    yaml_2.2.0    
[4] remotes_2.0.2 
> 
```
The error is reproducible when attempting to install several different packages. Not sure if this helps, but as of r version 3.3.0, only `use = NA` is accepted as input to setInternet2 (see [here](https://www.rdocumentation.org/packages/utils/versions/3.3.2/topics/setInternet2)).

**Comment by jesse-smith** [comment]
Update: the error occurs when using 'install_local' as well.

**Comment by kendonB** [comment]
I am seeing this error also.

**Comment by cderv** [comment]
`setInternet2` should definitely be removed from internal method `download_method_secure`. There are suprisingly 2 functions in `install_github.R` and `download.R`. 
This test with `setInternet2` is not needed anymore as `internal` default to `wininet` method on windows and support https.

Also, Is this with the dev version of `remotes` ? Or CRAN 3.5.1 ? 
I don't if it is related but there where changes recently and, as a workaround, you may need to set `options(download.file.method = "wininet")` as `remotes` now defaults to `libcurl` in some case.
