### ISSUE TITLE
Misleading message when installing, not updating, a GitHub dependency

### ISSUE THREAD

**Issue by maelle** [r-lib/remotes#254]
I used `remotes::install_github("r-lib/credentials")` and got this message

```r
These packages have more recent versions available.
Which would you like to update?

1:   openssl (1.0.2 -> 1.1         ) [CRAN]
2:   sys     (1.5   -> 2.1         ) [CRAN]
3:   askpass (NA    -> 1f8db575d...) [GitHub]
4:   CRAN packages only
5:   All
6:   None
```

I'm not sure how this could be improved but choosing 4 or 6 means not installing `askpass` which leads to an installation error.

**Comment by jimhester** [comment]
I think this has been fixed already, we now always install uninstalled packages without prompting.
