### ISSUE TITLE
Unable to `install_gitlab` repos within subgroups 

### ISSUE THREAD

**Issue by timtrice** [r-lib/remotes#259]
If we want to use `install_gitlab` we supply a `repo` parameter which is in <code>username/repo[/subdir][@ref]</code> format.  This string is split by [parse_repo_spec](https://github.com/r-lib/remotes/blob/fb6682b6091412e75e313345ab54e96e82ed58b7/R/parse-git.R#L40) so we have a `username` variable (e.g., "r-lib") and `repo` variable (e.g., "remotes"). 

If my repo is within a  GitLab group, then I can simply replace the `username` portion of the `repo` parameter with the name of the group.

However, if I have a subgroup holding the repo, I'm stuck. There is no `params` variable for subgroups.

```r
#' Works
devtools::install_gitlab("timtrice/falsy")
```

```r
#' Works
devtools::install_gitlab("timtrice_tests/falsy")
```

```r
#' Fails
devtools::install_gitlab("timtrice_tests/tests/falsy")
```

```
 Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot open URL 'https://gitlab.com/timtrice_tests/tests/raw/master/falsy/DESCRIPTION?private_token=ABCDEFGHIJKLMNOP' 
```

There is no way to get the subgroup past the `parse_repo_spec` function. So, further functions that stick the URL back together do it incorrectly. The URL in the error above should be, 

<code>https://gitlab.com/timtrice_tests/tests/raw/master/falsy/DESCRIPTION?private_token=ABCDEFGHIJKLMNOP</code>

For example, in `remote_package_name`, the src is built (using `build_url`) as that in the error message. But, if I change src to the last example above, while debugging, it is successful. 

Another option is, instead of using the group/subgroup/repo combination, perhaps we can pass the Project ID? This doesn't seem to work in `remote_pacage_name` but it does in `gitlab_commit`.

**Comment by jimhester** [comment]
I was not aware of this subgroup concept, looking at this example I am not really sure how it could be supported while also retaining support for subdirectories

**Comment by rozwad** [comment]
Please see #308 – quick and dirty workaround.

**Comment by ldecicco-USGS** [comment]
Any chance we can re-start the conversation on installing from sub groups? We're considering moving our github/USGS-R packages to a sub group. Here's an example:

The subgroup:
https://code.usgs.gov/water/stats

The repo:
https://code.usgs.gov/water/stats/MGBT

For the record, this works:
```r
 remotes::install_git("https://code.usgs.gov/water/stats/MGBT.git")
 remotes::install_url("https://code.usgs.gov/water/stats/MGBT/-/archive/master/MGBT.zip")
```
So...maybe we just need to get people to use that...
