### ISSUE TITLE
install_github continuation line error on DESCRIPTION file

### ISSUE THREAD

**Issue by jeffreyevans** [r-lib/remotes#269]
I am having an issue with install_github in remotes 2.0.2.9000 where I receive a continuation line error, originating from the DESCRIPTION file. I just sourced the GitHub version of remotes to make sure that I am running the most current version. The package that I am trying to install has passed CRAN checks and is currently being pushed to the repositories so, no issues with the package.    

Oddly enough, if the package, that is being installed from GitHub, is already installed locally this does not occur but if I remove the package from my library and then run install_github this error pops up:

Error in read.dcf(path) :
Found continuation line starting ' role = ...' at begin of record.

Based on this line in my DESCRIPTION file:

Authors@R: c(person(family="Evans", given="Jeffrey S.", email = "jeffrey_evans@tnc.org",
role = c("aut", "cre")), person(family="Ram", given="Karthik", role = "ctb") )

My Description and Imports sections also have line continuations that cause this error (note; there is no white space and the end of the lines). The package that I am trying this on is spatialEco (https://github.com/jeffreyevans/spatialEco). But the same error occurs on two other packages.

Here is my sessionInfo

R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] stats graphics grDevices utils datasets methods base

loaded via a namespace (and not attached):
[1] Rcpp_1.0.0 magrittr_1.5 rappdirs_0.3.1 bit_1.1-14
[5] debugme_1.1.0 R6_2.3.0 blob_1.1.1 tools_3.5.1
[9] pkgbuild_1.0.2 parsedate_1.1.3 cli_1.0.1 DBI_1.0.0
[13] withr_2.1.2 remotes_2.0.2.9000 bit64_0.9-7 assertthat_0.2.0
[17] rprojroot_1.3-2 digest_0.6.18 crancache_0.0.0.9000 crayon_1.3.4
[21] processx_3.2.1 callr_3.1.0 ps_1.2.1 curl_3.2
[25] memoise_1.1.0 RSQLite_2.1.1 cranlike_1.0.2 compiler_3.5.1
[29] desc_1.2.0 backports_1.1.3 prettyunits_1.0.2

**Comment by gaborcsardi** [comment]
Can't reproduce:
```r
❯ remove.packages("spatialEco")
Removing package from ‘/Users/gaborcsardi/R’
(as ‘lib’ is unspecified)

❯ remotes::install_github("jeffreyevans/spatialEco")
Downloading GitHub repo jeffreyevans/spatialEco@master
✔  checking for file ‘/private/var/folders/59/0gkmw1yj2w7bf2dfc3jznv5w0000gn/T/RtmpKMXjOa/remotesb33c8a5358f/jeffreyevans-spatialEco-1416965/DESCRIPTION’ ...
─  preparing ‘spatialEco’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘spatialEco_1.1-1.tar.gz’

Installing package into ‘/Users/gaborcsardi/R’
(as ‘lib’ is unspecified)
* installing *source* package ‘spatialEco’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (spatialEco)

```
