### ISSUE TITLE
Improve error messages when repository not found

### ISSUE THREAD

**Issue by jimhester** [r-lib/remotes#271]
Currently it looks like this

``` r
remotes::install_github("r-lib/arst")
#> Error: HTTP error 404.
#>   Not Found
#> 
#>   Rate limit remaining: 4990/5000
#>   Rate limit reset at: 2019-01-04 13:57:37 UTC
#> 
#> 
```

<sup>Created on 2019-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Some ideas for improvement

- Only show the rate limit message for 403 errors or when the rate limit is 0 (which should be a 403 error)
- Add a hint when it is a 404 error that it is likely due to a misspelled repo

The relevant code is https://github.com/r-lib/remotes/blob/a0d6cd5d52062fcaedac7dd19b03f9211f578791/R/github.R#L144-L188

**Comment by jennybc** [comment]
More about the hint for a 404:

  * Could be either misspelled owner (good vocab that works for user or organization) or repo name.
  * Could be you don't have permission to read the repo. Which, in turn, could mean you aren't sending the credentials you intend to.

 Our style guide for error messages: <https://style.tidyverse.org/error-messages.html>

**Comment by tylermorganwall** [comment]
I will tackle this.
