### ISSUE TITLE
install_github fails when non-empty 'configure.win' is present [Windows 10, R 3.5.2]

### ISSUE THREAD

**Issue by sjmgarnier** [r-lib/remotes#272]
Since upgrading from R 3.5.1 to 3.5.2, installation of ROpenCVLite from its GitHub repository fails on Windows with the following message (see https://github.com/swarm-lab/ROpenCVLite/issues/14): 

```
Error: (converted from warning) this package has a non-empty 'configure.win' file,
so building only the main architecture
```

I believe this might be related to https://github.com/r-lib/remotes/issues/221, but I'm not certain how to proceed in order to let users install the package on R 3.5.2. Thanks for your help.

**Comment by gaborcsardi** [comment]
You avoid the warning -> error conversion by setting `R_REMOTES_NO_ERRORS_FROM_WARNINGS=true`, see the README.

If the package can be built for both i386 and x64, then it could add this in the `DESCRIPTION` file, like this: https://github.com/cran/ps/blob/57f749fbd74e9912e4667e439bab0114fd2c3d8b/DESCRIPTION#L21

**Comment by sjmgarnier** [comment]
Perfect, thanks!
