### ISSUE TITLE
install_github does not pass argument onto install.packages

### ISSUE THREAD

**Issue by Shians** [r-lib/remotes#286]
Documentation of `install_github()` says it should pass arguments not install.packages. This gave me hope to resolve #130 by setting `method = "libcurl"` on Windows. However as far as I can tell `install_github()` has nothing to do with `install.packages()`. Instead it takes its download option from `remotes:::download_method()`.

``` r
debugonce(install.packages)
remotes::install_github("r-lib/remotes", method = "libcurl")
```

**Comment by cderv** [comment]
Not sure it is correctly documented in the help file but in last dev version, `remotes` uses the global option set for R if any is set. 

So you need to set 
```r
options(download.file.method = "libcurl")
```
and it will be picked by `remotes`. 

This option is base R and is documented in `?download.file`

This new behaviour is documented in the NEWS file for dev version. See https://github.com/r-lib/remotes/blob/master/NEWS.md#remotes-dev 

The code is here: 
https://github.com/r-lib/remotes/blob/9f1ae8dc6c6b55bfa5707e1ff0c44ac884757b81/R/download.R#L77

**Comment by Shians** [comment]
Thanks, working fine after installing dev version and set the option as described. In v2.0.2 the option was not used in `download_file()` and in the dev version the documentation is still misleading as far as I can tell, unless there's some configuration that does route through `install.packages()`.
