### ISSUE TITLE
install_deps() fails on travis on mac: 'missing value where TRUE/FALSE needed'

### ISSUE THREAD

**Issue by maurolepore** [r-lib/remotes#289]
Thanks a LOT for remotes and support for R on Travis  CI

On Travis CI with R 3.5.2 and macOS High Sierra I get this error ([job](https://travis-ci.org/forestgeo/fgeo.tool/jobs/489863653)):

```
> devtools::install_deps(dep = T, dependencies = TRUE, repos = c("https://cloud.r-project.org", "http://forestgeo.github.io/drat"))
fgeo.x (1.1.2 -> NA) [local]
Error in if (!file.info(path)$isdir) { : 
  missing value where TRUE/FALSE needed
Calls: <Anonymous> ... update.package_deps -> install_remotes -> vapply -> FUN -> source_pkg
In addition: Warning message:
In file.copy(x$path, bundle, recursive = TRUE) :
  problem copying /Users/usernlivt8Gy/fgeo.x_1.1.2.tar.gz to /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T//RtmpzwHcLq/file14a516eb0ad54/fgeo.x_1.1.2.tar.gz: No such file or directory
```

The package passes `rhub::check_on_macos()` cleanly, and passes on Ubuntu on Travis, win-builder. 

Locally, the isolated function call does what I expect:

![image](https://user-images.githubusercontent.com/5856545/52388729-c233a380-2a5d-11e9-8626-2c863a2b72f0.png)

**Comment by jimhester** [comment]
I think at least part of this is addressed by e473d9
