### ISSUE TITLE
install_url() doesn't respect download options

### ISSUE THREAD

**Issue by kenahoo** [r-lib/remotes#290]
I have a local CRAN-alike that requires a username & password for access.  Using `install_packages`, and its friends like `download.file`, I can set the following options to let `curl` handle the authentication:

    options(download.file.method = 'curl', download.file.extra = '--netrc')

The benefit of doing things this way is that the username & password stay out of the text of the URL, so they don't appear in log files, etc.

With `remotes::install_url`, the standard `download.file` mechanism isn't used, and there's no other way to pass credentials for download.

Our current workaround is to use `download.file` and then install from the tarball directly.  Could support for these options be added, either by leveraging `download.file` (preferred) or aping its behavior?

**Comment by cderv** [comment]
Did you try with last dev version of `remotes` ? 

The option `download.file.method` is now respected. (see [NEWS](https://github.com/r-lib/remotes/blob/master/NEWS.md#remotes-dev))
> install_* functions now respect the download.file.method option, if download_file() is used for HTTP.

Also, for `install_url`, `utils::download.file` is used so `download.file.extra = '--netrc'` should be respected, and will apply to `curl` method.

If you have not yet, can you try with last dev version ? thanks !

**Comment by kenahoo** [comment]
Excellent - no, I hadn't tried yet with the dev version, I can try that again when I'm back in the office Monday.  Thanks.

**Comment by kenahoo** [comment]
Forgot to update the thread - the new release works great, thanks for the change.
