### ISSUE TITLE
install_github fails without git lfs installed

### ISSUE THREAD

**Issue by bomeara** [r-lib/remotes#292]
We use git lfs for storing some files in our package (even though in our case it's overkill: biggest is 3.5 MB). If we use install_github on a system without git lfs installed, we get errors:

```
remotes::install_github("phylotastic/datelife", ref = "ad8eae1933b648309cabba4d0cc2a17fd2e4eaec")
```

returns

```
Downloading GitHub repo phylotastic/datelife@ad8eae1933b648309cabba4d0cc2a17fd2e4eaec
✔  checking for file ‘/tmp/RtmpHzKtix/remotes6cb34b34af4d/phylotastic-datelife-ad8eae1/DESCRIPTION’ ...
─  preparing ‘datelife’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘datelife_0.2.16.tar.gz’

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘datelife’ ...
** R
** data
*** moving datasets to lazyload DB
Warning: file ‘birds_and_cats.rda’ has magic number 'versi'
  Use of save versions prior to 2 is deprecated
Error in load(zfile, envir = envir) :
  bad restore file magic number (file may be corrupted) -- no data loaded
ERROR: lazydata failed for package ‘datelife’
* removing ‘/usr/local/lib/R/site-library/datelife’
Error in i.p(...) :
  (converted from warning) installation of package ‘/tmp/RtmpHzKtix/file6cb3360e4394/datelife_0.2.16.tar.gz’ had non-zero exit status
```

Within our research group, we can just make sure to tell people to install git lfs before using install_github, but others may also be hit by this. I don't know the best solution -- ideal would be for this to just work with lfs files; if not that, then an informative error message pointing to the need to install git lfs could help (it would have saved us a couple of days of debugging).

**Comment by gaborcsardi** [comment]
You can add a `configure` file to the repo, that checks for LFS and exits with a meaningful error if it is not available.

**Comment by bomeara** [comment]
Ah, good idea. We'll do this in our packages. I still wonder if it's an issue it'd be good for `install_github` itself to catch, too -- a change here could address it for anyone's packages that use lfs, rather than have them each independently add `configure`, probably after googling and finding this thread. [but feel free to close if it's a won't fix, of course]

**Comment by gaborcsardi** [comment]
How could one detect that your package needs git lfs?

**Comment by bomeara** [comment]
It would require git, but 

```
git check-attr --all -- * | grep "filter: lfs"
```

would check all files (or replace * with *rda, etc.). [from [this](https://github.com/git-lfs/git-lfs/issues/2748) thread].

Perhaps easier is just looking in the `.gitattributes`  file, which can have entries like

```
*.doc filter=lfs diff=lfs merge=lfs -text
*.rda filter=lfs diff=lfs merge=lfs -text
*.docx filter=lfs diff=lfs merge=lfs -text
*.xls filter=lfs diff=lfs merge=lfs -text
*.gz filter=lfs diff=lfs merge=lfs -text
*.pptx filter=lfs diff=lfs merge=lfs -text
```
matching `=lfs` for a string anywhere could work.

**Comment by lwaldron** [comment]
This took me a while to figure out, which I finally did before looking in the issues and finding it already reported! Agreed, a more meaningful error would have been very helpful.

**Comment by jimhester** [comment]
I sympathise with the issue, but we can't really detect git lfs reliably without having git installed (which we do not assume), so I think we are just going to have to leave this as-is.

**Comment by CGMossa** [comment]
I am having exactly this same issue. But I have LFS installed on my machine. How can I check if {devtools} is using my local git client or maybe there is something else going on?
