### ISSUE TITLE
bitbucket remote

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [r-lib/remotes#293]
Getting an error in
```
install_github("nwfsc-assess/VASTWestCoast")
```
because I have a bitbucket remote as well as github remotes. It is trying to find the bitbucket repository using the following URL which is listed in the error I received from R version 3.5.2 on a Windows machine
```
Downloading GitHub repo nwfsc-assess/VASTWestCoast@master
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repositories/hrue/r-inla/src/default/rinla/DESCRIPTION'
```
my remote section of my DESCRIPTION file looks like
```
Remotes: 
    github::James-Thorson/FishData, 
    bitbucket::hrue/r-inla/rinla@default,
    github::James-Thorson/FishStatsUtils, 
    github::James-Thorson/ThorsonUtilities, 
    github::James-Thorson/VAST, 
    github::nwfsc-assess/nwfscSurvey
```

**Comment by antoine-sachet** [comment]
Symptom for #337 and #342

Currently the host of the package is passed to the dependency (#337) hence what you are observing. If you change the code to avoid passing the host to the dependencies, it still won't work because the default bitbucket host in `bitbucket_remote` is `NULL` (#342), so you'll get this error:

```
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot open URL 'https://repositories/hrue/r-inla/src/default/rinla/DESCRIPTION'
```

**Comment by jimhester** [comment]
This is now installs without an error in the current devel version.
