### ISSUE TITLE
Reducing the number of options when two options are equivalent

### ISSUE THREAD

**Issue by llrs** [r-lib/remotes#297]
Today when installing a package via `devtools::install` I got prompted with this menu:

```
> install()
These packages have more recent versions available.
Which would you like to update?

1:   dplyr (0.7.8 -> 0.8.0) [CRAN]
2:   R6    (2.3.0 -> 2.4.0) [CRAN]
3:   CRAN packages only
4:   All
5:   None

Enter one or more numbers separated by spaces, or an empty line to cancel
1:
```

I thought that the third option could be removed as there are only CRAN packages to be updated. When I read the third option I thought there was some other package hidden that needed to be updated or that couldn't update. I propose that if updating "All" packages and "CRAN packages only" is the same to remove the option of "CRAN packages only"

This seems to come from remotes (hence I open the issue here), but I couldn't trace it back (I think that it is `devtools::install`->`install_deps`->`update` or `dev_package_deps`)

**Comment by jimhester** [comment]
Sure I agree it is not perfect, but I think the benefits of argument consistency outweighs the redundancy.
