### ISSUE TITLE
upgrade argument has no effect for install_cran

### ISSUE THREAD

**Issue by cderv** [r-lib/remotes#302]
I found this with new dplyr version while managing a central server: 

* I have dplyr 0.7.8 on the system
* There is now a new version
* I would expect `remotes::install_cran("dplyr", upgrade = FALSE, force = FALSE)` to install nothing. 

However, for cran remote, `upgrade` is not used
https://github.com/r-lib/remotes/blob/62123450b3b6c1c7c485e88a3b204dbc21166100/R/install-remote.R#L11-L47

You can reproduce with any 📦 

``` r
withr::with_temp_libpaths({
  remotes::install_version("glue", "1.2.0", quiet = TRUE)
  message(sprintf("Installed glue: %s", packageVersion("glue")))
  remotes::install_cran("glue", upgrade = FALSE, quiet = TRUE)
  message(sprintf("Installed glue: %s", packageVersion("glue")))
}
)
#> Installed glue: 1.2.0
#> Installing 1 packages: glue
#> package 'glue' successfully unpacked and MD5 sums checked
#> Installed glue: 1.3.0
```

<sup>Created on 2019-02-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Should we to nothing if 📦 is already installed, there is a new version, but `upgrade` is ask or  never ?

**Comment by jimhester** [comment]
`upgrade` only effects dependencies, `install_cran()` unconditionally installs the latest version from CRAN.

**Comment by cderv** [comment]
I understand this choice now.

Shouldn't the [documentation ](https://remotes.r-lib.org/reference/install_cran.html) reflect this ? 
It was misleading as `upgrade` is one of the argument as all other `install_*` functions., but it is not used at all with `install_cran()`
