### ISSUE TITLE
Should github_pat() be exported?

### ISSUE THREAD

**Issue by MarkEdmondson1234** [r-lib/remotes#306]
When trying to depend on `remotes::install_github()` I also include `remotes::github_pat()` but this is not exported in the latest version, I can only access via `:::`

```r
remotes::github_pat()
Error: 'github_pat' is not an exported object from 'namespace:remotes'
remotes:::github_pat()
NULL
```

But it is listed in the function arguments:

```
install_github(repo, ref = "master", subdir = NULL,
  auth_token = github_pat(), ... etc
```

Is this an oversight, or what do I need to do to import this into a package?  

The function I'm trying to import into installs libraries on a VM:

```r

..snip...
#' @import future
#' @importFrom utils install.packages
#' @importFrom remotes install_github github_pat
#' @export
gce_future_install_packages <- function(instance,
                                        docker_image,
                                        cran_packages = NULL,
                                        github_packages = NULL){
  
  ## set up future cluster
  temp_name <- paste0("gceR-install-",idempotency())
  clus <- as.cluster(instance, 
                             docker_image = docker_image,
                             rscript = c("docker", "run",paste0("--name=",temp_name),"--net=host", docker_image, "Rscript"))
  
  plan(cluster, workers = clus)
  
  if(!is.null(cran_packages)){
    cran <- NULL
    cran %<-% install.packages(cran_packages)
    cran
  }
  
  if(!is.null(github_packages)){
    devt <- NULL
    devt %<-% install_github(github_packages, auth_token = github_pat())
    devt
  }
  
... etc ...
```

Using `remotes_2.0.2`

**Comment by jennybc** [comment]
One possible position is that gh should export this. Indeed it does in the dev version, because I raised a similar issue there (https://github.com/r-lib/gh/issues/74).

I think you should inline some version of this function in your package, maybe with a comment to grab it from one of your Imports when/if possible. That's the current approach in usethis:

https://github.com/r-lib/usethis/blob/37a774ea989714619f5c6dcfaff0ece248027b56/R/github.R#L290-L295

**Comment by MarkEdmondson1234** [comment]
Ok, I'll copy it over for now, and keep an eye on the other thread. Thanks!
