### ISSUE TITLE
"Cannot open URL": remotes::install_version for type='binary' (MacOS)

### ISSUE THREAD

**Issue by asodja** [r-lib/remotes#307]
It seems like 'remotes::install_version' does not work for binary type. Example call:
> remotes::install_version('data.table', version='1.12.0', type='binary')
Downloading package from url: https://cloud.r-project.org/bin/macosx/el-capitan/contrib/3.5/data.table_1.12.0.tar.gz
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot open URL 'https://cloud.r-project.org/bin/macosx/el-capitan/contrib/3.5/data.table_1.12.0.tar.gz'

It seems that problems is file extension '.tar.gz', it should be '.tgz'. So url should be:
https://cloud.r-project.org/bin/macosx/el-capitan/contrib/3.5/data.table_1.12.0.tgz.

I tested just on MacOS so I am not sure if it works on other platforms.

**Comment by jimhester** [comment]
This is expected, `install_version()` is for installing older versions of packages, CRAN only keeps binaries for the latest version.

 If you want to install the current version just use `remotes::install_cran()` or `install.packages("cran")`.

**Comment by asodja** [comment]
Ok, I see. Although I do not agree that this is expected, since it is possible to set a type to binary. Install_version function should not allow to set a type or it should handle such cases for newest versions.  

To better understand my use case, I want to install packages for certain version from a file, similar to requirements.txt in python (I am familiar with Packrat, but it is just too buggy and you have to hack around it all the time). Unfortunately it seems that I will have to handle such cases by myself.

**Comment by jimhester** [comment]
Calling `install_version()` with a type of anything but source is now an error https://github.com/r-lib/remotes/commit/2330f37737425c5dc1ea8a1f9489d8717d35bbbb
