### ISSUE TITLE
The install_github function breaks with faulty "repos" string.

### ISSUE THREAD

**Issue by grabear** [r-lib/remotes#316]
# Problem
![image](https://user-images.githubusercontent.com/20953530/54390123-b85e1b00-466f-11e9-978b-cbbdc7e63a32.png)

I've had this issue before and I don't know how I fixed it.  This has occurred at work on my machine, my coworker's machine (@sdhutchins), and another developer's machines (@CosteaPaul; Windows/Linux; https://github.com/openjournals/joss-reviews/issues/1299).

# Debugging
In order to rule out networking issues I have tried it on my personal laptop using a different network connection.  I've also created a new library path in order to install everything fresh.  

Here is what my debugging console looks like:

![image](https://user-images.githubusercontent.com/20953530/54390425-741f4a80-4670-11e9-94fe-5b21d65e8b11.png)

It looks like the problem is occuring in the `remotes::available_packages` or `utils::available_packages` function.  For some reason the `contriburl` list has "src/contrib" tacked on to the end, which implies there is a blank string somewhere in the repos argument.  This can be replicated with the following code:

```r
> utils::contrib.url(c("", unlist(options("repos"))), "source")
[1] "/src/contrib"                                  
[2] "https://cran.rstudio.com/src/contrib"          
[3] "http://www.stats.ox.ac.uk/pub/RWin/src/contrib"
```

# Fake solution
I found a remotes issue that closely resembles mine https://github.com/r-lib/remotes/issues/251
In the RStudio Community link, I was able to find a hacky workaround: 
```r
> .libPaths("C:/Users/rgilmore/Desktop/test-env")
> Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS = "true")
> install.packages(c("devtools", "roxygen2", "testthat", "knitr"))
... # R installs these packages into new library path
> if (!requireNamespace("BiocManager"))
    install.packages("BiocManager")
> BiocManager::install()
... # R installs BioConductor
```

I get the warnings shown below, which look like they have something to do with the bioconductor repos, but my package still successfully installs:
![image](https://user-images.githubusercontent.com/20953530/54393508-535af300-4678-11e9-84c2-ef82b6972476.png)

# Conclusion

I have no idea what's going on here.  I just spent 4 hours trying to figure it out.  While I could try to sort through the `remotes` code and make a PR, I don't have the time.  I just wanted to get this documented.

Does anyone know what's going on here or have a real solution?  Am I missing something?

Cheers,
@grabear

**Comment by jimhester** [comment]
Think this is fixed by https://github.com/r-lib/remotes/commit/91c64b3598fc8145bd20484193c68fa9c90bce04
