### ISSUE TITLE
Remotes in DESCRIPTION file for private repos on Github

### ISSUE THREAD

**Issue by ferhat00** [r-lib/remotes#317]
I can't find in the documentation how to use the remotes package for accessing private repo's through modification of the DESCRIPTION file. Example below.

``Package: MyPackage``
``Type: Package``
``Title: My package of fcuntions``
``Version: 0.1.0``
``Author: Joe Bloggs``
``Maintainer: Jop Bloggs <joe@bloggs.com>``
``Description: My R functions``
``License: GPL-3``
``Depends:``
``  R (>= 3.5.0),``
``  tidyr``
``Imports:``
 `` tidyr``
``Remotes: joebloggs/private-repo ``
``Encoding: UTF-8``
``LazyData: true``
``RoxygenNote: 6.1.1``

Using ``devtools::install_github()`` we include the authentication token. 

What should I do in my package to access private repo's on Github?

**Comment by gaborcsardi** [comment]
You don't need to do anything. Anyone that can access the referenced private repo(s) with a token, will be able to install the package.

**Comment by ferhat00** [comment]
Many thanks.
