### ISSUE TITLE
install_github is not working 

### ISSUE THREAD

**Issue by mialj1** [r-lib/remotes#320]
Hi, 
I am having issues in installing GitHub developer packages, especially when using install_gihub it gives this error
 _Downloading GitHub repo cbail/textnets@master
Error in if (!is_dir(path)) { : missing value where TRUE/FALSE needed_

I want to install "cbail/textnets" package but every time gives the same error I have tried both on rstudio and rgui.

**Comment by alexvorobiev** [comment]
I am getting this error with devtools v.2.0.2

**Comment by jimhester** [comment]
@alexvorobiev please make sure you have updated versions of both devtools and remotes

**Comment by alexvorobiev** [comment]
@jimhester that didn't help. In my case the issue was with curl redirects. See my workaround here https://github.com/r-lib/remotes/issues/350#issuecomment-489787524
