### ISSUE TITLE
Issue installing private repos with 'devtools::install()'

### ISSUE THREAD

**Issue by Fazendaaa** [r-lib/remotes#321]
After developing a package that imports another two private packages, while trying to run 'devtools::install()' the following message is presented:
```shell
Error: HTTP error 404.
  Not Found

  Rate limit remaining: 39/60
  Rate limit reset at: 2019-03-21 18:32:13 UTC

  
Execution halted
```

My `DESCRIPTION` file is like this:
```
Imports: 
    assertthat,
    myPkgA  (>= 0.0.0.9000),
    myPkgB  (>= 0.0.0.9000)
VignetteBuilder: knitr
Remotes:  
    myOrg/myPkgA,
    myOrg/myPkgB
```

I have set the GITHUB_PAT as pointed out to me in issue #1964, but the problem still persists. The funny thing is if I remove the two packages from myOrg presented in `DESCRIPTION` file, `devtools::install()` works just fine.

This problem is troublesome due to trying to install this new package in my or any other of my coworker's machines with `devtools::install_github("myOrg/myPkgC", auth_token="GHkeyHere")` and throws the same 404 error. And I know that the GH key is working just fine because I tried to install myPkgA and myPkgB -- which both don't require any private repo -- with it and the `devtools::install_github()` of them worked just fine.

Thank you all for this awesome package, I have delayed this post over a week to be sure to analyse and fix any other probably related issue, even running GoodPractice just to be sure.

**Comment by ananthu1834** [comment]
I encountered almost the same issue (if I'm understanding the issue correctly). In a docker container built on top of rocker/rstudio-stable:3.5.2, I was able to successfully install from a private repo (say packageA) using install_github() by passing github auth token as an argument to the function. But the same failed with 404 for all private repos which depended on this packageA. Removing packageA and it does not throw a 404, but continues installation until it fails saying packageA not available. But for me, weirdly, this problem was fixed by adding the auth token to GITHUB_PAT instead of passing auth token as an argument.

**Comment by nteetor** [comment]
Experienced the same problem. I could install `{dep_A}` using `auth_token = ..`, but could not install `{pkg_depending_on_A}` with `auth_token = ..`. Specifying GITHUB_PAT in the renviron file got around the issue.

**Comment by dcolombara** [comment]
I **think** I have the same problem. 
`> devtools::install_github("PHSKC-APDE/B", auth_token = Sys.getenv("GITHUB_TOKEN"))`
`Downloading GitHub repo PHSKC-APDE/B@master
Error: Failed to install 'B' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`PHSKC-APDE`) and repo name (`apdeRecodes`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.`

I get the same error message if I try devtools::install_github, remotes::install_github, devtools::install_local, or remotes::install_local. 

My coworker can run the same command without a problem. I even shared my GITHUB_TOKEN with him and confirmed that it works perfectly for him. I also used my GITHUB_TOKEN to get a CSV from the same repo, so I know the token is valid. 

In the process of troubleshooting, I got a fresh install of R (now 3.6.2) and a fresh install of devtools and all of its dependencies. 

After hours of trying various solutions, my coworker was able to install/build the package using an Rstudio project. However, I am looking for a longer term solution. 

Any help (or a fix!) would be appreciated!

Thanks,

**Comment by sindribaldur** [comment]
I had the same issue and it was also solved by `GITHUB_PAT`. Found useful info both [here](https://csgillespie.github.io/efficientR/3-3-r-startup.html#renviron) and [here](https://happygitwithr.com/github-pat.html).

**Comment by dcolombara** [comment]
@sindribaldur, thanks so much for your response and the links. At the end of the day I restarted my computer and the next morning everything worked. I'm still not sure what happened, but I'll definitely read through the links to learn for the future.

**Comment by aminadibi** [comment]
I am having the same problem. PackagesA and PackageB are both private, and package B depends on Package A. 
When trying to install packageB I get the following error. Weirdly enough, the error gets the package name wrong. 
```
Error: Failed to install 'packageB' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`REPO`) and repo name (`PackageA`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
```

As soon as removed the dependency, everything started working.

**Comment by StoyoKaramihalev** [comment]
I'm experiencing exactly the same issue as described by @aminadibi: two private packages, B depends on A, A gets installed, B produces an error with the name of package A in the error message. I will remove the dependency to go around this, but that's not a desirable long-term solution.

**Comment by nicholas512** [comment]
I got this problem today. Installed package A (private) with `auth_token`.  Tried to install package B (private, depends on package A) with `auth_token`. Got a 404 error, and the error message used the wrong repo name (used package A in error message).  Removing the dependency isn't an option for me.

**Comment by maximilianmordig** [comment]
What about picking the `auth_token` based on a host level (e.g. github.com, otherGithub.com) and/or repository level (github.com/someOrg/someRepo). This could be passed as an option to the package or the installation functions. If this fails, the token could be queried interactively with the `credentials` package.
This covers the scenario when B depends on A, A and B are both private, but require different auth tokens.

**Comment by lvalnegri** [comment]
similar situation, but I have a chain of three packages:  A, B (dependent on A), and C (dependent on A and B). 
Using `devtools::install_github`, I can install A and B but not C, with the error message mistakenly writing down B. 
If instead I clone the repos and then use `devtools::install` the error message mistakenly writes down A. 

really really weird...

**Comment by mdemaegt** [comment]
I had the same issue and `GITHUB_BAT` also fixed the problem.
Is there meanwhile a more robust way of working that does not involve a token?

**Comment by martinzuba** [comment]
> I had the same issue and it was also solved by `GITHUB_PAT`. Found useful info both [here](https://csgillespie.github.io/efficientR/3-3-r-startup.html#renviron) and [here](https://happygitwithr.com/github-pat.html).

I have the same problem, but the links are dead. I use github PAT in strings as `auth_token` params in install_github.

**Comment by gaborcsardi** [comment]
This issue is a mix of installation problems, without reproducible examples, so I am going to close this now. If any of you still have issues with the latest version of remotes, please open separate issues. Thanks!
