### ISSUE TITLE
GitHub R package installation on Windows is failing due to temp file errors

### ISSUE THREAD

**Issue by mjsteinbaugh** [r-lib/remotes#334]
R is failing to install some packages on Windows from GitHub due to what appears to be a temp file/directory issue:

```
Downloading GitHub repo acidgenomics/basejump@master
acidgenomics-basejump-650045d/NEWS.md: Can't create '\\\\?\\C:\\Users\\MICHEA~1.STE\\AppData\\Local\\Temp\\RtmpOCMu0a\\remotes3cb683b152ea\\acidgenomics-basejump-650045d\\NEWS.md'
tar.exe: Error exit delayed from previous errors.
```

Weirdly, with my goalie package, I see a warning but then the installer runs through:

```
The downloaded binary packages are in
	C:\Users\micheal.steinbaugh\AppData\Local\Temp\RtmpOCMu0a\downloaded_packages
Warning message:
In utils::untar(tarfile, ...) :
  ‘tar.exe -zxf "C:\Users\MICHEA~1.STE\AppData\Local\Temp\RtmpOCMu0a\file3cb68abe53f5.tar.gz" -C "C:/Users/MICHEA~1.STE/AppData/Local/Temp/RtmpOCMu0a/remotes3cb682a23616"’ returned error code 1
```

```
The downloaded binary packages are in
	C:\Users\micheal.steinbaugh\AppData\Local\Temp\RtmpOCMu0a\downloaded_packages
Warning message:
In utils::untar(tarfile, ...) :
  ‘tar.exe -zxf "C:\Users\MICHEA~1.STE\AppData\Local\Temp\RtmpOCMu0a\file3cb68abe53f5.tar.gz" -C "C:/Users/MICHEA~1.STE/AppData/Local/Temp/RtmpOCMu0a/remotes3cb682a23616"’ returned error code 1
```

I'm seeing some other potentially related tempfile errors popping up on my R Windows AppVeyor CI builds, which leaves me to believe that temp file permissions are generally an issue in the current R release. Has anybody else seen this pop up?

**Comment by tdhock** [comment]
hi I'm having this issue as well. here is some code that illustrates that using the command line works, i.e. `git clone https://github.com/aldro61/mmit.git; R CMD INSTALL mmit/Rpackage` 

```
$ git clone https://github.com/aldro61/mmit.git
Cloning into 'mmit'...
]0;MINGW64:/c/Users/th798
th798@cmp2986 MINGW64 ~
$ R CMD INSTALL mmit/Rpackage/
* installing to library 'C:/Program Files/R/R-3.6.0/library'
* installing *source* package 'mmit' ...
** using staged installation
** libs
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.0/include" -DNDEBUG          -O2 -Wall  -mtune=generic -c coefficients.cpp -o coefficients.o
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.0/include" -DNDEBUG          -O2 -Wall  -mtune=generic -c interface.cpp -o interface.o
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.0/include" -DNDEBUG          -O2 -Wall  -mtune=generic -c piecewise_function.cpp -o piecewise_function.o
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.0/include" -DNDEBUG          -O2 -Wall  -mtune=generic -c solver.cpp -o solver.o
/usr/bin/sed: -e expression #1, char 1: unknown command: `C'
c:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o mmit.dll tmp.def coefficients.o interface.o piecewise_function.o solver.o -LC:/PROGRA~1/R/R-36~1.0/bin/x64 -lR
installing to C:/Program Files/R/R-3.6.0/library/00LOCK-Rpackage/00new/mmit/libs/x64
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'mmit'
    finding HTML links ... done
    compute_optimal_costs                   html  
    mmif                                    html  
    mmif.cv                                 html  
    mmif.predict                            html  
    mmit                                    html  
    mmit.cv                                 html  
    mmit.predict                            html  
    mmit.pruning                            html  
    mse                                     html  
    zero_one_loss                           html  
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (mmit)
```
but using remotes does not:
```
]0;MINGW64:/c/Users/th798
th798@cmp2986 MINGW64 ~
$ R --vanilla -e "remotes::install_github('aldro61/mmit/Rpackage')"

R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> remotes::install_github('aldro61/mmit/Rpackage')
Downloading GitHub repo aldro61/mmit@master
aldro61-mmit-b9d77ec/Rpackage/src/coefficients.cpp: Can't create '\\\\?\\C:\\Users\\th798\\AppData\\Local\\Temp\\RtmpAljvU0\\remotes2d2019e67c35\\aldro61-mmit-b9d77ec\\Rpackage\\src\\coefficients.cpp'
aldro61-mmit-b9d77ec/Rpackage/src/coefficients.h: Can't create '\\\\?\\C:\\Users\\th798\\AppData\\Local\\Temp\\RtmpAljvU0\\remotes2d2019e67c35\\aldro61-mmit-b9d77ec\\Rpackage\\src\\coefficients.h'
aldro61-mmit-b9d77ec/Rpackage/src/double_utils.h: Can't create '\\\\?\\C:\\Users\\th798\\AppData\\Local\\Temp\\RtmpAljvU0\\remotes2d2019e67c35\\aldro61-mmit-b9d77ec\\Rpackage\\src\\double_utils.h'
aldro61-mmit-b9d77ec/Rpackage/src/function_types.h: Can't create '\\\\?\\C:\\Users\\th798\\AppData\\Local\\Temp\\RtmpAljvU0\\remotes2d2019e67c35\\aldro61-mmit-b9d77ec\\Rpackage\\src\\function_types.h'
aldro61-mmit-b9d77ec/Rpackage/src/piecewise_function.cpp: Can't create '\\\\?\\C:\\Users\\th798\\AppData\\Local\\Temp\\RtmpAljvU0\\remotes2d2019e67c35\\aldro61-mmit-b9d77ec\\Rpackage\\src\\piecewise_function.cpp'
aldro61-mmit-b9d77ec/Rpackage/src/piecewise_function.h: Can't create '\\\\?\\C:\\Users\\th798\\AppData\\Local\\Temp\\RtmpAljvU0\\remotes2d2019e67c35\\aldro61-mmit-b9d77ec\\Rpackage\\src\\piecewise_function.h'
aldro61-mmit-b9d77ec/Rpackage/src/solver.cpp: Can't create '\\\\?\\C:\\Users\\th798\\AppData\\Local\\Temp\\RtmpAljvU0\\remotes2d2019e67c35\\aldro61-mmit-b9d77ec\\Rpackage\\src\\solver.cpp'
aldro61-mmit-b9d77ec/Rpackage/src/solver.h: Can't create '\\\\?\\C:\\Users\\th798\\AppData\\Local\\Temp\\RtmpAljvU0\\remotes2d2019e67c35\\aldro61-mmit-b9d77ec\\Rpackage\\src\\solver.h'
tar.exe: Error exit delayed from previous errors.

Skipping 4 packages ahead of CRAN: abind, foreach, iterators, penaltyLearning
v  checking for file 'C:\Users\th798\AppData\Local\Temp\RtmpAljvU0\remotes2d2019e67c35\aldro61-mmit-b9d77ec\Rpackage/DESCRIPTION'
-  preparing 'mmit':
v  checking DESCRIPTION meta-information
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'mmit_2017.03.15.tar.gz'
   
* installing *source* package 'mmit' ...
** using staged installation
** libs
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.0/include" -DNDEBUG          -O2 -Wall  -mtune=generic -c interface.cpp -o interface.o
interface.cpp:3:20: fatal error: solver.h: No such file or directory
 #include "solver.h"
                    ^
compilation terminated.
make: *** [C:/PROGRA~1/R/R-36~1.0/etc/x64/Makeconf:215: interface.o] Error 1
ERROR: compilation failed for package 'mmit'
* removing 'C:/Program Files/R/R-3.6.0/library/mmit'
* restoring previous 'C:/Program Files/R/R-3.6.0/library/mmit'
Error in i.p(...) : 
  (converted from warning) installation of package 'C:/Users/th798/AppData/Local/Temp/RtmpAljvU0/file2d2055764c23/mmit_2017.03.15.tar.gz' had non-zero exit status
Calls: <Anonymous> ... with_rprofile_user -> with_envvar -> force -> force -> i.p
In addition: Warning message:
In utils::untar(tarfile, ...) :
  'tar.exe -xf "C:\Users\th798\AppData\Local\Temp\RtmpAljvU0\file2d202fdd6990.tar.gz" -C "C:/Users/th798/AppData/Local/Temp/RtmpAljvU0/remotes2d2019e67c35"' returned error code 1
Execution halted
]0;MINGW64:/c/Users/th798
th798@cmp2986 MINGW64 ~
$ Calls: <Anonymous> ... with_rprofile_user -> with_envvar -> force -> force -> i.p
In addition: Warning message:
In utils::untar(tarfile, ...) :
  'tar.exe -xf "C:\Users\th798\AppData\Local\Temp\RtmpAljvU0\file2d202fdd6990.tar.gz" -C "C:/Users/th798/AppData/Local/Temp/RtmpAljvU0/remotes2d2019e67c35"' returned error code 1
Execution halted
]0;MINGW64:/c/Users/th798
th798@cmp2986 MINGW64 ~
$ 
```

**Comment by tdhock** [comment]
NB: when I installed git on windows I needed to check the box/option for symlink support (otherwise the git clone; R CMD INSTALL would not work).

the problem seems to be related to the fact that the mmit/Rpackage/src/* files are symlinks.

**Comment by tdhock** [comment]
hi @dpprdan @gaborcsardi any ideas how to fix?

**Comment by shalzsab** [comment]
I am also facing the same issue after I updated my R to version 4.0.
<install.packages("devtools")>

I get this message:

"WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/ Installing package into ‘C:/Users/shalzsab/Documents/R/win-library/4.0’ (as ‘lib’ is unspecified) also installing the dependency ‘usethis’

There is a binary version available but the source version is later: binary source needs_compilation usethis 1.6.0 1.6.1 FALSE

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/devtools_2.3.0.zip' Content type 'application/zip' length 351089 bytes (342 KB) downloaded 342 KB

package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in C:\Users\shalzsab\AppData\Local\Temp\RtmpkhJwos\downloaded_packages installing the source package ‘usethis’

trying URL 'https://cran.rstudio.com/src/contrib/usethis_1.6.1.tar.gz' Content type 'application/x-gzip' length 255052 bytes (249 KB) downloaded 249 KB

The downloaded source packages are in ‘C:\Users\shalzsab\AppData\Local\Temp\RtmpkhJwos\downloaded_packages’

And when I load the package I get this error

<library(devtools)>
Error: package ‘usethis’ required by ‘devtools’ could not be found

If I try to check the packages in the installation directory

<find.package("devtools")>
"C:/Users/shalzsab/Documents/R/win-library/4.0/devtools"

For usethis package I get this error

<find.package("usethis")>
Error in find.package("usethis") : there is no package called ‘usethis’

How can I solve this?

**Comment by dpprdan** [comment]
@shalzsab It says at the beginning of the message you posted that you do not have Rtools installed. Unless you already did (and R does not discover it) you need to install Rtools40. I.e. since you updated R, you also need to update Rtools. For more information see https://cran.rstudio.com/bin/windows/Rtools/.

**Comment by shalzsab** [comment]
@dpprdan This problem arose only after I installed the latest version of R (4.0), Rtools (40) and Rstudio (1.2.5042). I found two major issues: 1. The packages that are downloaded in Temp folder are in .rar format, 2. Rstudio don't recognize rtools installed.

**Comment by dpprdan** [comment]
@shalzsab It seems to me that both of your issues don't have anything to do with the original issue reported in this thread nor are they directly related to {remotes}. Regarding Rtools: Have you [put Rtools on the PATH](https://cloud.r-project.org/bin/windows/Rtools/)?
If that does not help, I'd suggest asking for help on https://community.rstudio.com/.

**Comment by bwasim51** [comment]
em getting this error while installing biocmanager r packages
The downloaded source packages are in
	‘C:\Users\bwasi\AppData\Local\Temp\RtmpuqxlMo\downloaded_packages’
Installation path not writeable, unable to update
  packages: boot, cluster, MASS, mgcv

**Comment by gaborcsardi** [comment]
I don't think this is remotes, it is BiocManager, no? In any case, you don't have write access to these packages, so you can't update them, at least not in the system library where they are installed. remotes has not much to do with this.

**Comment by gaborcsardi** [comment]
I am fairly sure that the original problem for `acidgenomics/basejump` was that `NEWS.md` was a symbolic link and some Windows tar implementations cannot handle that. Since then remotes has changed and falls back to the internal R tar implementation if the external one fails. So this actually works fine now on windows (with some warnings for the first external tar attempt):

```r
remotes::install_github("acidgenomics/r-basejump@a72dd2b719e6092247adc57c169692fcfe58dce4")
```

**Comment by MonicaMbabazi** [comment]
I am having this problem when installing R packages. The downloaded source packages are in
	‘/tmp/RtmpmvcZDK/downloaded_packages’. How do i go about it?
