### ISSUE TITLE
R Travis-CI failing

### ISSUE THREAD

**Issue by kkmann** [r-lib/remotes#336]
Hey,

it seems that a recent update to devtools is breaking my Travis-CI builds for R, cf. e.g.
https://travis-ci.com/kkmann/adoptr-validation-report
I manually downloaded the newest version of devtools (2.0.2) and tried running `devtools::install_dev_deps()` locally, also get the following error
```
The downloaded source packages are in
	‘/tmp/Rtmp1eQaNU/downloaded_packages’
Error in match.arg(upgrade, c("ask", "always", "never")) : 
  'arg' must be of length 1
```
Is anyone else having a similar problem / idea what could cause this?

**Comment by jimhester** [comment]
Yes, please see https://github.com/r-lib/devtools/issues/2020#issuecomment-481219296 for a workaround.
