### ISSUE TITLE
`install_git(hub)`: No option to have a shallow clone (`git clone --depth=1`) - Howto best deal with multi package repos?

### ISSUE THREAD

**Issue by r-cheologist** [r-lib/remotes#338]
I'm facing a situation where a family of packages is housed in a single `github` repo.
When I sequentially install the family members, I run into `github`'s rate limiting (and yes, I'm using the authentitcation token option).
When looking through the code of `remotes::install_github`, it becomes apparent that there are two ways of using `git`: 1) `git2r` (which is convenient, but appears NOT to support shallow cloning) and 2) external git, calling `system` to work with the OS's `git` client (and explicitly sets `depth = 1`).
Before I reinvent the wheel, I'm asking (or requesting to implement) whether an `install_git` equivalent `git = "external"` in conjunction with `depth = 1` could be made accessible in all higher level functions (such as `install_github`)? Or are there `github`/`gitlab`/... API limitations preventing this?

**Comment by jimhester** [comment]
The depth has nothing to do with the rate limiting, in fact `install_github()` doesn't do a clone at all, it downloads the zip file from the repo.

**Comment by r-cheologist** [comment]
My comment in #339 ends the discussion started here.
