### ISSUE TITLE
Feature Request: `subdir` should accept multiple directory names

### ISSUE THREAD

**Issue by r-cheologist** [r-lib/remotes#339]
When thinking about the issue I bring up in #338, it occurred to me that much of what I'm facing when a) tracking a family of `R` packages in a single `github` repo, b) installing them sequencially, c) `remotes`'s `git2r`-functionality NOT performing shallow clones and d) me thus being hit with rate limiting by `github` , might be alleviated if `remotes::install_github` (and the rest of that family of functions) would allow for multiple `subdir`s in one call, iterating over them for installation after a single `git` cloning action.

**Comment by jimhester** [comment]
Sorry, this way of organizing repositories is not something we recommend doing and not something we are going to add code to support. I would suggest you write yourself a helper function that does something like shallow clone the repository then use `remotes::install_local()` to install the individual packages from the subdirectories.

**Comment by r-cheologist** [comment]
Understood. Would `remotes::install_local` retain the `git` origin information for the package(s)?

**Comment by r-cheologist** [comment]
Would it be feasible for `remotes` to export/expose the underlying downloading function(s)?

**Comment by r-cheologist** [comment]
I understand the argument about repo organisation partially, but consider a largish framework of packages, such as the [`assertive`](https://bitbucket.org/richierocks/assertive) family by @richierocks - users have the benefit to being able to only install/use a small part of the entire functionality, while the dev(s) can work with limited interdependence hell between the module packages.

I have come up with the following:

    install_git_multiple_subdirs <- function(
      repo, subdirs, host = NULL,
      remote_type = c("bitbucket", "git", "github", "gitlab"),
      repos = BiocManager::repositories()) {
      remote_type <- match.arg(remote_type)
      ## Download bundle (bitbucket, github, gitlab) or shallow clone (git) repo
      ## Heavily relying on (unexported) functionality from `remotes`
      if (is.null(host)) host <- switch(
        remote_type,
        bitbucket = "api.bitbucket.org/2.0",
        git = stop("`host` definition required."),
        github = "api.github.com",
        gitlab = "gitlab.com")
      remote <- switch(remote_type,
        bitbucket = remotes:::bitbucket_remote(repo = repo, host = host),
        git = remotes:::git_remote(
          url = utils::URLencode(paste(host, repo, sep = "/")), git = "external"),
        github = remotes:::github_remote(repo, host = host),
        gitlab = remotes:::gitlab_remote(repo, host = host))
      bundle <- remotes:::remote_download(remote)
      bundle_is_tarball <- grepl(pattern = "\\.tar\\.gz$", x = bundle)
      on.exit(unlink(bundle, recursive = TRUE), add = TRUE)
      ## Assure presence of requested subdirs
      if (bundle_is_tarball) {
        subdirs_present <- untar(tarfile = bundle, list = TRUE,
          compressed = TRUE)
        subdirs_present <- unique(sapply(
          subdirs_present,
          function(x){
            unlist(strsplit(x, split = "[/\\]"))[2]
          }))
      } else {
        subdirs_present <-  list.dirs(path = bundle, recursive = FALSE)
      }
      names(subdirs_present) <- basename(subdirs_present)
      missing_subdirs <- setdiff(subdirs, names(subdirs_present))
      if (length(missing_subdirs) != 0) stop("Requested subdirs not present: ",
                                             paste(subdirs, collapse = ", "))
      ## Iteratively install the subdir-contained packages
      for (sd in subdirs) {
        remotes::install_local(path = bundle, subdir = sd, dependencies = TRUE,
          upgrade = "never", repos = repos)
      }
    }

which appears to do what I want. Note the many `:::` (unexported) parts from `remotes` I'm using to benefit from your excellent functionality - please consider whether some of that could be exposed/exported.
