### ISSUE TITLE
tar error install_github

### ISSUE THREAD

**Issue by kuzmenkov111** [r-lib/remotes#350]
Hello!

I have a trouble with remotes::install_github("user/package"). R 3.5.1 Microsoft R Open. Ubuntu 18.04 in container. There is an error in tar after just rebuilding container without changing anything.

`remotes::install_github('rstudio/DT')
Downloading GitHub repo rstudio/DT@master
tar:
This does not look like a tar archive
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
tar:
This does not look like a tar archive
gzip:
stdin: unexpected end of file
tar:
Child returned status 1
tar:
Error is not recoverable: exiting now
Error in getrootdir(untar(src, list = TRUE)) :
length(file_list) > 0 is not TRUE
Calls: <Anonymous> ... source_pkg -> decompress -> getrootdir -> stopifnot
In addition:
Warning messages:
1:
In utils::untar(tarfile, ...) :
‘tar -xf '/tmp/RtmpitCFRe/file2677442609b8.tar.gz' -C '/tmp/RtmpitCFRe/remotes267752f2629f'’ returned error code 2
2:
In system(cmd, intern = TRUE) :
running command 'tar -tf '/tmp/RtmpitCFRe/file2677442609b8.tar.gz'' had status 2
Execution halted` 

May tell me what is going wrong?

**Comment by jimhester** [comment]
It looks like your tar program is not working correctly, or possibly the download is not complete. What does `Sys.getenv("tar")` return?

**Comment by alexvorobiev** [comment]
I ran it in the debugger. At least in my case the issue was not with tar. The real issue is the default download method (curl) does not follow HTTP redirects (and gives no warnings about that). The result is a zero-length file which tar cannot unpack. I don't know whether it is github itself or corporate firewalls/proxy/MITM. The workaround is to add this curl option
```
options(download.file.extra = paste0("-L ", getOption("download.file.extra", default = ""))
```
After that `install_github` works again.

**Comment by nextpagesoft** [comment]
I have had the same issue (Ubuntu 19.04, R 3.6.0). First of all check if the downloaded file tar.gz has any content at all. Name of the file is included in the error message. @kuzmenkov111  post it is `'/tmp/RtmpitCFRe/file2677442609b8.tar.gz'`:

```r
file.info("/tmp/RtmpitCFRe/file2677442609b8.tar.gz")
```

In my case it had size 0 so clearly downloading was not successful, so I started digging in.

[Line 73](https://github.com/r-lib/remotes/blob/master/R/download.R#L73) in function `base_download` selects download method. In my case `getOption("download.file.method")` was returning `curl`. Setting it to `libcurl`:

```r
options("download.file.method" = "libcurl")
```

cured the problem with no content and `devtools::install_github` succeeded.

I don't know how option "curl" was set in the first place. Maybe this is what R 3.6.0 defaults to.

**Comment by DaveParr** [comment]
Same issue, macOS Mojave, 10.14.4, R 3.6.

This exact issue has hit me multiple times with multiple packages now. And 

`options(download.file.extra = paste0("-L ", getOption("download.file.extra", default = "")))` has worked each time so far.
