### ISSUE TITLE
GitLab personal access tokens need api scope

### ISSUE THREAD

**Issue by aornugent** [r-lib/remotes#355]
Hia,

`install_gitlab` attempts to use a url encoded path to the repo (see: https://github.com/r-lib/remotes/issues/327)  and failing:

```{r}
remotes::install_gitlab("jimhester/covr")
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot open URL 'https://gitlab.com/api/v4/projects/jimhester%2Fcovr/repository/commits/master
```

Navigating directly to [https://gitlab.com/jimhester%2Fcovr](https://gitlab.com/jimhester%2Fcovr) doesn't work either. [https://gitlab.com/jimhester/covr](https://gitlab.com/jimhester/covr) does.

**Comment by aornugent** [comment]
After some snooping it appears the issue isn't URL encoding, rather the personal access token here: https://github.com/r-lib/remotes/blob/1f657ec067088add76adedfcc9a0ea2a45aac9e9/R/install-gitlab.R#L138

```
# Works
gitlab_commit("jimhester", "covr", pat = NULL)
[1] "257a963aaf9b5bdbafc2cec85f14b95ed86a8561"

# Doesn't work
gitlab_commit("jimhester", "covr", pat = gitlab_pat())
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot open URL 'https://gitlab.com/api/v4/projects/jimhester%2Fcovr/repository/commits/master?private_token=[removed]' 
```

The [GitLab docs](https://docs.gitlab.com/ee/api/#personal-access-tokens) suggest the API call is well formed, so it's unclear what is going wrong. 
Happy to create a pull request if someone can point me in the right direction.

**Comment by aornugent** [comment]
My bad. I had the wrong scope set on my access token.

For future reference: [Limiting scopes of a personal access token](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html#limiting-scopes-of-a-personal-access-token)

**Comment by trafficonese** [comment]
I am still getting the same error from your first post although my personal access tokes has api scope.

This is my (anonymized) command:
`install_gitlab(repo = "user/repo", auth_token = "********", host = "gitlab.mycompany.eu")`

And I am still getting this error:

> Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
>   cannot open URL 'https://gitlab.mycompany.eu/api/v4/projects/user%2Frepo/repository/commits/master?private_token=********

The url of the repo is https://gitlab.mycompany.eu/user/repo and it is currently an Internal repo.

What am I missing?

**Comment by aornugent** [comment]
I'll be honest, I got lazy and gave my token all the rights I could. It may also need `read_repository` scope? 

Your error indicates that `install_gitlab` is failing to look up the commit reference on [line 135](https://github.com/r-lib/remotes/blob/1f657ec067088add76adedfcc9a0ea2a45aac9e9/R/install-gitlab.R#L135). If you want to verify that the link itself works you can use `httr`

```{R}
tmp <- httr::GET("https://gitlab.mycompany.eu/api/v4/projects/user%2Frepo/repository/commits/master?private_token=********")
httr::content(tmp)
```

You should get a human-readable error if your token doesn't have sufficient access.

**Comment by trafficonese** [comment]
It does not work when I add `user/repo` but when instead I use the `project id` as stated in the API docs:
[GET /projects/:id/repository/commits](https://docs.gitlab.com/ee/api/commits.html)

So instead of 
`/projects/user%2Frepo/`
I need this
`/projects/5/`

**Comment by aornugent** [comment]
How frustrating. You can see in the docs that the `id` and encoded URL should be interchangeable. It does mention that you need to be the repository 'owner'. Can you check that you can find your repo in: 
```
httr::GET("https://gitlab.mycompany.eu/api/v4/projects?owned=true&private_token=********")
```
Kindly lifted from: https://stackoverflow.com/a/54925461. I don't have an example to test on sorry.

**Comment by trafficonese** [comment]
Ah I didn't own it, but the "developer" group owned it, so I transfered to my account, now the project shows up when using `owned=true` but I still get the `cannot open URL` error when trying `install_gitlab`.

**Comment by aornugent** [comment]
I don't fully understand the terms, but I would've thought using `install_gitlab("owner/repo") would have worked as well.

If the error you're getting looks like this:

```
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot open URL 'https://git.hostname.tld/username/reponame/repository/archive.tar.gz?ref=master&private_token=GITLAB_PAT'
```

then pull request https://github.com/r-lib/remotes/pull/359 that will adresss the issue.

**Comment by aornugent** [comment]
Pull request is merged. Can you please test this has fixed your issue?

**Comment by trafficonese** [comment]
Unfortunately it is still not working and I am getting the same error.

`remotes::install_gitlab(repo = "user/repo", auth_token = '**********', host = "gitlab.mycompany.eu")`

> cannot open URL 'https://gitlab.mycompany.eu/api/v4/projects/user%2Frepo/repository/files/DESCRIPTION/raw?ref=master&private_token=**********&private_token=**********'

Interestingly it adds the private_token twice now to the request?

I set the project to private instead of internal, the Token has the following scope = `api, read_user, read_repository`, I can see it with `owned=true` and I can access it with the **project ID** but not with **user/repo**.

With project ID I see the package:
`https://gitlab.mycompany.eu/api/v4/projects/124/repository/files/DESCRIPTION/raw?ref=master&private_token=**********`

But with 
`https://gitlab.mycompany.eu/api/v4/projects/user/repo/repository/files/DESCRIPTION/raw?ref=master&private_token=**********`
I get a **Not Found** error.

**Comment by dpprdan** [comment]
@trafficonese this could also be an issue with your gitlab server, in particular the reverse proxy. 

Can you try the following URL in your browser (make sure you're _not_ logged in your gitlab server, so the API needs to use the token):

`https://gitlab.mycompany.eu/api/v4/projects/user%2Frepo/repository/archive?private_token=*******`

It should give you a .tar.gz file. 

(The Gitlab API only accepts `user%2Frepo`, not `user/repo` by the way.)

**Comment by dpprdan** [comment]
I think this can be closed, correct @trafficonese?
@aornugent Regarding your initial problem with the correct API scope: I opened a [feature request](https://gitlab.com/gitlab-org/gitlab-ce/issues/61060) for Gitlab CE to enable the read_repository scope for Repositories API.
