### ISSUE TITLE
update_packages(force = TRUE) does not work as expected.

### ISSUE THREAD

**Issue by jakob-r** [r-lib/remotes#356]
According to the help:
> force: Force installation, even if the remote state has not changed since the previous install.

But even with `force = TRUE` after that line the list is reduced to the packages that need an update:
https://github.com/r-lib/remotes/blob/91c64b3598fc8145bd20484193c68fa9c90bce04/R/deps.R#L435

**Comment by jimhester** [comment]
I apologize if this is confusing, but `force` only applies when trying to update non-CRAN remotes, it doesn't universally reinstall all packages. Perhaps it would be easier to reason about to do as you suggest, but it would require rewriting a decent amount of the code, so is unlikely to happen.
