### ISSUE TITLE
Install dependencies even when package itself is up to date

### ISSUE THREAD

**Issue by jeroen** [r-lib/remotes#357]
Remotes does not install dependencies when installing with `dependencies = TRUE` if the package was already installed (but not the dependencies). For example I use:

```r
remotes::install_local(dependencies = TRUE)
# Skipping install of 'openssl' from a local remote, the SHA1 (1.3) has not changed since last install.
#  Use `force = TRUE` to force installation
```

And then when checking I get:

```
Error in ("base" %:::% "library")("testthat") :
  there is no package called ‘testthat’
```

**Comment by gaborcsardi** [comment]
Yes, I believe that this is known behavior, and it happens because remotes installs packages as it walks the dependency graph. If you want to make sure that it always installs everything, you have to specify `force = TRUE`.

**Comment by jeroen** [comment]
OK if this is known, the issue may be closed. I was expecting that if the installed version is equal to the remote version, you would still walk the dependency graph based on the local installed DESCRIPTION.

**Comment by jimhester** [comment]
Yeah this is expected in remotes, but `pak::pak_install()` does as you describe I believe.

For local packages you can use `remotes::install_deps(dependencies = TRUE)` to install the dependencies.

**Comment by jeroen** [comment]
Ok great, thanks for the details.
