### ISSUE TITLE
Install only CRAN dependencies

### ISSUE THREAD

**Issue by trinker** [r-lib/remotes#358]
I'm using `install_local` and I want to supply the path to the local package but only want remotes to install CRAN packages.  Is there a way to do this?

The reason is: It errors on provate bitbucket repos which are already installed on the machine.  SO it didn't need to install this dependency but tries to check it and errors because it can't find it.

**Comment by jimhester** [comment]
I think something like this would work 

```r
deps <- remotes::package_deps()
# subset the dependencies however you wish
update(deps)
remotes::install_local(dependencies = FALSE)
```
