### ISSUE TITLE
Error: Does not appear to be an R package (no DESCRIPTION)

### ISSUE THREAD

**Issue by jeroen** [r-lib/remotes#370]
When calling `install_deps()` and one of the dependencies already has a dev version installed, we regularly this error:

```r
remotes::install_deps(dependencies = TRUE, upgrade = TRUE)
```

<img width="759" alt="Screen Shot 2019-05-21 at 10 27 42 AM" src="https://user-images.githubusercontent.com/216319/58117296-17319a80-7bb3-11e9-9bc3-a0089dbf2ea8.png">

Looks like the `DESCRIPTION` file of the __installed__ dependency package contains this:

```
Maintainer: Jeroen Ooms <jeroen@berkeley.edu>
RemoteType: local
RemoteUrl:
        /private/var/folders/hp/fg4q7m353d91v9mgm4d1stvh0000gn/T/RtmpJkrZ7F/magick_2.0.9000.tar.gz
Built: R 3.6.0; x86_64-apple-darwin15.6.0; 2019-05-20 22:00:37 UTC; unix
```

I'm not sure how that `RemoteUrl` got in there but that file no longer exists.

**Comment by gaborcsardi** [comment]
This is probably an issue with tar: #282

**Comment by jeroen** [comment]
I don't think this is the problem. I think the issue is that when a local source package `tar.gz` was installed via `remotes::install_local()`, it records the source package as the `RemoteUrl`. But that source package might no longer be avaialble when remotes tries to upgrade the package.

**Comment by gaborcsardi** [comment]
Oh, OK. Yes, that should `tryCatch()` I guess.
