### ISSUE TITLE
install_deps() - Install only required dependencies

### ISSUE THREAD

**Issue by kenahoo** [r-lib/remotes#373]
There are 3 behaviors that `install_deps(upgrade=...)` can have:

  * "always" - always install any newer version of all dependencies (I think - its behavior is not actually documented)
  * "never" - never upgrade any other package, just do new installs of missing packages (I think)
  * "ask" - let the user choose whether to upgrade each individual package

(The additional "default" option just lets you choose one of those 3 options via an environment variable.)

None of these are what I think most people would want in an automated testing situation, which is:

  * Only upgrade packages that must be upgraded according to the version requirements in `DESCRIPTION`

For example, if package `A`'s `DESCRIPTION` file has

```
Imports: B (>= 1.1), C, D, E, ...
```

and version 1.0 of `B` is installed, then the only way to get `B` upgraded is to also upgrade all the other dependencies `C`, `D`, `E`, ... even if they already satisfy the requirements.

Not sure whether this requires `pak`-level capabilities or not.  It could be added very easily with the changes I proposed in PR #305, though.

**Comment by jimhester** [comment]
No, if the current dependency doesn't satisfy the requirements it is automatically installed without prompting.

**Comment by kenahoo** [comment]
That does not seem to be the case in my testing.

**Comment by kenahoo** [comment]
Here's what happens for me:

```
> packageVersion('DataFiltering')
[1] '1.0'
> substr(read.dcf('DESCRIPTION')[,'Imports'], 1, 24)
                    Imports 
"DataFiltering (>= 1.1),\n" 
> packageVersion('remotes')
[1] '2.0.4'
> remotes::install_deps('.', upgrade="never")
> 
```
(Nothing is installed in that last command.)

**Comment by kenahoo** [comment]
@jimhester are you able to reproduce that behavior?

**Comment by kenahoo** [comment]
@jimhester This is still an issue for us, have you been able to look at it?  Thanks.

**Comment by kenahoo** [comment]
I retried with version 2.1.0 of `remotes`, same result:

```
> packageVersion('dplyr')
[1] '0.8.1'

> substr(read.dcf('DESCRIPTION')[,'Imports'], 17, 31)
          Imports 
"dplyr (> 0.8.2)" 

> packageVersion('remotes')
[1] '2.1.0'

> remotes::install_deps('.', upgrade="never")
Installing 10 packages: igraph, pbapply, aws.s3, neuralnet, segmented, doParallel, aws.signature, Deriv, foreach, iterators
...
```

`dplyr` is not upgraded to a suitable version.

**Comment by kenahoo** [comment]
Would love to know if this is on the `remotes` people's radar.  Maybe I'll need to investigate it and add a fix to to [our fork of this package](https://github.com/focusenergy/r-repositories)?  I don't know yet what's going to be necessary to fix it, though.

**Comment by kenahoo** [comment]
I'm going to conclude this is *not* on anyone's radar, since there hasn't been a comment in 6 months, and no acknowledgement ever that something's broken.

This hits us pretty often - the versions of prerequisites given in `DESCRIPTION` are not installed by `install_deps()`, so automated builds pass or fail when they shouldn't, and we end up deploying/blocking releases when we shouldn't.

**Comment by jimhester** [comment]
This is just out of scope for remotes, remotes is basically just a wrapper around `install.packages()`, and in `?install.packages` it states, 

> You are advised to run ‘update.packages’ before ‘install.packages’ to ensure that any already installed dependencies have their latest versions.

So if you are doing anything but `upgrade = TRUE` you have to deal with any resulting consequences yourself.

pak does handle this case however, so if you are really interested in this functionality I would look there.

**Comment by kenahoo** [comment]
Unfortunately, `pak` doesn't solve this either, because if I understand https://github.com/r-lib/pak/issues/122 correctly, `pak` doesn't actually honor *any* version requirements.
