### ISSUE TITLE
install_github() does not work for specific package in R 3.6.0

### ISSUE THREAD

**Issue by wvictor14** [r-lib/remotes#374]
Apologies if this is not the correct forum to find help for this problem.

I found that my package I developed no longer installs successfully using `install_github()` in R 3.6.0

```{r}
remotes::install_github('wvictor14/planet')
```
I tested it and the install works fine in R 3.5.2, and R 3.5.1, but when I run it on R 3.6.0 I get the following error messages:

```{r}
devtools::install_github('wvictor14/planet')
Downloading GitHub repo wvictor14/planet@master
√  checking for file 'C:\Users\vyuan\AppData\Local\Temp\5\RtmpQRuNgS\remotes4e4c719752f\wvictor14-planet-b474a87/DESCRIPTION' ... 
-  preparing 'planet':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'planet_0.0.1.tar.gz' (9.3s)
   
* installing *source* package 'planet' ...
** using staged installation
** R
Error in lazyLoadDBinsertVariable(vars[i], from, datafile, ascii, compress,  : 
  (converted from warning) internal error 10 in R_compress3
ERROR: unable to build sysdata DB for package 'planet'
* removing 'C:/Users/vyuan/Documents/R/R-3.6.0/library/planet'
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/vyuan/AppData/Local/Temp/5/RtmpQRuNgS/file4e4c1a371d06/planet_0.0.1.tar.gz’ had non-zero exit status
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
```

I'm not sure exactly what's going on. Possibly something wrong with the sysdata.rda file?

**Comment by DaveParr** [comment]
Potentially related: https://github.com/r-lib/remotes/issues/350

**Comment by jimhester** [comment]
There is a warning during installation, but it is possibly a false positive, you can use the following to install it in spite of the warning.

```r
withr::with_envvar(c(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true"), 
  remotes::install_github('wvictor14/planet')
)
```

**Comment by wvictor14** [comment]
Thank you for the help! This does work for me. I won't reopen this issue, but I would like to figure out the reason for the warning. I'm not super experienced with R package development, so any pointers would be greatly appreciated.

**Comment by wvictor14** [comment]
I've discovered that this problem is unique to linux

The workaround still works when installing on linux:

> withr::with_envvar(c(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true"), 
>   remotes::install_github('wvictor14/planet')
> )

But for some reason users cannot access or import data objects with `data()`

I also tried updating sysdata.rda as some other threads mentioned this may be the reason, but this didn't solve anything.
