### ISSUE TITLE
add crancache to DESCRIPTION

### ISSUE THREAD

**Issue by vobencha** [r-lib/remotes#382]
Hi @jimhester ,
Any reason why crancache isn't in Suggests or Enhances?
Val

**Comment by jimhester** [comment]
crancache isn't on CRAN and is only a soft dependency that speeds things up if it is installed. @gaborcsardi do you think we should just remove it entirely or leave it as is?

**Comment by gaborcsardi** [comment]
We can remove it as soon as revdepcheck does not need it.

**Comment by vobencha** [comment]
OK, thanks for the background.
