### ISSUE TITLE
Installation fails if a suggests is unavailable

### ISSUE THREAD

**Issue by jeroen** [r-lib/remotes#384]
See example below. Remotes detects that `BiocInstaller` is not available and will be skipped, but then still errors before starting the installation.

```r
> remotes::install_github('ropenscilabs/available', upgrade = TRUE, dependencies = TRUE)
Downloading GitHub repo ropenscilabs/available@master
mime  (0.6 -> 0.7  ) [CRAN]
yesno (NA  -> 0.1.0) [CRAN]
Skipping 1 packages not available: BiocInstaller
Skipping 1 packages ahead of CRAN: curl
Installing 3 packages: BiocInstaller, mime, yesno
Error: (converted from warning) package ‘BiocInstaller’ is not available (for R version 3.6.0)
```

**Comment by gaborcsardi** [comment]
Yes, remotes converts warnings to errors. You can use `R_REMOTES_NO_ERRORS_FROM_WARNINGS=true` see the README.

**Comment by jeroen** [comment]
I was hoping it wouldn't even yield the warning because it knows the package should be skipped. But still give errors for genuine dependency installation errors.

**Comment by gaborcsardi** [comment]
This is not possible currently, because we cannot distinguish between the warnings coming from `install.packages()`.

**Comment by jeroen** [comment]
OK fair enough, I'll switch to `R_REMOTES_NO_ERRORS_FROM_WARNINGS` to install. Thanks

**Comment by gaborcsardi** [comment]
In theory you could install the hard deps first, and then the soft deps with the env var set. But I don't think it is currently easy to install just the soft deps.
