### ISSUE TITLE
Implement support for gitlab?

### ISSUE THREAD

**Issue by richfitz** [r-lib/remotes#40]
Probably as popular now as bitbucket, and has acquired gitorious

**Comment by richfitz** [comment]
Sorry, trigger happy butter fingers!

It would be great if remotes support could be expanded to support gitlab.  I could probably work a PR up if you're flat out with other stuff

**Comment by gaborcsardi** [comment]
HAha. PRs are great! Maybe you could wait until the fate of the great devtools split up is decided. https://github.com/hadley/devtools/pull/1310 

Just because that will potentially change a lot of stuff.

**Comment by ConorIA** [comment]
I wish I had thought to read @gaborcsardi's last comment before hacking away ... anyway I've made a start in #50. @richfitz, testing and feedback is welcome! 

Given the similarity of the some of the internal GitHub and GitLab functions, I imagine in some future version these could be performed by a single function with individual wrappers for each service.
