### ISSUE TITLE
Enable installing packages from Artifactory and Azure DevOps? 

### ISSUE THREAD

**Issue by paulponcet** [r-lib/remotes#400]
Artifactory and Azure DevOps are popular artifact repository managers that support R packages. Would it be possible to create `install_artifactory()` and `install_azuredevops()` functions similar to other `install_xxx()` functions?

**Comment by jimhester** [comment]
We would definitely review a PR that did so.

**Comment by brshallo** [comment]
Until then, I've just used `remotes::install_git("<clone url>", git = "external")` to install R packaged from our company's internal Azure Devops and Active Directory set-up.

**Comment by jimhester** [comment]
It would be possible, but I don't think we have the development bandwidth to write, support and test this feature. I think it is better off done in a separate package.
