### ISSUE TITLE
Strange error with install_github on windows with rtools

### ISSUE THREAD

**Issue by kotoroshinoto** [r-lib/remotes#405]
Trying from R started in windows CMD: https://pastebin.com/SjXKTEgQ
Trying from R terminal in RStudio: https://pastebin.com/yRrE1jCe

It previously worked on this machine. Works on my other windows machine right next to me with almost the same set of software and configuration.

I have no idea what is causing this.

R version is 3.6.1; reinstalled the latest Rtools; made sure it (and R's bin directory) were visible on the Path.

for the sake of it, here is the content of my Path env variable (from within ConEmu):

```
"C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\Rtools\bin;C:\Program Files\R\R-3.6.1\bin;C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;C:\Program Files\Python37\Scripts\;C:\Program Files\Python37\;C:\Program Files\Microsoft MPI\Bin\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Python36\Scripts\;C:\Program Files\Python36\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Dell\Dell Data Protection\Encryption\;C:\Program Files (x86)\SSH Communications Security\SSH Tectia\SSH Tectia AUX;C:\Program Files (x86)\SSH Communications Security\SSH Tectia\SSH Tectia AUX/Support binaries;C:\Program Files (x86)\SSH Communications Security\SSH Tectia\SSH Tectia Broker;C:\Program Files (x86)\SSH Communications Security\SSH Tectia\SSH Tectia Client;C:\Windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\texlive\2017\bin\win32;C:\Program Files\dotnet\;C:\Program Files\doxygen\bin;C:\Program Files (x86)\Calibre2\;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files\OpenSSH\bin;C:\Program Files\CMake\bin;C:\Users\mgooch\AppData\Local\Pandoc\"
```

edit (merging my comment into original report): 
I was able to work around it for the moment by installing the dependencies using install.packages based on what is listed in the DESCRIPTION file (including my dependency on another github repo package, as this error is universal). I install the CRAN packages with one call, and for the two github repos I set repos=NULL and type="source", supply the tarball link for a tagged commit and it downloads, compiles, installs, etc.

so the underlying functionality appears to all be fine, its something specific to remotes::install_github that is failing. Either it is failing to properly download the tarball through the github api, or it is failing to properly call the tar executable (or both).

{the main package i'm trying to install is my own, i'm attempting to make sure deployment / running functions etc works from an end-user style environment.)

I reported my problem on devtools to a thread that sounded quite similar to my issue, (his might be slightly distinct, but it probably merits sharing and cross linking here)

r-lib/devtools#2066

**Comment by kotoroshinoto** [comment]
I was able to work around it for the moment by installing the dependencies using install.packages based on what is listed in the DESCRIPTION file (including my dependency on another github repo package, as this error is universal). I install the CRAN packages with one call, and for the two github repos I set repos=NULL and type="source", supply the tarball link for a tagged commit and it downloads, compiles, installs, etc.

so the underlying functionality appears to all be fine, its something specific to remotes::install_github that is failing. Either it is failing to properly download the tarball through the github api, or it is failing to properly call the tar executable (or both).

{the main package i'm trying to install is my own, i'm attempting to make sure deployment / running functions etc works from an end-user style environment.)

**Comment by kotoroshinoto** [comment]
I reported my problem on devtools to a thread that sounded quite similar to my issue, (his might be slightly distinct, but it probably merits sharing and cross linking here

**Comment by kotoroshinoto** [comment]
whatever is causing this problem might ALSO be related to the weirdness I experienced with rstudio: https://github.com/rstudio/rstudio/issues/5155

**Comment by gnguy** [comment]
I looked into this a little bit, as I have also run into this issue since upgrading to R 3.6.0. The root issue for my specific use-case is that RTools' tar installation appears to be the one getting used, and that my computer's security software appears to be blocking the invocation of the RTools tar.exe on the .tar.gz tempfile as suspicious behavior.

What I'm not clear on is whether this change is a downstream result of changes in RTools and/or its relationship with R 3.6 (RTools' changelog doesn't mention anything) or if changes related to the current storage directory (in AppData/Local/Temp) may be causing issues. I haven't seen any substantive changes in the remotes codebase to indicate that the file location or methods called around untar-ing the tar.gz file have changed on the remotes side, but I may be wrong there.

**Comment by jimhester** [comment]
I am pretty confident that this issue is not the result of code in remotes and could be fixed by configuration changes on your machine, therefore I am closing this issue. You may try asking it at <https://community.rstudio.com> and see if anyone else has any advice or has a similar situation.
