### ISSUE TITLE
Trailing whitespace in package name confuses install_deps

### ISSUE THREAD

**Issue by dernst** [r-lib/remotes#414]
My colleague mistakenly wrote in the DESCRIPTION file of one of his packages after "Package:" a space before the line-end [1] . Subsequently `install_deps` was unable to install this package as a dependency.

Apparently `read_dcf` exlicitly keeps all whitespaces from the DESCRIPTION file [2]. IMO there should be an exception for the package name or a warning should be triggered. Something like...
```
as.list(read.dcf(path, keep.white = setdiff(fields, "Package"))[1, ])
```

`combine_deps` later then compares the package names stated in the dependencies against the package names from the DESCRIPTION files, which ultimately fails because of the trailing whitespace.

[1] https://github.com/a-maldet/composerr/blob/c5b4de887b50bddbe1eae60e1d1ce699dde5673f/DESCRIPTION#L1
[2] https://github.com/r-lib/remotes/blob/e78d84ea6c9f858572ba163a1c31a92507fbd5cb/R/dcf.R#L3

**Comment by jimhester** [comment]
I sympathize with your colleague! Unfortunately we need to preserve whitespace in fields for other cases, and special casing the package field would be too much effort to be worthwhile. So I am going to close this issue.
