### ISSUE TITLE
remotes::install_github repos= option does not get passed to child installations

### ISSUE THREAD

**Issue by colearendt** [r-lib/remotes#422]
Let's say packageA is a GitHub package that depends on packageB (another GitHub package). packageB depends on xml2, let's say.

If I specify `remotes::install_github("packageA", repos = "myrepository")`, everything looks fine.

However, if an update is required, somewhere `remotes::install_github("packageB")` gets called (notably - _without_ the "repos" option that I specified before).

As a result, the only workaround is to change your global `options("repos")`. The `repos = ` option does not get propagated as it should. This is particularly troubling for non-interactive installations (where I do not have the opportunity to select which updates / installations happen), and where my custom repository (RSPM in this case) does not have the latest version of a package. As a result, I get a version of `xml2` installed (from CRAN, for instance) that is not reproducible.

I have a pretty unique use case, so perhaps this is not a problem for anyone else. I found the behavior surprising and hard to reason about, though 😄

**Comment by jimhester** [comment]
I think this should be fixed by https://github.com/r-lib/remotes/pull/423, can you verify it is?

**Comment by colearendt** [comment]
I don't think it is... 😬 It's a weird thing to reproduce, but I installed `r-lib/remotes@fix-repos` and then `remotes::install_github(repos = )` is still pulling from `options("repos")` and not from the provided `repos=` option.

**Comment by chasemc** [comment]
I have been having some issues too that seem highly similar if not the same if this. It is causing some pain. I can look into it too. I'm doing some weird stuff in mac that is manifesting as only a portion of a package's dependencies respecting the 'repo' argument.

**Comment by chasemc** [comment]
I'll try to come up with a reprex this week though my case is unique as well. Except that I might be having trouble with the 'lib' argument not seeming to pass down, but like I said I'll try to confirm this week.
