### ISSUE TITLE
help.start()  on Linux  display blank page in browser

### ISSUE THREAD

**Issue by sandsindhu** [r-lib/remotes#446]
Hi,

I have embedded R into Qt application. The help('topic') and help.start() works fine on Windows. However on CentOS 7.2, e.g. help('print') executes silently without any error, but it doesn't launch any browser window.  The help.start() command does bring up the browser, but its blank and status bar shows Waiting for 127.0.0.1:29662/doc/html/index.html.   

Appreciate any suggestion.

Thanks

**Comment by jimhester** [comment]
Ok, but I am not sure what that has to do with the remotes package.
