### ISSUE TITLE
Plot window doesn't  respond to mouse click on X (close) tool button

### ISSUE THREAD

**Issue by sandsindhu** [r-lib/remotes#447]
Hi,

I have embedded R into Qt application. On CentOS7.2, the plot command works fine, plots data nicely, but when i try to close it by clicking on close tool button it doesn't closes. Also, when i maximize it, the plot window becomes blank i.e. it doesn't repaint.

I am using R-3.6.0. Pls not that on Windows, it works just fine.

Appreciate any comment

Thanks

**Comment by sandsindhu** [comment]
I am surprised that its closed without any comment.  Is this a known problem?

**Comment by jimhester** [comment]
This is the repo for the remotes R package, it is not a general R help page.

What you are reporting has nothing to do with the remotes package.

**Comment by sandsindhu** [comment]
Sorry didn't know.  Where should I post this question if you may suggest? Thanks!
