### ISSUE TITLE
Listing packages not installed from CRAN or Bioconductor

### ISSUE THREAD

**Issue by mjsteinbaugh** [r-lib/remotes#449]
Maybe I'm missing this in the remotes documentation, but is there an easy way to list packages installed from GitHub? Is there an alternative to `utils::installed.packages()` that contains remote information?

**Comment by mjsteinbaugh** [comment]
Searching online this is getting close but not integrated into remotes:
https://stackoverflow.com/questions/49698348/how-to-find-out-which-package-was-installed-from-github-in-my-r-library

**Comment by cderv** [comment]
I think you could be interested in `sessioninfo` package. 
If you installed packages with remotes, it will know if it is from CRAN, github or other
See https://github.com/r-lib/sessioninfo#usage

There is a `sessioninfo::package_info` function that will return a data.frame you can filter to get only github package. See `?sessioninfo::package_info`

**Comment by mjsteinbaugh** [comment]
Thanks @cderv. I added `installedPackages()` to my bb8 package also, which returns a data frame with a "source" column:
https://github.com/acidgenomics/bb8/blob/master/R/installedPackages.R
