### ISSUE TITLE
install_github() does not upgrade dependency

### ISSUE THREAD

**Issue by copernican** [r-lib/remotes#451]
`install_github()` does not appear to upgrade an installed package to respect a version specified in `DESCRIPTION`. I've created a minimal package [here](https://github.com/copernican/remotestest) to demonstrate the issue. If I first install `mgcv` 1.8-30, then `install_github()` works fine. But if I downgrade `mgcv` and run `install_github()` again, it fails. Could the versioning scheme used by this particular package be the issue? The error message suggests that `1.8.30` should be installed, when the [actual version](https://cran.r-project.org/package=mgcv) is `1.8-30`.

```r
>   utils::packageVersion("mgcv")
[1] ‘1.8.28’
>   remotes::install_github("copernican/remotestest", upgrade = "always")
Downloading GitHub repo copernican/remotestest@master
✔  checking for file ‘/tmp/RtmpdObqxG/remotes13be6751e7993/copernican-remotestest-063b082/DESCRIPTION’ ...
─  preparing ‘remotestest’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  creating default NAMESPACE file
─  building ‘remotestest_0.0.0.9000.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   
Installing package into ‘/mnt/home/sean_wilson/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package ‘remotestest’ ...
** using staged installation
** help
No man pages found in package  ‘remotestest’ 
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘remotestest’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘mgcv’ 1.8-28 is being loaded, but >= 1.8.30 is required
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/mnt/home/sean_wilson/R/x86_64-pc-linux-gnu-library/3.6/remotestest’
Error: Failed to install 'remotestest' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpdObqxG/file13be662030ce5/remotestest_0.0.0.9000.tar.gz’ had non-zero exit status
```

**Comment by jimhester** [comment]
I think most likely this is because `mgcv` is a recommended package, and we remove recommended packages from the dependencies to upgrade at https://github.com/r-lib/remotes/blob/b9b9aa043f30e090a471560c16707855c2a10bce/R/deps.R#L65

**Comment by copernican** [comment]
Ah, so this issue would likely affect other recommended packages. Is there a workaround you might suggest? Perhaps `package_deps()` gains an `ignore = c("base", "recommended")` argument?

**Comment by jimhester** [comment]
I don't think this is common enough to handle in remotes actually.

**Comment by statnmap** [comment]
I am also wondering why {remotes} does not stop installation as soon as minimum version number is not respected.

I face a similar problem with {gradethis}. Although a minimal version is required for dependency {learnr} in DESCRIPTION file, {remotes} does not encourage me to upgrade {learnr} and try to install as usual.  
Then I get the below error, where this issue (https://github.com/rstudio-education/gradethis/issues/147) says to upgrade {learnr}. Which works actually.  
```
Erreur : Failed to install 'gradethis' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> ** inst
E> ** byte-compile and prepare package for lazy loading
E> ** help
E> Error :  .onLoad failed in loadNamespace() for 'gradethis', details:
E>   call: (function (exercise.cap = "Code", exercise.eval = FALSE, exercise.timelimit = 30, 
E>   error: argument inutilisé (exercise.error.check.code = "gradethis_error_checker()")
E> ERROR: installing Rd objects failed for package ‘gradethis’
```
