### ISSUE TITLE
install_git Memory bloat issue. 

### ISSUE THREAD

**Issue by alittlesliceoftom** [r-lib/remotes#452]
On a Windows 10 machine, with git installed in C:\Program Files\Git\bin, running the command
`remotes::install_git(
  "repo url",
  git = "external"
)`

Creates an unescaped loop of creating "git for windows" processes. This continues until the computer runs out of Ram (24GB machine) and has to be closed. There were over 1000 processes. 

Same command works on colleagues machines.

**Comment by alittlesliceoftom** [comment]
I do have cmder console emulator installed, which I wonder if it is affecting things?

**Comment by jimhester** [comment]
Sorry, I don't know and have no way to reproduce this. If you can provide reproducible details I can re-open it.
