### ISSUE TITLE
Correct formatting of "Remotes" in DESCRIPTION

### ISSUE THREAD

**Issue by kapsner** [r-lib/remotes#453]
I wonder how to correctly specify a remote dependency in my DESCRIPTION file, where the package is on a self-hosted gitlab and a specific branch is required.

Situation:

- self-hosted gitlab: https://myserver.gitlab.com/group/project
- desired version of "project" is in branch "development"

I found out, that the following is installing the master branch:
```r
Remotes:
    git::https://myserver.gitlab.com/group/project.git
```

However, these are not working:

```r
Remotes:
    git::https://myserver.gitlab.com/group/project.git@development,
    git::development@https://myserver.gitlab.com/group/project.git,
    git::https://myserver.gitlab.com/group/project@development
```

I have tried several combinations of the possibilites found in the following URLs but I was not able to solve the problem myself.

- https://cran.r-project.org/web/packages/devtools/vignettes/dependencies.html

- https://remotes.r-lib.org/articles/dependencies.html

My current workaround is to always merge the desired dependency package version to the default "master" branch.

**Comment by jimhester** [comment]
It is not currently possible, the git remote does not try to parse the branch like the GitHub remote.

**Comment by kapsner** [comment]
Thank you for your quick reply.

Would it be possible to add this as a feature request?

**Comment by cderv** [comment]
I wonder if, as a workaround, the url Remotes cannot be used. Should be something like this with your example
```
Remotes: url::https://gitlab.com/group/project/-/archive/development/project-development.zip
```
Did you already try ? I am thinking it should work... 🤔

**Comment by kapsner** [comment]
@cderv thanks for your reply. No, I didn't try your suggested approach.

To be honest, I didn't try it yet

**Comment by kapsner** [comment]
@cderv thanks for your reply. No, I didn't try your suggested approach.

To be honest, I am not yet familiar with creating those zip-files from my repository. Is this done somehow automatically when referring to a specificly formatted URL or would I have to do this for every commit on the branch manually?

**Comment by kapsner** [comment]
The approach suggested by @cderv is working!

I can confirm, that it works with complete branches as well as with certain tags in gitlab.
