### ISSUE TITLE
Error with space in Windows path with `install_github()`

### ISSUE THREAD

**Issue by statnmap** [r-lib/remotes#455]
We tried to install a package using `remotes::install_github()` on Windows where the username contains a space like `John Doe`. The function is not able to open the repository downloaded as a tar.gz.

As can be read in the error message below (in French), the package tar.gz is correctly downloaded and saved in `C:/Users/Yves
Bas/AppData/Local/Temp/RtmpEHVgpt/file34b84fa768ea/tic_0.2.13.9021.tar.gz`, however, when trying to install from this archive, R says ` 'C:\Users\Yves' : No such file or directory`, which let's suppose the space causes problems. 

```
**** arch - i386Erreur fatale : impossible d'ouvrir le fichier
'C:\Users\Yves' : No such file or directory*** arch - x64Erreur fatale :
impossible d'ouvrir le fichier 'C:\Users\Yves' : No such file or
directoryERROR: loading failed for 'i386', 'x64'* removing 'C:/Users/Yves
Bas/Documents/R/win-library/3.5/tic'In R CMD INSTALLError in i.p(...) :
(converted from warning) installation of package ‘C:/Users/Yves
Bas/AppData/Local/Temp/RtmpEHVgpt/file34b84fa768ea/tic_0.2.13.9021.tar.gz’
had non-zero exit status*
```

Also, shouldn't `destdir` be used to download and unzip the tar.gz instead of a temp dir that is not changeable by the user?

`remotes::install_github("ropenscilabs/tic", lib = "C:/packages_github",
destdir = "C:/packages_temporary")`

**Comment by jimhester** [comment]
I think this is an issue with R, rather than an issue with remotes. I would ensure that your library path does not contain directories with spaces.
