### ISSUE TITLE
install_local cp error on Windows 10

### ISSUE THREAD

**Issue by julieinsan** [r-lib/remotes#456]
I'm trying to install a local package in Windows 10 and I keep getting the following error:

cp: unknown option -- )
Try '/usr/bin/cp --help' for more information.
ERROR: installing binary package failed

When I use `install.packages("xxxx.zip", repos = NULL)`, the package installs just fine, but, I need the dependencies to also install, so I'm going with `remotes::install_local("xxxx.zip")`.

I think this may be an issue with the cp.exe chosen during installation: it doesn't use the Rtools cp.exe, which would be in C:/Users/xxx/Rtools, but is instead trying to use /usr/bin/cp, which doesn't exist, I think, on my computer.  

But, in console, when I run:

```
where cp
```
I get back:

C:\Users\xxx\Rtools\bin\cp.exe

So, I don't see why it would be choosing to look for it in /usr/bin/cp...

<hr />

```
sessionInfo()
```
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] AppliedPredictiveModeling_1.1-7

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3       CORElearn_1.53.1 lattice_0.20-38  packrat_0.5.0    MASS_7.3-51.4    grid_3.6.0       plyr_1.8.4      
 [8] magrittr_1.5     ellipse_0.4.1    stringi_1.4.3    reshape2_1.4.3   remotes_2.1.0    rpart_4.1-15     tools_3.6.0     
[15] stringr_1.4.0    compiler_3.6.0   cluster_2.0.9    nnet_7.3-12

**Comment by jimhester** [comment]
I am not sure either, but I am pretty sure this is a system configuration issue rather than a bug in remotes, as many others are able to use remotes on Windows without a problem.

**Comment by RoelVerbelen** [comment]
Hi @jimhester and @julieinsan,

I'm running into a similar same issue today which you describe above. 

```r
> remotes::install_local("xxxx.zip", type = "binary")
Installing package into ‘C:/Users/Roel.Verbelen/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
Successfully loaded Rprofile
* installing *binary* package 'xxxx' ...
cp: unknown option -- )
Try '/Rtools/bin/cp --help' for more information.
ERROR: installing binary package failed
* removing 'C:/Users/Roel.Verbelen/Documents/R/win-library/3.6/xxxx'
* restoring previous 'C:/Users/Roel.Verbelen/Documents/R/win-library/3.6/xxxx'
```

In the RStudio command prompt terminal I get back:

```
>where cp
C:\Rtools\bin\cp.exe
```

Would you have any advice?

RStudio Edition : Desktop 
RStudio Version : 1.3.1073
OS Version      :  Windows 10 x64 (build 18362)
Platform          : x86_64-w64-mingw32/x64 (64-bit)
R Version       :  3.6.3
remotes Version: 2.2.0

**Comment by RoelVerbelen** [comment]
I have asked my colleagues to run the same command and tried myself on a different Windows computer and then the error changes to:

```r
> remotes::install_local("xxxx.zip", type = "binary")
Installing package into 'C:/Users/firstname.lastname/Documents/R/win-library/3.6'
(as 'lib' is unspecified)
* installing *binary* package 'xxxx' ...
Error in system(paste("cp -R .", shQuote(instdir), "|| (", TAR, "cd - .| (cd",  : 
  (converted from warning) 'cp' not found
* removing 'C:/Users/firstname.lastname/Documents/R/win-library/3.6/xxxx'
Error: Failed to install 'xxxx' from local:
  (converted from warning) installation of package 'C:/Users/FIRSTNAME~1.ZHA/AppData/Local/Temp/RtmpOuVeFW/remotes3acc698220ca/xxxx' had non-zero exit status
```

or 

```
Error in system(paste("mv -f", shQuote(instdir), shQuote(file.path(lockdir,  : 
  (converted from warning) 'mv' not found
```

**Comment by julieinsan** [comment]
Hi @RoelVerbelen, 
I don't recall whether I found a solution to this, but, along the way, I think I convinced myself that it was a configuration problem and following the Rtools readme, added the following 2 variables to my .Renviron file using the usethis package to find it:

```r
library(usethis)
edit_r_environ()
```

Here are the two variables that I made there:

BINPREF=C:/Users/julie/Documents/Rtools/mingw_$(WIN)/bin/
BINPREF64=C:/Users/julie/Documents/Rtools/mingw_64/bin/

Maybe try that and see if you have any luck!

**Comment by RoelVerbelen** [comment]
Hi @julieinsan,

Thank you for your response and sharing the fix which worked for you!

I tried what you described, with file paths relative to where Rtools is installed on my (and my colleagues') computer:

```
BINPREF = C:/Rtools/mingw_$(WIN)/bin/
BINPREF64 = C:/Rtools/mingw_64/bin/
```

The issue persists however. I also noticed BINPREF is set up correctly in this way in the `C:\Program Files\R\R-3.6.3\etc\x64\Makeconf`:

```
BINPREF ?= c:/Rtools/mingw_64/bin/
```

The Makeconf file in my home directory is blank `C:\Users\Roel.Verbelen\Documents\.R\Makevars`.

I've reinstalled R 3.6.3, RStudio 1.3.1073, Rtools 3.5 to no avail as well.

On my laptop I get:

```r
> devtools::find_rtools(debug = TRUE)
Scanning R CMD config CC...
cc_path: c:/Rtools/mingw_64/bin/gcc 
install_path: c:/Rtools 
Found compatible gcc from R CMD config CC
[1] TRUE
```

My colleagues get:

```r
> devtools::find_rtools(debug = TRUE)
Scanning R CMD config CC...
cc_path:  
'' does not exist
Scanning path...
Scanning registry...
Found C:/Rtools for 3.5 
VERSION.txt
Rtools version 3.5.0.4 
[1] TRUE
```

**Comment by renkun-ken** [comment]
The following code never works on Windows:

```r
url <- "https://github.com/ManuelHentschel/VSCode-R-Debugger/releases/download/v0.4.2/vscDebugger_0.4.2.zip"
remotes::install_url(url, dependencies = TRUE)
```

which produces the following error:

```
Installing package into 'C:/Users/renku/Documents/R/win-library/3.6'
(as 'lib' is unspecified)
* installing *binary* package 'vscDebugger' ...
cp: unknown option -- )
Try '/Rtools/bin/cp --help' for more information.
ERROR: installing binary package failed
* removing 'C:/Users/renku/Documents/R/win-library/3.6/vscDebugger'
Error: Failed to install 'vscDebugger' from local:
  (converted from warning) installation of package 'C:/Users/renku/AppData/Local/Temp/RtmpyUOq4R/remotes183c35025c6/vscDebugger' had non-zero exit status
```

Download the file to local and both `install.packages()` and `R CMD INSTALL` work perfectly.

I believe there's something wrong on the `remotes` side.

**Comment by jimhester** [comment]
@renkun-ken `install_url()` and all remotes functions are for installing source packages, that link is to a binary package. Just use `install.packages()` directly.
