### ISSUE TITLE
Support declaring extra dependencies

### ISSUE THREAD

**Issue by jeroen** [r-lib/remotes#459]
As discussed on slack, we want to formalize declaring several types of development dependencies in the description file. These are packages that are _not_ needed to pass check, but used  for development. E.g:

 - pkgdown: packages used by pkgdown articles
 - document: packages such as roxygen2 needed to generate manuals

By declaring these, we can automate rendering docs without having to do custom stuff in the travis file, or making these packages a requirement for running CMD check (as Suggests does).

The proposal is to prefix the fields with `Config/Depends/` such that they do not trigger a NOTE.

```txt
Imports: foo, bar
Suggest: baz
Config/Depends/pkgdown: tidyverse, bench
Config/Depends/coverage: covr
Config/Depends/document: roxygen2
```

Fields may contain remotes syntax like `cran::dplyr@0.8.2, r-lib/roxygen@branch`.

We generalize the `dependencies` parameter from the `remotes::install_...()` functions to support these custom dependencies such as `"pkgdown"`.

One open question is the dependency relationship between the dependency types :) For example:

```r
remotes::install_github("dplyr", dependencies = "pkgdown")
```

This should probably dependencies in `Config/Depends/pkgdown` plus hard dependencies (Depends, Imports, LinkingTo), but not maybe Suggests (which are mostly required to run tests)?

**Comment by gaborcsardi** [comment]
I think `"pkgdown"` should only install `Config/Depends/pkgdown`, to be able to express everything. In general, if it is a character vector, then it should only install the specified stuff.

So for your site you would typically do `c("hard", "soft", "pkgdown")`.

We can also have `"all"`, to install absolutely everything (non-recursively of course), and `TRUE` would mean `c("hard", "soft")`, like it already does.

**Comment by maelle** [comment]
I was wondering why `usethis::use_coverage()` added covr to Suggests (even if covr is only needed on Travis), and I suppose the proposal by Jeroen would mean that could be avoided?

**Comment by hadley** [comment]
I wonder if `Config/Needs/...` would be slightly better than `Config/Depends/...` since it avoids the existing meaning of the "Depends" field.

**Comment by jimhester** [comment]
Closed by https://github.com/r-lib/remotes/pull/483
