### ISSUE TITLE
Support for setting `INSTALL_OPTS` globally

### ISSUE THREAD

**Issue by pat-s** [r-lib/remotes#467]
To be used in all `install_*()` functions.

Useful on Windows when installing from source and always requiring `--no-multiarch`.

It seems there [was such an option once in {devtools}](https://stackoverflow.com/questions/41186353/install-github-with-no-multiarch-argument) but it didn't make it into {remotes}?

**Comment by jimhester** [comment]
We have decided global options like this are generally not a good idea, if you want something like this a solution would be a wrapper function that sets `INSTALL_opts` and passes the rest of the args to the install functions.

**Comment by pat-s** [comment]
Thanks Jim.
