### ISSUE TITLE
Github sub-directory: download only sub-directory?

### ISSUE THREAD

**Issue by MatthieuStigler** [r-lib/remotes#468]
I am trying to install a package within a sub-subdirectory: `https://github.com/LaboratoirePierreLegendre/numericalecology/tree/master/fonctions_R/constr.hclust`

The problem is that the package itself is light, but the github project is very heavy (600 MB!), Doing: 

    remotes::install_github("LaboratoirePierreLegendre/numericalecology/fonctions_R/constr.hclust")

`install_github` tries to download first the full repo: _Downloading GitHub repo LaboratoirePierreLegendre/numericalecology@master_ which will take easily 5-10 minutes. 

It seems it would be much more efficient to be able to download only the subdirectory? Is this possible currently?

Thanks!!

PS: I tried also using `install_url` and there is a problem with the name `.hclust`: `    remotes::install_url("https://github.com/LaboratoirePierreLegendre/numericalecology/tree/master/fonctions_R/constr.hclust")`  gives: _Error: Failed to install 'unknown package' from URL:   Don't know how to decompress files with extension hclust_ Should I open another issue for that?

**Comment by jimhester** [comment]
No, this is not possible, GitHub only provides the full repository as a download.
