### ISSUE TITLE
Installing from GitLab with nested subgroups

### ISSUE THREAD

**Issue by tomshafer** [r-lib/remotes#470]
Hi, and thanks for the great package! 

My organization has a GitLab account, and we tend to organize our repositories in a deeper-than-one-level hierarchy. For example, we might have `Org/CollectionA/CollectionB/R/repository`. What is the best way to collect a repository under this scheme?

As a public example, I've created a repo at https://gitlab.com/ts-test-group/sub1/sub2/testpkg. Attempting to install with `install_gitlab()` produces the following invalid url: 

    https://gitlab.com/api/v4/projects/ts-test-group%2Fsub1/repository/files/sub2%2Ftestpkg%2FDESCRIPTION/raw?ref=master

It seems that the correct URL should be (verified with curl):

    https://gitlab.com/api/v4/projects/ts-test-group%2Fsub1%2Fsub2%2Ftestpkg/repository/files/DESCRIPTION/raw?ref=master

Many thanks!

**Comment by cderv** [comment]
Hi ! Did you try with last remote development version installed from Github ? 
This is should be a new feature as detailed in [NEWS](https://github.com/r-lib/remotes/blob/master/NEWS.md#remotes-development-version) and implemented in https://github.com/r-lib/remotes/pull/424

This subgroups question relates to #259

**Comment by tomshafer** [comment]
Unfortunately, no. Running `remotes::install_gitlab("ts-test-group/sub1/sub2/testpkg")` produces the following URL, with the subgroup and repo in the wrong place:

    https://gitlab.com/api/v4/projects/ts-test-group%2Fsub1/repository/files/sub2%2Ftestpkg%2FDESCRIPTION/raw?ref=master

**Comment by cderv** [comment]
It works for me with last dev version of remotes. See the reprex below
``` r
sessioninfo::package_info("remotes")
#>  package * version    date       lib source                        
#>  remotes   2.1.0.9000 2020-02-05 [1] Github (r-lib/remotes@8d8d545)
#> 
#> [1] C:/Users/chris/Documents/R/win-library/3.6
#> [2] C:/Program Files/R/R-3.6.1/library
withr::with_temp_libpaths(
  remotes::install_gitlab("ts-test-group/sub1/sub2/testpkg")
)
#> Downloading GitLab repo ts-test-group/sub1/sub2/testpkg@master
#> from URL https://gitlab.com/api/v4/projects/16677400/repository/archive.tar.gz?sha=master
#>          checking for file 'C:\Users\chris\AppData\Local\Temp\RtmpsptU4r\remotes4cb020a91462\testpkg-master-0075c8774569d97a011b381ab6c90ca4c2ed236b/DESCRIPTION' ...  v  checking for file 'C:\Users\chris\AppData\Local\Temp\RtmpsptU4r\remotes4cb020a91462\testpkg-master-0075c8774569d97a011b381ab6c90ca4c2ed236b/DESCRIPTION' (372ms)
#>       -  preparing 'testpkg':
#>    checking DESCRIPTION meta-information ...     checking DESCRIPTION meta-information ...   v  checking DESCRIPTION meta-information
#>       -  checking for LF line-endings in source and make files and shell scripts
#>   -  checking for empty or unneeded directories
#>       -  building 'testpkg_0.0.0.9000.tar.gz'
#>      
#> 
#> Installing package into 'C:/Users/chris/AppData/Local/Temp/RtmpsptU4r/temp_libpath4cb059fa427e'
#> (as 'lib' is unspecified)
```

<sup>Created on 2020-02-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

And thanks a lot for the real testpkg on gitlab in nested subgroups !!

**Comment by tomshafer** [comment]
I have no idea why that didn't work for me before—I assume user error. I can reproduce your reprex now, though, which works just as well for my 'real' repo. Many thanks for the help!
