### ISSUE TITLE
install_github() function doesn't use `lock=F` argument

### ISSUE THREAD

**Issue by MyKo101** [r-lib/remotes#479]
I don't have complete admin rights on my system and so whenever I install a package using `install.packages()`, I have to use the argument `lock=F` to prevent R from creating the 00LOCK folder (changing the library directory also solves this problem, but needs to be done at every load, again due to admin rights issues)

Anyway, I tried to use this argument with the `install_github()` function and, after hitting an error had the following Warning Message:
"1 components of `...` were not used.
We detected these problematic arguments:
* `lock`
Did you misspecify an argument?`"

What would be the correct way to specify this in `install_github()`?

**Comment by jimhester** [comment]
Maybe just set the option, e.g. `getOption("install.lock", TRUE)`
