### ISSUE TITLE
update_package() gives 404 when package is not available anymore

### ISSUE THREAD

**Issue by moodymudskipper** [r-lib/remotes#480]
I don't think there's an easy option to ignore those and move on to other packages, and the message could probably be improved to suggest that the github package might have been deleted or set to private.

```
remotes::update_packages(update = "always")
Error: HTTP error 404.
  Not Found

  Did you spell the repo owner (`OWNER`) and repo name (`PKG`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
```

**Comment by jimhester** [comment]
It could be, but I think the current message is relatively clear.
