### ISSUE TITLE
How to include a local repository that contains spaces in the Remotes field of an R package DESCRIPTION?

### ISSUE THREAD

**Issue by efcaguab** [r-lib/remotes#482]
One of the dependencies for an R package I'm developing is in a local directory. Using devtools/remotes I can specify this dependency by including `Remotes: local::/path/to/the_repository` in the package DESCRIPTION. 

However, the path I need to access contains spaces and I cannot figure out how to specify it correctly. 

So far I've tried quoting (`local::"~/path/to/the repository"`) and escaping (`local::~/path/to/the\ repository`) but I still get 

```
Error: Missing commas separating Remotes
``` 

Any suggestion?

**Comment by jimhester** [comment]
It probably isn't currently possible. I would suggest you create a symlink to the directory in question that does not contain spaces.

**Comment by h-k-kan** [comment]
Using the non-8dot3 notation worked for me.
The non-8dot3 notation of a directory name can be found using dir/x in the command prompt.
