### ISSUE TITLE
Have some way for unavailable GitHub remote not to block installation

### ISSUE THREAD

**Issue by jayqi** [r-lib/remotes#484]
I have a local package A that depends on a remote package B that is in a private GitHub repository. 

I would like to be able to specify the remotes section in package A's DESCRIPTION to point at the private repo, such that if a user has their `GITHUB_PAT` set up correctly, they would be able to install/upgrade package B without needing to clone the private repo and installing it locally. 

However, when I do so, for users that don't have their `GITHUB_PAT` set up, installation is blocked for `devtools::install` and `remotes::install_local` with error:

```
Error: Failed to install '<<package A>>' from local:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`<<repoowner>>`) and repo name (`<<privaterepo>>`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
```

This happens even when I already have a package B installed locally. It seems like the inability to check for updated versions blocks installation, unless I set `upgrade = "never"`.

It would be really useful to have the option for the installation to just ignore package B, if there is already a copy of package B installed. 

The behavior I would like to be able to have is the same as if I get if I do not have the `Remotes` section specified in package A's DESCRIPTION; when checking for updated versions, the installation will say 

```
Skipping 1 packages not available: <<package B>>
```

and continue. 

The reason this would be useful is so that users aren't forced to figure out how to set up `GITHUB_PAT` if they already have local repositories cloned and installed, in order to use `devtools::install` with default settings.

**Comment by jimhester** [comment]
There isn't really any way for us to support this, I would suggest you just don't use the `Remotes:` field for this package and provide extra instructions to install the private dependency separately.
