### ISSUE TITLE
update_packages() intermittently fails with cryptic error when GitHub servers have problems

### ISSUE THREAD

**Issue by jonathan-g** [r-lib/remotes#494]
I can't create a reprex because this depends on how GitHub responds to requests, but this morning, I was getting a lot of [unicorns](https://github.com/503.html) on GitHub in my browser and at the same time `update_packages()` (run interactively from the RStudio console) was intermittently throwing errors 
```
Error: JSON: EXPECTED value GOT <
```
It took me a while to figure out what might be doing this, and I am still not certain, but my suspicion is that when `update_packages()` queries GitHub and then gets an error code (e.g., 503) with an HTML payload instead of the expected 200 code and a JSON payload, the JSON parser fails.

Maybe this could be addressed by inspecting the return code and throwing a more user-friendly error message if the https request returns an error code.

**Comment by jimhester** [comment]
Yes, that is what is happening it is a known issue. as such I am going to close this particular issue.
