### ISSUE TITLE
install_github() etc should offer to install a newer version from CRAN if available

### ISSUE THREAD

**Issue by gavinsimpson** [r-lib/remotes#498]
In doing my due diligence as maintainer of a package that uses *dplyr* I was installing the RC of that package today using `remotes::install_github`. Locally I had a version of *vctrs* < 0.3.0 (I think it was 0.2.99xxx, likely a result of troubleshooting some other change in the *tidyverse* that affected my package). When running `remotes::install_github("tidyverse/dplyr")` I was offered the following upgrade choices:

```r
> remotes::install_github("tidyverse/dplyr")
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo tidyverse/dplyr@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                          
2: CRAN packages only                           
3: None                                         
4: vctrs (67c49a1cd... -> d7d4fd378...) [GitHub]

Enter one or more numbers, or an empty line to skip updates:
```

Option **2** did nothing as I had no outdated package of relevance **except** for *vctrs*. Option **4** is not something I wanted to don't want to be troubleshooting issues reported by the *dplyr* devs while contending with any possible changes that have been merged into *vctrs* master branch post the 0.3.0 release.

Choosing option **2** had the undesirable effect of the *dplyr* installation failing as the dependencies were not met. (The first time I ran the above I did have a couple of dependencies with newer CRAN versions so I ran option 2, waited a while and then had the installation error out.)

I *know* I can do `install.packages("vctrs")` to update that package to CRAN-latest version, but

* it's not obvious that *vctrs* **is** outdated here with respect to CRAN, and
* it would be a usability boon if `install_github()` could facilitate upgrading to the CRAN-latest versions of dependencies instead of GH-latest versions if the local-version of a package is inferior to the CRAN-latest version.

So this is a *feature request*: make `install_github` and related functions aware of CRAN-latest versions of package dependencies that are newer than the locally-installed version and offer the option to install those CRAN-latest versions **or** the GH-latest version.

Desired behaviour:

* some UI to indicate to the user that the local installation of a dependency is older than the CRAN latest version,
* some option to allow all dependencies with later version on CRAN to be installed even if there is a newer version of one or more of those packages on GH
    - For example, option **2** in the above output would have installed version 0.3.0 of *vctrs*

Also, it would be nice to have the option to bail out from the above install entirely at the *ask* stage rather than proceed with an install you might know will fail.

**Comment by jimhester** [comment]
The menu states 
> It is recommended to update all of them.

If the user chooses any other choice than 1. then it is incumbent on the _user_ to be sure they understand the consequences, e.g. their versions may not be sufficient to install the requested package.

In this particular case where you already had vctrs installed from GitHub if you had updated to the latest version you would have successfully installed devel vctrs and then dplyr.

If you don't want to use a development version of a dependency that you currently have installed then you need to handle that yourself, e.g. by using `install.packages()`.

You can 'bail out' the same way you do elsewhere in R, by issuing an interrupt with `CTRL-C`.

**Comment by gavinsimpson** [comment]
@jimhester I didn't want to use the development version of *vctrs*. I was forced into installing it at some point recently (i.e. in the past few months but time is a blur just now) because I was emailed by someone involved in *dplyr* asking me to fix my package because they'd decided to change *dplyr* in a way that broke previous behaviour, and the issue they'd identified was throwing errors from *vctrs*.

With respect

> It is recommended to update all of them.

doesn't mean

> It is recommended to update all of them **to whatever latest versions I happened to find**.

Sometimes I don't understand the mentality of packages like this. On the one hand they're ostensibly portrayed as making the life easier for package developers, yet on the other behaviour is often not intuitive nor helpful, as in this case.

**Comment by gavinsimpson** [comment]
Also, this was a **feature request**. I know how to fix the problem and don't need you to patronisingly tell me what I already know. If you don't want to implement the feature or disagree with the merits of the proposal, fine. But don't give me the patronising response.
