### ISSUE TITLE
install_url: fails to install binary packages for Windows

### ISSUE THREAD

**Issue by abhinavprakash2006** [r-lib/remotes#500]
The command `install_url()` fails with the following error when installing a binary package on Windows:
![Screen Shot 2020-05-14 at 8 45 36 PM](https://user-images.githubusercontent.com/37256517/82002883-9cb02500-9624-11ea-8549-7f5460a23429.png)

It is pointing the error to Rtools. 
Rtools should not be invoked as it is a binary package.

The `install.packages()` command works for the same:
![Screen Shot 2020-05-14 at 8 46 07 PM](https://user-images.githubusercontent.com/37256517/82002907-adf93180-9624-11ea-8d0a-80614eb4fee8.png)

The command `install_url()` works well for MacOS though. I think because Mac does not rely on Rtools.
![Screen Shot 2020-05-14 at 8 47 37 PM](https://user-images.githubusercontent.com/37256517/82003031-f87aae00-9624-11ea-8b19-f5899420daa9.png)

**Comment by jimhester** [comment]
```r
remotes::install_url("https://github.com/TAMU-AML/DSWE-Packge/releases/download/v1.3.1/DSWE_1.3.1.zip", type = "binary", build = FALSE)
```

**Comment by jimhester** [comment]
Basically remotes is not designed to install binary packages, it is meant to install source packages. In particular we always set the type to explicitly "source" at https://github.com/r-lib/remotes/blob/9b5dc29102a486df2f42c88bb19027a7cd54a721/R/install.R#L40

We only support install binary dependencies, not the package itself.

This is unlikely to change in the future, so I will close this issue.
