### ISSUE TITLE
Issue with install_dev() and packagemanager.rstudio.com on Ubuntu 18.04

### ISSUE THREAD

**Issue by lcolladotor** [r-lib/remotes#501]
Hi,

I'm seeing the following error across several GitHub Actions logs such as [this one](https://github.com/lcolladotor/biocthis/runs/687455375?check_suite_focus=true#step:16:17).

```R
> remotes::install_dev("pkgdown")
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://packagemanager.rstudio.com/all/__linux__/bionic/latest/web/packages/pkgdown/DESCRIPTION'
```

This is using the Bioconductor-devel docker which is built open the Rocker Ubuntu 18.04 docker image.

Here's the R session information https://github.com/lcolladotor/biocthis/runs/687455375?check_suite_focus=true#step:9:21.

Looking at the issues and code for both `pkgdown` and `remotes` I couldn't find any code referring to `packagemanager`. I've seen this before at https://github.com/r-lib/actions/blob/master/examples/check-standard.yaml#L24 but that line of code is not used in the GHA workflow I'm using. But well, I know that `r-lib` is updating this URL recently (for example, https://github.com/r-lib/actions/commit/59e63f42f6d0c9c1d4bfedf8af266a0769893daf#diff-41184afd0528c7a9c3baae0a7a7cb58e was 18 days ago), so if you know a better place where I should report this issue please let me know.

I can potentially avoid this issue by changing from `install_dev()` to `install_github()` or `install_cran()`. [This example](https://github.com/r-lib/actions/blob/master/examples/pkgdown.yaml#L37) GHA workflow also uses `install_dev()`, so likely there were/are important reasons to do so at some point.

Best,
Leo

**Comment by jimhester** [comment]
remotes queries the `repos` option to get the CRAN url https://github.com/r-lib/remotes/blob/9b5dc29102a486df2f42c88bb19027a7cd54a721/R/install-dev.R#L26

Somewhere in your workflow you must be setting it to that url, there is nowhere in the remotes package that does so.

**Comment by lcolladotor** [comment]
Hi,

So my GHA workflow never uses that URL (it's commented out at [you can see here](https://github.com/lcolladotor/biocthis/blob/master/.github/workflows/check-bioc.yml#L309)). However, your message made me look back and I see that the rocker Ubuntu 18.04 docker file at [Dockerfile_rstudio_4.0.0-ubuntu18.04](https://github.com/rocker-org/rocker-versioned2/blob/master/dockerfiles/Dockerfile_rstudio_4.0.0-ubuntu18.04) that the Bioconductor docker is based on relies on [Dockerfile_r-ver_4.0.0](https://github.com/rocker-org/rocker-versioned2/blob/master/dockerfiles/Dockerfile_r-ver_4.0.0) which sets the `CRAN` environment variable to https://packagemanager.rstudio.com/all/__linux__/bionic/latest at [Dockerfile_r-ver_4.0.0#L13](https://github.com/rocker-org/rocker-versioned2/blob/10862c00bc4d9f07418aca576a280f00290fe928/dockerfiles/Dockerfile_r-ver_4.0.0#L13) (this update was done 6 days ago). So I'll follow up in their repo and forward them your `options(repos)` suggestion.

Thanks again for the help!

Best,
Leo
