### ISSUE TITLE
install_github() not able to update a package dependency if an older version exists

### ISSUE THREAD

**Issue by abhinavprakash2006** [r-lib/remotes#503]
I tried to install an R package from a GitHub repo using `remotes::install_github("TAMU-AML/DSWE-Package")` on **R 3.5.0**. The package depends on "**KernSmooth (>= 2.23-16)**", but **R 3.5.0** comes with a pre-installed "**KernSmooth 2.23-15**".
I expected the command `remotes::install_github("TAMU-AML/DSWE-Package)` to update "**KernSmooth**", but it did not and I got an error:
![Screen Shot 2020-05-19 at 3 03 33 PM](https://user-images.githubusercontent.com/37256517/82372696-0db75a00-99e2-11ea-9531-43d5945ada78.png)
If I remove the default installation of "**KernSmooth**" using `remove.packages("KernSmooth")`, and again try   `remotes::install_github("TAMU-AML/DSWE-Package")`, it installs the updated version of "**KernSmooth**" and the installation process for the GitHub repo goes through successfully.

**Comment by jimhester** [comment]
I think this is likely a a downstream symptom of https://github.com/r-lib/remotes/issues/395 or similar, so I will close this particular issue.
