### ISSUE TITLE
Error in parse(outFile) : unexpected end of input - bug in package install

### ISSUE THREAD

**Issue by SimonDedman** [r-lib/remotes#507]
Hi folks,

`install_packages` gives the 

> Error in parse(outFile) : unexpected end of input

warning if there's an unclosed bracket in a script, however it says that the location is at the end of the last alphabetically named script, and not at the end of the broken script itself (unless that's the last script, of course).

See [here](https://stackoverflow.com/questions/62364853/error-in-parseoutfile-unexpected-end-of-input-bug-in-package-install-and) for more details & my workaround.

I propose that the install packages warning code should use something similar i.e. parse test each script in turn rather than glueing them all together. Please let me know if this isn't the correct place to file this bug, i.e. it's RStudio or R or an underlying package installer.

Cheers

**Comment by jimhester** [comment]
Thanks for opening the issue.

This it is ultimately an R issue, but I don't think there is much to be done about it unfortunately I don't think anyone on R-core would be willing to take on making the code changes necessary to fix this particular error.

**Comment by elinw** [comment]
This is really old, but could you possibly show me where in remotes or a package relied on by remotes  there is the use of `base::parse()` that could be causing this?
