### ISSUE TITLE
`remotes::update_packages()` is now messaging about purrrogress

### ISSUE THREAD

**Issue by mjsteinbaugh** [r-lib/remotes#512]
Hi, I'm seeing this warning now when calling `remotes::update_packages()`.

```
Skipping 1 packages not available: purrrogress
```

I don't have purrrogress currently installed on my machine, and I'm not sure how to generate a proper traceback to debug this issue. Any idea where this is being called?

**Comment by mjsteinbaugh** [comment]
See related [CRAN removal](https://cran.r-project.org/web/packages/purrrogress/index.html) from 2020-06-15.

**Comment by jimhester** [comment]
remotes does not use `purrrogress`.

One of the packages you are trying to update must reference it, but I have no idea what one.

**Comment by mjsteinbaugh** [comment]
Thanks, I figured @jimhester. I'll do some digging and see if I can figure it out.

**Comment by mjsteinbaugh** [comment]
In case anybody else hits this issue, it seems to be [TCGAbiolinks](https://bioconductor.org/packages/TCGAbiolinks/).

**Comment by mjsteinbaugh** [comment]
Fixed with this [change](https://github.com/BioinformaticsFMRP/TCGAbiolinks/commit/e5708e0878e15f9b23dfab026cc484f1bb5eede9), safe to close.
