### ISSUE TITLE
How to deal with ERROR PACKAGE WAS BUILT IN VERSION x ?

### ISSUE THREAD

**Issue by RocioAliaga** [r-lib/remotes#515]
Hi, 
I am quite new in using R, I would like to know how to deal with this error message:
"package ‘tmap’ was built under R version 3.6.2"
 In fact, this is an example but it appears for any package that is not under the version of R. 
What I can do? 
Thanks in advance for your help. 
Rocio

**Comment by jimhester** [comment]
The easiest thing would be to upgrade your version of R to the latest version.

Alternatively if this warning is coming when you call `install.packages()` then it should just be a warning, not an error and you can safely ignore it.

If this warning is being converted to an error when you try to install packages with `remotes::install_github()` you can avoid that by using

```r
Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
```

Or by running `usethis::edit_r_environ()` and then placing
```
R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
```

In the `.Renviron` file, which will set this for you each time R is started up.
