### ISSUE TITLE
Idea: Make it very known to user when packages are updating to a new major version

### ISSUE THREAD

**Issue by daattali** [r-lib/remotes#524]
I can't decide if this is a good idea or not, so I'll throw it out there:

I usually update packages in a batch - every few weeks I'll upgrade a bunch of packages. It's hard to tell if any of them have any breaking changes that I must be aware of, other than looking at the NEWS section of each one.

Not all packages follow semantic versioning, but enough do, so I thought it might be nice if when I update packages, at the end when all installations are finished, my console would show a message such as:

```
IMPORTANT NOTE: The following packages were updated to a new major version, which usually indicates they introduced breaking changes that might break your existing code: <list>
```

**Comment by jimhester** [comment]
While possibly a good idea I think it is out of scope for remotes.

**Comment by daattali** [comment]
@jimhester would you re-consider? I just came to this repo to suggest this exact idea and found out that I already suggested it a year ago :)
Perhaps there can just be an asterisk besides any line wher the major version has changed.
To me that information is quite essential for installing a package

**Comment by daattali** [comment]
To clarify: the reasoning I initially gave last year is valid, but I think there's an even stronger argument to why this is useful.

I usually don't blindly update all the packages, but rather I go through the list and only update packages that I think should be updated. If I'm given this output:

![image](https://user-images.githubusercontent.com/952340/204114937-d4f2bb02-71fe-43eb-968c-910bfc1a40eb.png)

Most of them are patch updates and I don't want to be bothered by them. I would go through this list and only pick packages that have major updates. But I have no way of easily knowing that so it's very easy to miss one package that actually had a major update.

**Comment by gaborcsardi** [comment]
We are not adding new features to remotes, as we are focusing on pak instead, which already has a much better display of what is going to be installed and from where. It also lists all packages that are going to be installed, before installing them.
