### ISSUE TITLE
`install_deps` skips dependency installation when setting MRAN snapshot on `options(repos)`

### ISSUE THREAD

**Issue by tiagocabaco** [r-lib/remotes#527]
When a custom `repos` argument is set in `options` to a snapshot from MRAN, `install_deps` skips dependency installations when local package versions are above versions in the MRAN snapshot.

For example, if on my machine `dplyr` is on version 1.0.0, and a snapshot from MRAN at 2020-01-01 is set on `options(repos)`, when `dplyr` is a dependency on a package not yet in a standard package repository `install_deps` will skip the installation of dplyr version at selected MRAN snapshot, bellow 1.0.0.
  
Is this an expected behavior from the function? If so, is it possible to override?

**Comment by jimhester** [comment]
Yes this is expected, remotes will never downgrade dependencies.

If you are trying to pin package versions for a project I suggest you look into using [renv](https://rstudio.github.io/renv/index.html), possibly in conjunction with MRAN

**Comment by tiagocabaco** [comment]
Thanks for your response. Yes, the goal was to pin package versions, Will have a look into renv. Thanks for the suggestion and reply.
