### ISSUE TITLE
Can't install binary from enterprise github release assets

### ISSUE THREAD

**Issue by mkirzon** [r-lib/remotes#529]
We have github enterprise and have uploaded binaries of a package that are attached as assets under a release tag. However, I can't seem to install the binary; rather it still installs the source
```r
remotes::install_github("ourOrg/ourPackage@0.1.0", host = "git.ourOrg.com/api/v3", type = "binary", build = FALSE)
# * installing *source* package 'ourPackage' ...
# ** R
# ** preparing package for lazy loading
# ** help
# *** installing help indices
# ** building package indices
# ** testing if installed package can be loaded
# *** arch - i386
# *** arch - x64
# * DONE (ourPackage)
```

**Comment by jimhester** [comment]
remotes doesn't support this, and there are no plans to do so.

**Comment by mkirzon** [comment]
Understood, thank you. Any chance you have a recommendation for this?

**Comment by jimhester** [comment]
[RStudio package manager](https://rstudio.com/products/package-manager/) is designed for companies hosting their internal packages, and will automatically build and host binaries based on git repositories (including GitHub).
