### ISSUE TITLE
upgrade=FALSE is not passed through to dependent installations

### ISSUE THREAD

**Issue by richfitz** [r-lib/remotes#53]
Upgrading packages tends to lead to really broken sets of packages on windows due to file locking, and so I tend to set `upgrade = FALSE` quite a lot (I would *love* a `remotes.upgrade` global option that I could set to FALSE).

If a package installed by `remotes::install_github` lists a remote in its description then subsequent installations do not honour the `upgrade = FALSE` argument

**Comment by gaborcsardi** [comment]
:+1:
