### ISSUE TITLE
Install_git does not download correct submodules commits

### ISSUE THREAD

**Issue by SAbdulah** [r-lib/remotes#534]
I am using install_git to download my package from Github. The problem that I am using submodule on my repo and install_git always uses the master branch of this submodule.
I defined mu submodules to uses a specific commit, not the master.

 I tried to used args="--recursive" but the same problem is still occurring.

**Comment by jimhester** [comment]
Sorry, I doubt we will support this in the near future.

As a workaround I would suggest using [git-subtrees](https://www.atlassian.com/git/tutorials/git-subtree) rather than submodules.
