### ISSUE TITLE
feature request: respect currently installed versions when building dependency tree

### ISSUE THREAD

**Issue by kieranjmartin** [r-lib/remotes#537]
As I understand it, package_deps looks at CRAN versions of packages, and determines dependencies in that way. This can lead to unnecessary dependencies being installed.

For example, if I have ggplot 3.1.0 (and all its dependencies) and install a package using install_github which declares ggplot as a dependency, then I will find that it will also install isoband, which was not a dependency for 3.1.0, but is for later versions.

This seems like undesirable behaviour: I actually have all the packages I need to run my github package, but am being forced to install more because it's using the CRAN dependency rather than my local depency tree.

I can resolve this by using dependencies = FALSE but if I'm actually missing a depedency that I need then that won't be installed.

Ideally I would like it to search through the locally installed description files to search for these dependencies

**Comment by jimhester** [comment]
Thanks for filing this issue! Unfortunately, implementing this in remotes would require significant rewriting of the dependency resolution code. It is very unlikely to ever happen.

https://pak.r-lib.org/ is a alternative that does do what you suggest, though it is still maturing.

Even though we're closing this issue, we really appreciate the feedback, and hope you'll continue to contribute in the future :smile:
