### ISSUE TITLE
argument "av2" is missing, with no default

### ISSUE THREAD

**Issue by jeroen** [r-lib/remotes#539]
See: https://ci.appveyor.com/project/jeroen/sys/builds/35128362

**Comment by jimhester** [comment]
This is not coming from remotes, it seems to be something recently added to R patched (https://github.com/wch/r-source/commit/d4f09f4ae0671d604a0df698e9ff94b247e2d3a2)

**Comment by jeroen** [comment]
OK, you're right, sorry for the inaccurate diagnosis. I reported it to r-core.
