### ISSUE TITLE
install_github "Missing value where TRUE/FALSE needed" error

### ISSUE THREAD

**Issue by Jacob-ctrl** [r-lib/remotes#543]
Hi! 

I've recently tried to install the [sdam-r package ](https://github.com/mspeekenbrink/sdam-r) which is available only on GitHub.

I tried to install it through the remotes package, however, I've been getting this error:

```
remotes::install_github("mspeekenbrink/sdam-r")
Downloading GitHub repo mspeekenbrink/sdam-r@HEAD
Error: Failed to install 'sdamr' from GitHub:
  missing value where TRUE/FALSE needed
```

I'm using RStudio and this version of R:

```
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          4                           
minor          0.2                         
year           2020                        
month          06                          
day            22                          
svn rev        78730                       
language       R                           
version.string R version 4.0.2 (2020-06-22)
nickname       Taking Off Again
```

All packages are up to date.

I've tried to run it through the devtools package as well but it would return the same error message.

I can install other CRAN packages, but it's the GitHub packages I cannot download.

I found a similar post about this issue (https://github.com/r-lib/remotes/issues/320) and the solutions they propose is to add

`options(download.file.extra = paste0("-L ", getOption("download.file.extra", default = ""))`

and/or

`options("download.file.method" = "libcurl")`

before the install_github command. Did that - didn't work, still returned the "**missing value where TRUE/FALSE needed**". 

Any tips or ideas as to what could be the possible solution?

I'm completely new to GitHub and R so if you need any more details/info let me know.

Thanks!
J.

**Comment by vkartha** [comment]
Did you ever figure this out? I'm having the same issue after updating to R 4.0.3, for a different package, assuming it's related. Cannot download packages using install_github, and getting the same error, also tried the two above solutions previously posted before, did not work.

**Comment by vkartha** [comment]
Updating RStudio specifically fixed this issue for me, BTW (I don't honestly know why, but thought it was worth a shot since I had updated R to the latest release 4.0.3 but had a v old version of Rstudio)

**Comment by Jacob-ctrl** [comment]
In my case, I had to create a separate working directory. The one RStudio tried to install the package to had a Polish sign in it (since I'm using a Polish system) and apparently, it caused the command to crash. Once I set the working directory to one without any Polish signs the command worked just fine and I was able to install the package.

**Comment by ALVignoles** [comment]
Hello ! I know that this issue is closed, but if anyone runs into this problem again, it could also be because of your Antivirus ; in my case it was putting one of the files in quarantine, and the package wouldn,'t install. Hope this helps !!

**Comment by Inmaaguilera** [comment]
It happens the same to me!

**Comment by Inmaaguilera** [comment]
Maybe, this is related to what ALVignoles commented regarding the antivirus.   How could I manage it ?
