### ISSUE TITLE
Add a way to query/install system dependencies of specific package

### ISSUE THREAD

**Issue by thomasp85** [r-lib/remotes#545]
The system dependency query only works for a local package, making it hard to install remotes with any system dependencies. This surfaced as a user trying to install pkgdown which now requires ragg and hence it's slew of system libraries. It would be nice if there was a way to query dependencies by name so one wouldn't have to download the source package before making the query

something like `install_github("pkgdown", system_dependencies =TRUE)` would be amazing, but allowing `remotes::system_requirements()` to take a package name instead of a directory would be very good as well

**Comment by jimhester** [comment]
`install_github("pkgdown", system_dependencies = TRUE)` is impossible without some way to elevate permissions, since you generally need `su` access to install things from the package manager.

**Comment by thomasp85** [comment]
That was maybe also a pipe dream. But it would be nice to have some canned way of installing pkgdown on Linux with all the right system requirements
