### ISSUE TITLE
install_deps() on macOS attempts to download non-existent *.tgz package file 

### ISSUE THREAD

**Issue by JoshOBrien** [r-lib/remotes#547]
I just used `usethis::use_github_action_check_standard()` to add `R CMD check` as GitHub action to my [**rasterDT**](https://github.com/JoshOBrien/rasterDT) package repo. At the moment, a new version of *data.table* (one of my  package's dependencies) has been recently accepted by CRAN. As a result, the source bundle for the new version is available, but neither the Windows or the macOS binaries are available.

In the Windows `R CMD check` triggered by the GitHub action, the source package was successfully downloaded and built, using Rtools.

On macOS, [as reported here](https://github.com/JoshOBrien/rasterDT/runs/1288076859?check_suite_focus=true#step:8:138), the GitHub action fails in the "Install dependencies" step, when `install_deps()` attempts to download the currently non-existent `data.table_1.13.2.tgz`. Here, with a little bit of preceding context, is the relevant bit of the error report:

```bash
trying URL 'https://cloud.r-project.org/bin/macosx/contrib/4.0/fasterize_1.0.3.tgz'
Content type 'application/x-gzip' length 1073041 bytes (1.0 MB)
==================================================
downloaded 1.0 MB

trying URL 'https://cloud.r-project.org/bin/macosx/contrib/4.0/data.table_1.13.2.tgz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cloud.r-project.org/bin/macosx/contrib/4.0/data.table_1.13.2.tgz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'https://cloud.r-project.org/bin/macosx/contrib/4.0/data.table_1.13.2.tgz': HTTP status was '404 Not Found'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘data.table’ failed
``` 

I'm not familiar with compiling R packages on macOS, so don't know whether it would be possible to add a fallback in which a package for which no binary is currently available is compiled from source...

**Comment by jimhester** [comment]
This was due to a temporary issue with the CRAN mirror syncing. I don't think there is anything we can do about it in remotes.
