### ISSUE TITLE
Look for both master and main branches in install_github()

### ISSUE THREAD

**Issue by rjake** [r-lib/remotes#550]
With the [new defualt](https://github.com/github/renaming) of using a `main` branch, I'm curious if `install_github()` could look for the `master` branch and then for the `main` branch, or vice versa to avoid throwing an error.

```r
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/rjake/headliner/tarball/master'
```

**Comment by jimhester** [comment]
Are you using the latest version of remotes? It uses `HEAD`, which should always use the head branch of the repository.

**Comment by jimhester** [comment]
e.g. `remotes::install_github("rjake/headliner")` works without issue when using the current CRAN release (2.2.0)

**Comment by rjake** [comment]
Oops, should've checked. Thanks!
