### ISSUE TITLE
Re-licensing remotes

### ISSUE THREAD

**Issue by hadley** [r-lib/remotes#551]
We are systematically re-licensing tidyverse and r-lib packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all all non-RStudio [contributors](https://github.com/r-lib/remotes/graphs/contributors). @ankane, @antoine-sachet, @aornugent, @Bisaloo, @danhalligan, @davidchall, @dmurdoch, @dpprdan, @flying-sheep, @HenrikBengtsson, @infotroph, @jan-glx, @jefferis, @joshuaulrich, @jsilve24, @kenahoo, @LiNk-NY, @MichaelChirico, @mkearney, @muschellij2, @MyKo101, @Neil-Schneider, @overmar, @pommedeterresautee, @QuLogic, @rcannood, @robertdj, @timtrice, @tmelliott, @tylermorganwall, @yutannihilation, would you permit us to re-license remotes with the MIT license? If so, please comment "I agree" below.

* [x] [@ankane](https://github.com/r-lib/remotes/commits?author=ankane)  
* [x] [@antoine-sachet](https://github.com/r-lib/remotes/commits?author=antoine-sachet)  
* [x] [@aornugent](https://github.com/r-lib/remotes/commits?author=aornugent)  
* [x] [@Bisaloo](https://github.com/r-lib/remotes/commits?author=Bisaloo)  
* [x] [@danhalligan](https://github.com/r-lib/remotes/commits?author=danhalligan)  
* [x] [@davidchall](https://github.com/r-lib/remotes/commits?author=davidchall)  
* [x] [@dmurdoch](https://github.com/r-lib/remotes/commits?author=dmurdoch)  
* [x] [@dpprdan](https://github.com/r-lib/remotes/commits?author=dpprdan)  
* [x] [@flying-sheep](https://github.com/r-lib/remotes/commits?author=flying-sheep)  
* [x] [@HenrikBengtsson](https://github.com/r-lib/remotes/commits?author=HenrikBengtsson)  
* [x] [@infotroph](https://github.com/r-lib/remotes/commits?author=infotroph)  
* [x] [@jan-glx](https://github.com/r-lib/remotes/commits?author=jan-glx)  
* [x] [@jefferis](https://github.com/r-lib/remotes/commits?author=jefferis)  
* [x] [@joshuaulrich](https://github.com/r-lib/remotes/commits?author=joshuaulrich)  
* [x] [@jsilve24](https://github.com/r-lib/remotes/commits?author=jsilve24)  
* [x] [@kenahoo](https://github.com/r-lib/remotes/commits?author=kenahoo)  
* [x] [@LiNk-NY](https://github.com/r-lib/remotes/commits?author=LiNk-NY)  
* [x] [@MichaelChirico](https://github.com/r-lib/remotes/commits?author=MichaelChirico)  
* [x] [@mkearney](https://github.com/r-lib/remotes/commits?author=mkearney)  
* [x] [@muschellij2](https://github.com/r-lib/remotes/commits?author=muschellij2)  
* [x] [@MyKo101](https://github.com/r-lib/remotes/commits?author=MyKo101)  
* [x] [@Neil-Schneider](https://github.com/r-lib/remotes/commits?author=Neil-Schneider)  
* [x] [@overmar](https://github.com/r-lib/remotes/commits?author=overmar)  
* [x] [@pommedeterresautee](https://github.com/r-lib/remotes/commits?author=pommedeterresautee)  
* [x] [@QuLogic](https://github.com/r-lib/remotes/commits?author=QuLogic)  
* [x] [@rcannood](https://github.com/r-lib/remotes/commits?author=rcannood)  
* [x] [@robertdj](https://github.com/r-lib/remotes/commits?author=robertdj)  
* [x] [@timtrice](https://github.com/r-lib/remotes/commits?author=timtrice)  
* [x] [@tmelliott](https://github.com/r-lib/remotes/commits?author=tmelliott)  
* [x] [@tylermorganwall](https://github.com/r-lib/remotes/commits?author=tylermorganwall)  
* [x] [@yutannihilation](https://github.com/r-lib/remotes/commits?author=yutannihilation)

**Comment by fiosgenomics** [comment]
I agree

**Comment by danhalligan** [comment]
I agree

**Comment by rcannood** [comment]
"I agree" below

**Comment by joshuaulrich** [comment]
I agree. Muting to avoid multiple notifications. Please reach out directly if you need me to comment further.

**Comment by jsilve24** [comment]
I agree.

**Comment by jefferis** [comment]
I agree

**Comment by dpprdan** [comment]
I agree.

If others are interested in the motivation for the re-licensing, see the corresponding issue in the ggplot2 repo https://github.com/tidyverse/ggplot2/issues/4236

**Comment by MichaelChirico** [comment]
agree

**Comment by dmurdoch** [comment]
Is there an easy way to see what my contribution(s) was/were?

**Comment by antoine-sachet** [comment]
I agree!

**Comment by Bisaloo** [comment]
> Is there an easy way to see what my contribution(s) was/were?

https://github.com/r-lib/remotes/commits?author=dmurdoch

**Comment by Bisaloo** [comment]
I agree

**Comment by batpigandme** [comment]
Yep, in addition to adding your name as author (like @Bisaloo pointed out), the checklist items are actually links to your commits.

**Comment by dmurdoch** [comment]
I agree

**Comment by timtrice** [comment]
I agree

**Comment by Neil-Schneider** [comment]
I agree

**Comment by muschellij2** [comment]
I agree

**Comment by pommedeterresautee** [comment]
I agree

**Comment by tmelliott** [comment]
I agree.

**Comment by ankane** [comment]
I agree

**Comment by LiNk-NY** [comment]
I agree

**Comment by aornugent** [comment]
I agree.

**Comment by flying-sheep** [comment]
I agree

**Comment by jan-glx** [comment]
I agree

**Comment by QuLogic** [comment]
I agree, but I didn't actually add any code.

**Comment by davidchall** [comment]
I agree

**Comment by yutannihilation** [comment]
I agree

**Comment by MyKo101** [comment]
I agree

**Comment by robertdj** [comment]
I agree

**Comment by batpigandme** [comment]
Hi, @HenrikBengtsson, @mkearney, @overmar, and @tylermorganwall,
We'd love to get your agreement please, if you could take a look when you have a chance. 🙂
Thanks!

**Comment by tylermorganwall** [comment]
I agree!

**Comment by HenrikBengtsson** [comment]
I agree

**Comment by mkearney** [comment]
I agree

**Comment by hadley** [comment]
@overmar agreed over email.
