### ISSUE TITLE
`system_requirements()` misses C++11 

### ISSUE THREAD

**Issue by dmurdoch** [r-lib/remotes#558]
The `RcppArmadillo` package currently requires C++11.  This should be available by default in R 4+, but in earlier R versions it needs to be requested.  Rather than using `SystemRequirements` in `DESCRIPTION` to do it, `RcppArmadillo` puts `CXX_STD = CXX11` in `src/Makevars.in`, which I think is the recommended way.

However, `system_requirements()` misses the requirement, so (as discussed in this thread:  https://stat.ethz.ch/pipermail/r-package-devel/2020q4/006327.html) Github Action builds of packages using `RcppArmadillo` in earlier versions of R fail.

Suggestion:  make the `system_requirements()` search look at `Makevars.*` as well as `DESCRIPTION`, or maybe just apply a special-case rule to `RcppArmadillo` (though there are a lot of other packages with  `CXX_STD = CXX11` in `Makevars.*`; I don't know how many others leave out `SystemRequirements` and are expected to work on R versions before R 4.)

**Comment by jimhester** [comment]
Using `SystemRequirements` is the recommended way.

**Comment by dmurdoch** [comment]
According to WRE:

> "   In order to specify C++11 code in a package to be used with R
> versions from 3.1.0 but before 3.6.2, the package's 'Makevars' file (or
> 'Makevars.win' on Windows) should include the line
> 
>      CXX_STD = CXX11
> Compilation and linking will then be done with the C++11 compiler (if
> any).
> 
>    Packages without a 'src/Makevars' or 'src/Makefile' file may specify
> that they require C++11 for code in the 'src' directory by including
> 'C++11' in the 'SystemRequirements' field of the 'DESCRIPTION' file,
> e.g.
> 
>      SystemRequirements: C++11
> 
>    If a package does have a 'src/Makevars[.win]' file then setting the
> make variable 'CXX_STD' is preferred, as it allows 'R CMD SHLIB' to work
> correctly in the package's 'src' directory."

Since `RcppArmadillo` wants to be available for `R (>= 3.3.0)`, and it does have a `Makevars` file, the final paragraph applies.

I'm not saying this is a good design, just that it's the recommended way to do things, `RcppArmadillo` follows it, and this causes problems for other packages that depend on `system_requirements()`.

**Comment by dmurdoch** [comment]
I just did a search through CRAN packages for packages meeting these conditions:
  - has Makevars containing CXX_STD specifying CXX11 or CXX14
  - doesn't have SystemRequirements for C++
  - doesn't depend on R >= 3.6.2 or more

There are about 500 packages meeting these conditions.  Probably some of them depend on packages that put C++11 or C++14 in SystemRequirements, but not all of them do.  Here's the start of the list:

```
 [1] "acebayes"  "activegp"  "ADtools"   "agtboost"  "alpaca"   
 [6] "AlphaSimR" "AnaCoDa"   "anMC"      "anomaly"   "anytime"  
```

**Comment by jimhester** [comment]
These packages would still be better off additionally specifying it in the SystemRequirements field if they really did want to use `CXX_STD`.

The `system_requirements()` function in remotes simply queries RSPM's database of system requirements (https://github.com/rstudio/r-system-requirements) which is solely based on the `SystemRequirements:` field of packages and their dependencies. This is very unlikely to change, so these packages will not be able to take advantage of the automatic system requirement lookup unfortunately.

**Comment by dmurdoch** [comment]
Okay, I'll make the suggestion there instead.
