### ISSUE TITLE
install_github() does not install data/ on linux

### ISSUE THREAD

**Issue by wvictor14** [r-lib/remotes#560]
I have an issue installation with [my r package](github.com/wvictor14/planet). 

Installation and functionality works fine on windows and mac OS. It also installs without error on linux.

However, on linux only, none of my data objects are accessible. It seems that the `data/` folder does not get built after install.

```
devtools::install_github('wvictor14/planet@fix-install-error', force = TRUE)
Downloading GitHub repo wvictor14/planet@fix-install-error
✓  checking for file ‘/tmp/RtmpFn8vQw/remotes8a4021b19f19/wvictor14-planet-0fb319e/DESCRIPTION’ ...
─  preparing ‘planet’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘planet_0.2.2.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'
   
Installing package into ‘/home/BCRICWH.LAN/vyuan/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package ‘planet’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (planet)

> system.file(package = "planet")
[1] "/home/BCRICWH.LAN/vyuan/R/x86_64-pc-linux-gnu-library/3.6/planet"

# NO DATA FOLDER?
> dir(system.file(package = "planet"))
[1] "DESCRIPTION" "help"        "html"        "INDEX"       "LICENSE"     "Meta"        "NAMESPACE"  
[8] "NEWS.md"     "R"          
```

This is on Ubuntu 18.0.4, R version 3.6.3. Using this version of remotes and devtools:

```
> packageVersion('devtools')
[1] ‘2.3.2’
> packageVersion('remotes')
[1] ‘2.2.0’
```

Unfortunately I can't update R version at the moment. But I have other users experiencing the same issue on R version 4.0.0+

`check()` returns no errors or warnings.  I generated the data objects using `usethis::use_data(..., internal = FALSE)`. I also have some internal data too. 

Would really appreciate any help. Thanks!

**Comment by jimhester** [comment]
linux's file system is case sensitive, your data directory is named `Data`, not `data` as expected. Windows and macOS do not have case sensitive file systems by default, which is why you don't see issues on those machines.

**Comment by wvictor14** [comment]
Wow, thank you so much!
