### ISSUE TITLE
remotes::install_local confuses package version with sha1

### ISSUE THREAD

**Issue by cboettig** [r-lib/remotes#562]
remotes::install_local() refuses to reinstall a package by default if the package version in the DESCRIPTION file has not changed.  It incorrectly reports that the SHA1 hash has not changed (and quotes the version number instead).  

Among other things, this breaks common popular CI scripts such as 
https://github.com/r-lib/actions/blob/master/examples/render-readme.yaml#L21

which rely on `install_local()` to detect things like new dependencies being added to the DESCRIPTION.  

(`install_deps()` in contrast seems to always to the expected thing here)

**Comment by jimhester** [comment]
What you suggest was how `install_local()` originally worked.

 It was changed in https://github.com/r-lib/devtools/pull/1804 upon user requests. If you change the dependencies you will also need to bump the version number.

**Comment by cboettig** [comment]
Cool, thanks for the history.  

I think needing to bump the version number in order to add dependencies is unintuitive. I suppose I would have a more robust workflow by calling `install_deps()` first in workflows like your nice GH-Actions script.  (If `install_local()` did that internally, it could still avoid the unexpected error in my case without breaking @lionel- 's use case, I believe).  

At very least it should report that it is not reinstalling because the package version has not changed, referring to the package version as the SHA1 is confusing.
