### ISSUE TITLE
Use install_version in install_deps to handle versioned dependencies

### ISSUE THREAD

**Issue by psolymos** [r-lib/remotes#563]
I was testing all kinds of `DESCRIPTION` file setups to automate dependency management for Docker images. One particular issue I noticed is that `remotes::install_deps` accepts versioned packages in `Imports:` etc, but the versions are not respected as the `remotes::install_version` is not used. I am guessing it is intentional, but the reasoning behind it is unclear to me.

My workaround includes using a `VersionedPackages:` field in `DESCRIPTION` to put versioned packages in and then use `remotes::install_version`. Is there a better way, or could `remotes::install_deps` be changed to better respect versions?

Thanks!

**Comment by jimhester** [comment]
Yes, there is a better way, use [renv](https://rstudio.github.io/renv/index.html) if you want to pin particular versions of R packages for a project.

**Comment by psolymos** [comment]
Thanks, I am aware. I was just hoping for some middle ground. I find renv to be great for shapshotting projects, most advice on using renv with Docker comes down to [explicitly using DESCRIPTION](https://rstudio.github.io/renv/articles/faq.html#capturing-explicit-dependencies), which brings me back to the default remotes behavior.

Looping in @kevinushey here: is there a more declarative way for CRAN package versions other than to ask renv to base `renv.lock` on my local machine's state and transfer that to Dockerfile through git?

Thanks!

**Comment by psolymos** [comment]
For the record: [here](https://github.com/analythium/openfaas-rstats-templates/tree/master/template#dependencies) is my current workaround that I found to work well across different R base images (Debian, Ubuntu, Alpine). I was just checking if I understood the intended `remotes::install_deps()` correctly.

The Dockerfile copies an [install script](https://github.com/analythium/openfaas-rstats-templates/blob/master/template/rstats-base-plumber/install.R) (inspired by rhub/r-minimal's approach using [installr](https://github.com/r-hub/r-minimal)) that handles certain aspects of the sysreqs and dependency installs.

**Comment by kevinushey** [comment]
> Looping in @kevinushey here: is there a more declarative way for CRAN package versions other than to ask renv to base renv.lock on my local machine's state and transfer that to Dockerfile through git?

You could manually edit the `renv.lock` lockfile to request the specific packages you want -- not sure if that's a reasonable-enough compromise.

The dependency solver in `renv` is quite primitive though, and isn't really designed to take arbitrary version requirements and translate that into a "correct" set of dependencies. I think [pak](https://github.com/r-lib/pak) may be a better fit if that's what you require.

**Comment by psolymos** [comment]
Thanks for the feedback. I'll have a look at pak!
