### ISSUE TITLE
Parsing remote with github:: prefix

### ISSUE THREAD

**Issue by jeroen** [r-lib/remotes#565]
I was expecting `github::statnet/rle@master` and `statnet/rle@master` to be interchangable, but I found that:

```r
remotes::parse_repo_spec('github::statnet/rle@master')
```

Results in:

```
$username
[1] "github::statnet"
```

Which is of course not a valid GitHub name, and hence broke things downstream.

**Comment by jimhester** [comment]
You need to use `remotes:::parse_one_extra("github::statnet/rle@master")` to parse the full remote.

**Comment by muschellij2** [comment]
Any thoughts on exporting this function for package use?  I'm adding a PR to https://github.com/o2r-project/containerit, which is trying to parse remotes and using `remotes:::parse_one_extra`, but violates CRAN policy.
