### ISSUE TITLE
Request: display information about GitHub API rate limits

### ISSUE THREAD

**Issue by wch** [r-lib/remotes#568]
We often run into issues installing packages in GitHub Actions due GitHub API rate limits. For example:
https://github.com/rstudio/shiny/runs/1590155684?check_suite_focus=true#step:6:25
https://github.com/rstudio/shiny/pull/3210/checks?check_run_id=1578374454#step:6:26

It would be very helpful if, when this error occurs, it printed out information about rate limits. Apparently that information included in the HTTP response headers. Using the example from https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#rate-limiting:

```
$ curl -i https://api.github.com/users/octocat
> HTTP/1.1 200 OK
> Date: Mon, 01 Jul 2013 17:27:06 GMT
> Status: 200 OK
> X-RateLimit-Limit: 60
> X-RateLimit-Remaining: 56
> X-RateLimit-Reset: 1372700873
```

Rate limit information is also available via the API (https://docs.github.com/en/free-pro-team@latest/rest/reference/rate-limit#get-rate-limit-status-for-the-authenticated-user):

```
$ curl \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/rate_limit

{
  "resources": {
    "core": {
      "limit": 60,
      "remaining": 59,
      "reset": 1608581909,
      "used": 1
    },
    "graphql": {
      "limit": 0,
      "remaining": 0,
      "reset": 1608582033,
      "used": 0
    },
    "integration_manifest": {
      "limit": 5000,
      "remaining": 5000,
      "reset": 1608582033,
      "used": 0
    },
    "search": {
      "limit": 10,
      "remaining": 10,
      "reset": 1608578493,
      "used": 0
    }
  },
  "rate": {
    "limit": 60,
    "remaining": 59,
    "reset": 1608581909,
    "used": 1
  }
}
```

**Comment by jimhester** [comment]
It does this already if you use curl FWIW. 

https://github.com/r-lib/remotes/blob/2590ecd14d856ebdcbc10cc407e014998185bcc5/R/github.R#L144-L223

**Comment by wch** [comment]
We've also discussed the workaround where we use `Remotes` entries like:

```
  url::https://github.com/org/pkg/archive/master.tar.gz
```

(From https://r-lib.github.io/revdepcheck/articles/cloud.html#usage)

It would be nice to be able to use entries in `Remotes` like:

```
  github_url::org/pkg
```

Or if there was some option we could set to tell Remotes to automatically translate `org/pkg` entries to use the URL, instead of going through the GitHub API. And now that I think about it a bit more, it would be nice if that were the default behavior when running stuff in GitHub Actions, so that users don't have to do anything to make it work.

**Comment by jimhester** [comment]
The GitHub Action workflow examples now use pak, so I think this is less relevant now than when it was opened.
