### ISSUE TITLE
package_deps ignores "recommended" packages

### ISSUE THREAD

**Issue by dselivanov** [r-lib/remotes#569]
Is there a strong reason to [not check](https://github.com/r-lib/remotes/blob/f0022703d72cdd5e6e75f162894e965fb0171873/R/deps.R#L72) "recommended" packages for updates? 

I have an issue with that - my pkg depends on [Matrix](https://cran.r-project.org/web/packages/Matrix/index.html) pkg which is recommended. However it depends on recent Matrix >= 1.3 while most recent  R 4.0.3 contains Matrix 1.2.*.

**Comment by jimhester** [comment]
In practice it seems R users rarely if ever update recommended packages manually, instead relying on whatever version of recommended package is installed when they install R. A workaround you could use would be to increase the R version requirement of your package.

I think one argument against checking the recommended packages in remotes is often they are installed in the system package library which users may not have access to.
