### ISSUE TITLE
Can install_github() et al. scout for a DESCRIPTION file

### ISSUE THREAD

**Issue by krlmlr** [r-lib/remotes#576]
if no subdirectory is given? We could restrict the search to such files where one line matches `^Package: ...$` .

Currently:

``` r
remotes::install_github("igraph/igraph")
#> Using github PAT from envvar GITHUB_PAT
#> Downloading GitHub repo igraph/igraph@HEAD
#> Error: Failed to install 'igraph' from GitHub:
#>   Does not appear to be an R package (no DESCRIPTION)
```

<sup>Created on 2021-01-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Useful for automation, important for igraph, duckdb and other packages where the R code is in a subdirectory.

**Comment by jimhester** [comment]
I think this is out of scope, there wouldn't really be a way to do this robustly without walking the entire directory tree of the github repository, which seems like a bad idea.

**Comment by krlmlr** [comment]
Isn't the `.zip` file downloaded anyway? What if the `.zip` contains only one file named `DESCRIPTION` that has a line that matches `"^Package: "` ?
