### ISSUE TITLE
Skip installation if the sha1 is not changed

### ISSUE THREAD

**Issue by wush978** [r-lib/remotes#58]
Hi,

Is it possible to skip installation if the sha1 is not changed? Currently, `devtools::install_github` has this feature (https://github.com/hadley/devtools/blob/d8ab190cd05e4bd2a3688a1eab3324109060b111/R/install-remote.R#L26) It would be great if `remotes` has feature, too.

Thanks,
Wush

**Comment by jimhester** [comment]
The plan is for devtools to use remotes in the future. So we would like to do this, but doing so without introducing extra dependencies in remotes will take some thought.

**Comment by wush978** [comment]
Hi @jimhester ,

Thanks for your reply. 

Maybe I will implement this feature in this summer. Do you have any contribution rule so that I could send a PR to you if I resolve this issue?

**Comment by jimhester** [comment]
This is now fixed by #135

**Comment by wush978** [comment]
Thanks
