### ISSUE TITLE
Regular install packages fails because devtools not installed

### ISSUE THREAD

**Issue by ArnauC** [r-lib/remotes#586]
Hi, I'm experiencing the following problem:

When I try to install any package (forcats in this example), at first, it seems to download the package just fine, but right after, I get the following error:

Error in library(package, character.only = TRUE, lib.loc = lib.loc) :
there is no package called ‘devtools’
Calls: -> library
Ejecución interrumpida
Warning in install.packages :
installation of package ‘forcats’ had non-zero exit status

The downloaded source packages are in
‘/tmp/RtmpzWbLHK/downloaded_packages’

![image](https://user-images.githubusercontent.com/10518683/108374288-17841d00-7201-11eb-8a6d-155c402c3ab9.png)

**Comment by jimhester** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
