### ISSUE TITLE
Install with devtools::install_github() fails to detect build tools

### ISSUE THREAD

**Issue by mduska** [r-lib/remotes#591]
Not sure if r-lib/usethis is the better place for this, but this is my first time trying to download a Github package, and I'm running into some trouble using RStudio v1.2.5033 on MacOS Big Sur v11.2.1.

Initially, when running

```
library(devtools)
devtools::install_github('xuyiqing/gsynth')
```

I was getting this error:

```
Warning in install.packages :
  installation of package ‘gsynth’ had non-zero exit status
```

Did some reading, and it looked like I needed to download Command Line Tools, so I downloaded XCode CLI, clang4, and gfortran. Now I am getting a pop-up message saying:

"Install Build Tools Building R package from source requires installation of additional build tools. Do you want to install the additional tools now? Y/N"

If I click "Yes", it brings me to this webpage: cnet.com/how-to/install-command-line-developer-tools-in-os-x, which just tells me to download the tools I've already downloaded.

If I click "No", I get this error:

```
Error: Failed to install 'gsynth' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
```

Running the above pkgbuild code in an R console, this is what I get:

```
Trying to compile a simple C file
Error: Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
rror: Could not find tools necessary to compile a package
```

**Comment by jimhester** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
