### ISSUE TITLE
"Error: Failed to install 'unknown package' from Git:" with attempted install of distRforest with remotes

### ISSUE THREAD

**Issue by AJ-RTO** [r-lib/remotes#592]
I am trying to install distRforest on an r4.02 local desktop, but am getting an unknown package error with both devtools and remotes:
devtools::install_github("henckr/distRforest")
Error: Failed to install 'unknown package' from GitHub:
  Timeout was reached: [api.github.com] Connection timed out after 10000 milliseconds
remotes::install_github("henckr/distRforest")
Error: Failed to install 'unknown package' from GitHub:
  Timeout was reached: [api.github.com] Connection timed out after 10000 milliseconds

I successfully installed the devtools and remotes packages before attempting the Github installation.

I have also tried the solution to issue #2305, without success:
remotes::install_git("https://github.com/henckr/distRforest.git")
Error: Failed to install 'unknown package' from Git:
  Error in 'git2r_remote_ls': failed to send request: The operation timed out

Please help.

Many thanks.

**Comment by jimhester** [comment]
This seems like a configuration issue. 
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
