### ISSUE TITLE
R CMD complains about Remotes field in DESCRIPTION

### ISSUE THREAD

**Issue by mbojan** [r-lib/remotes#596]
`R CMD check` complains about `Remotes` field in `DESCRIPTION`:

```
Unknown, possibly mis-spelled, fields in DESCRIPTION:
  ‘Remotes’
```

I haven't tested if CRAN operators will complain as well...

**Comment by ijlyttle** [comment]
This is expected behavior - CRAN will complain; `Remotes` is used to support non-CRAN repositories. A common use-case  developing a package while depending on a development version of another package: https://github.com/r-lib/remotes#additional-repositories

**Comment by mbojan** [comment]
Ah, correct. Thanks!
