### ISSUE TITLE
Error: Missing commas separating Remotes

### ISSUE THREAD

**Issue by jfisher-usgs** [r-lib/remotes#606]
I'm getting inconsistent behavior when running `remotes::dev_package_dep` on Windows and Ubuntu. On Windows the following works without issue,

```r
remotes::dev_package_deps(system.file(package = 'dvv'), dependencies = TRUE)
```
And when run on Ubuntu it fails with the following message:

```
Error: Missing commas separating Remotes: 'Remotes: xxxxxxxxxx@develop'
```
Digging into the code I discovered inconsistent results for the following commands:

```r
path <- system.file('DESCRIPTION', package = 'dvv')
fields <- colnames(read.dcf(path))
as.list(read.dcf(path, keep.white = fields)[1, ])[['Remotes']]
```

The output on Windows is :

```
[1] "gitlab@xxxxxxxxxx::pyrt/dset/rlms@develop,\n        gitlab@xxxxxxxxxx::pyrt/dset/aqsapi@develop"
```

whereas, the output on Ubuntu is:

```
[1] "Remotes: gitlab@xxxxxxxxxx::pyrt/dset/rlms@develop,\n    gitlab@xxxxxxxxxx::pyrt/dset/aqsapi@develop"
```

It looks like the string is not being properly parsed. Not sure what's going on, but perhaps you can help. By the way, the **remotes** package is amazing, thank you!

Partial Session Info:

```
R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

other attached packages:
[1] remotes_2.3.0
```

```
R version 4.0.5 (2021-03-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

other attached packages:
[1] remotes_2.3.0
```

**Comment by jimhester** [comment]
Not sure why you are seeing a difference here, I have never seen this across many packages.
