### ISSUE TITLE
`package_deps` returns `TRUE` and `"CRAN"` for columns `is_cran` and `remote` on made-up package

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/remotes#607]
Tried this with remotes version 2.3.0.9000:

``` r
library(remotes)
foo <- package_deps('MadeUpPackage')
foo
#> Not on CRAN ----------------------------
#>  package      installed available is_cran remote
#>  MadeUpPac... NA        NA        TRUE    CRAN
colnames(foo)
#> [1] "package"   "installed" "available" "diff"      "is_cran"   "remote"
```

In addition, the columns `is_cran` and `remote` are absent from the *Value* section of the help page of `package_deps()`.

**Comment by jimhester** [comment]
The package you are trying to install is always included as assumed to be a CRAN package. I don't think it is worth fixing this.
