### ISSUE TITLE
remotes::install_deps() on ci installting rlang several times

### ISSUE THREAD

**Issue by Athanasiamo** [r-lib/remotes#610]
Hi.

I'm running the default usethis standard release check for github actions. I'm struggling with getting my package to pass checks because rlang is being installed several times during dependency installs. 

My initial problem is that `rmarkdown` now depends on 0.4.11.9000, which is not on CRAN. So, my dependencies were failing for having the wrong rmarkdown version. 

I then added rlang as a remote, so that the newest dev version from github would be installed in stead. From the build log, I can see that the first version of rlang to be installed is the 0.4.11.9000 tar. 

But, while installing the remaining dependencies, the CRAN version of rlang is being pulled and installed, and rmarkdown fails with the same error still. 

I'm a little unsure how to proceed. 

repo:  https://github.com/Athanasiamo/swc.tidyverse
build log: https://github.com/Athanasiamo/swc.tidyverse/actions/runs/820190022
DESC: https://github.com/Athanasiamo/swc.tidyverse/blob/main/DESCRIPTION

**Comment by jimhester** [comment]
This is due to a bug in the installation order used by `install.packages()` when installing mixed binary and source packages (https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17864).

In this case rmarkdown was recently released to CRAN and a package binary has not yet been built for it. Once it is built this will resolve itself. Until then there is not a lot you can do I am afraid.

**Comment by Athanasiamo** [comment]
alrighty. Then I'll wait patiently. I wont have students installing it for another week, so hopefully it'll be sorted by then so I can be sure things should install for them. 

Thanks for the quick reply!

**Comment by jimhester** [comment]
Another alternative would to use a pak based workflow, which doesn't have this problem, e.g. https://github.com/r-lib/actions/blob/master/.github/workflows/check-pak.yaml

That tests more versions of R than you likely need, but you could delete the lines from https://github.com/r-lib/actions/blob/0d6c4b3efe82090bc03e99c585d9e89003117931/.github/workflows/check-pak.yaml#L29-L37 that you don't want to test.

**Comment by Athanasiamo** [comment]
Thank you @jimhester . I tried that and just removed the unwanted jobs and it worked like a charm. Everything passing and looking shiny.
