### ISSUE TITLE
package building: install rstan from third party url from DESCRIPTION remotes

### ISSUE THREAD

**Issue by stemangiola** [r-lib/remotes#615]
In the case of rstan, the community has created an independent repository. This because CRAN had been challenging to develop for (for them).

https://mc-stan.org/r-packages/

For example 

```r
install.packages("rstan", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
```

Can I use `remotes` to link to `https://mc-stan.org/r-packages/` from the DESCRIPTION of my package?

**Comment by jimhester** [comment]
You should be able to add that URL to the `Additional_repositories:` and it should pick it up.
