### ISSUE TITLE
`RemotePkgType` is not necessarily something that we can pass to `available.packages()`

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/remotes#617]
Unfortunately. pak sets this to `macos` and `windows`. I think remotes could maybe ignore it?

**Comment by jimhester** [comment]
It is always meant to be the `type` parameter in `install.packages`, e.g. one of `"source", "mac.binary", and "win.binary"`.

**Comment by gaborcsardi** [comment]
Does remotes add this at all? I can't find it anywhere in the code.
