### ISSUE TITLE
install_git() Assumes github-style urls and credential-less web server access

### ISSUE THREAD

**Issue by dgkf** [r-lib/remotes#625]
Despite being able to clone a repository in the command line, I was running into errors using `install_git` to install dependencies. After some investigation, I found a few assumptions that might contribute to errors:

https://github.com/r-lib/remotes/blob/a14cf0031da2d083854246914b4974f09656443a/R/install-git.R#L148-L151

These lines in `remote_package_name.git2r_remote` assume a github-style raw file content url without a safe fallback. ~~For example, where GitHub will use `.../raw/<ref>/<path>`, GitLab will use `.../-/raw/<ref>/<path>`.~~ _Edit: after further testing, the GitHub style is totally fine for GitLab._

Likewise, this assumes that one has unauthenticated access to these web pages. At least in my org, I run into the error below because `read.dcf` is trying to parse the log-in page that unauthenticated access redirects to.

```
Error: Failed to install 'unknown package' from Git:
  Line starting '<!DOCTYPE html> ...' is malformed!
```

Would it be possible to fall back to return `NA` or fall back to a method that only assumes a basic git functionality when such assumptions cause errors?

**Comment by jimhester** [comment]
That code is from https://github.com/r-lib/remotes/pull/603, you might want to talk to @niheaven about supporting more services but generally I don't think it will be possible to support everything.

**Comment by dgkf** [comment]
Thanks @jimhester (& thanks @niheaven for your work on this already - it's generally worked perfectly with only this slight hiccup!)

@niheaven - would it be okay to add such a fallback?

```diff
if (grepl("^https?://", remote$url)) {
+  tryCatch({
    url <- build_url(sub("\\.git$", "", remote$url), "raw", remote_sha(remote, ...), description_path)
    download(tmp, url)
    read_dcf(tmp)$Package
+  }, error = function(e) NA_character_)
}
```

Wrapping this in a `try` block, similar to the `git archive` method below would provide a safe fallback when the url follows a different structure or requires authentication. I'd be happy to help put together a PR if you'd like.

**Comment by niheaven** [comment]
@dgkf 👍 for your PR
