### ISSUE TITLE
Unable to install devtools on Jupiter Lab workspace

### ISSUE THREAD

**Issue by kamaulindhardt** [r-lib/remotes#635]
Dear community, 

I am asking for your help on this issue using Jupyter Lab with an R kernel. 

I am new to Jupyter Labs, but have recently started using it with R kernel. I am working on a workspace hosted by the CGIAR's Collaborative GARDIAN Labs (CG Labs) that facilitate the collaboratively writing of scripts and running of analyses via Jupyter, which has been extended to support smooth data exchange via the CG Labs Globus Servers. (https://labs.scio.systems/html/about.html)

Normally I simply use `install.packages("devtools")` to install devtools into my RStudio. This approach has worked for other packages in Jupiter Lab but not for "devtools". When I try I get errors related to the dependencies. This approach have worked for other packages but not for "devtools". Here I get this error:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/83076278/125325767-9b21e000-e341-11eb-941b-68cf09f56c17.png">

 
Does anyone have an idea about what is going on here? I have my library set as` "/opt/conda/lib/R/library"`.. 

I suspect the issue to be related to my library specifications, however, I have no idea how to investigate this nor change the library specifications.

**Comment by jimhester** [comment]
If you are using conda you I believe need to use `conda install` to install R packages, not `install.packages()` and devtools.

The latter tools expect standard R build toolchains, which conda does not provide.

Note that conda does not provide all CRAN R packages, let alone packages on GitHub.

**Comment by kamaulindhardt** [comment]
Thank you @jimhester 

Interesting information. How would you then proceed and make use of the `conda install`? Do you have any information/tutorial/guidance on how I could do that? 

I see that `devtools` is a package that is also in CRAN, so in theory, one should be able to install it using `instal.packages()`, but this does not work. Using `conda install` requires me to set up an anaconda library path (see here: https://docs.anaconda.com/anaconda/navigator/tutorials/r-lang/), which I don't really see how I could do in the cloud-based CG Lab.

**Comment by jimhester** [comment]
I am confident that these issues are a result of the environment you are running the code in, not an issue with devtools or its dependencies.

I unfortunately am not familiar with conda, so can't help you further.

I would suggest opening an issue on the community sites for conda, or at <https://community.rstudio.com> and asking other users for help there.
