### ISSUE TITLE
remotes::install_github fails with API rate limits 

### ISSUE THREAD

**Issue by Nelson-Gon** [r-lib/remotes#638]
I am currently having failing [builds](https://github.com/Nelson-Gon/shinymde/runs/3292714539) for a specific package. Looking at the source of the failing checks reveals:

```
Error: Error: HTTP error 401.
  Bad credentials

  Rate limit remaining: 59/60
  Rate limit reset at: 2021-08-10 17:39:26 UTC
```

I only did run this once in an hour so I'm thinking this may be related to: https://github.com/r-lib/devtools/issues/2299 and not sure how this could be fixed. 

Thank you and please do let me know if I need to provide more information.

Nelson

**Comment by jdblischak** [comment]
I was able to fix the `HTTP error 401`  on GitHub Actions by defining `GITHUB_PAT` with the job's token:

```
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
```

In general it seems that relying on the bundled PAT is not robust. A similar issue was discussed in #330

**Comment by Nelson-Gon** [comment]
> I was able to fix the `HTTP error 401` on GitHub Actions by defining `GITHUB_PAT` with the job's token:
> 
> ```
>     env:
>       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
> ```
> 
> In general it seems that relying on the bundled PAT is not robust. A similar issue was discussed in #330

Thanks a lot, this fixes it!

**Comment by rainxfan** [comment]
> 
This fixed the issue, thank you!

**Comment by jon4thin** [comment]
> > 
> 
> This fixed the issue, thank you!
> 
> > I was able to fix the `HTTP error 401` on GitHub Actions by defining `GITHUB_PAT` with the job's token:
> > ```
> >     env:
> >       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In general it seems that relying on the bundled PAT is not robust. A similar issue was discussed in #330

Where do you enter this? This does not look like R code to me....
