### ISSUE TITLE
remotes::dev_package_deps() fails to load DESCRIPTION file from a masked/mangled github URL

### ISSUE THREAD

**Issue by chrisknoll** [r-lib/remotes#639]
In our git actions output for testing our custom R package (hosted on github), we're experiencing an error during execution:

```
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/***/CirceR/contents/DESCRIPTION?ref=HEAD'
Calls: saveRDS ... github_DESCRIPTION -> download -> base_download -> base_download_headers
Execution halted
Error: Process completed with exit code 1.
```

The main repo is here: https://github.com/OHDSI/CohortGenerator

The github actions report is here: https://github.com/OHDSI/CohortGenerator/runs/3294257207?check_suite_focus=true

The referenced package `CirceR` is found here: https://github.com/ohdsi/circer

Our main question is: is it normal for the requested URL for the DESCRITPION file to be masked with the *** as in: `cannot open URL 'https://api.github.com/repos/***/CirceR/contents/DESCRIPTION?ref=HEAD'`

If we change the *** to the actual organization `OHDSI` for this URL the request works, so is it possible the URL is being mangled?

We've tested loading each individual package locally and this error doesn't occur, so we think it's localized to github actions.

The relevant part of our Github-Actions script is:
```
      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}
```

It seems the error stems from `saveRDS()`, and somewhere during `remotes::dev_package_deps()` it fails to read the description file due to the previously mentioned mangled URL.

**Comment by anthonysena** [comment]
Per https://github.com/r-lib/remotes/issues/638#issuecomment-897741838, defining GITHUB_PAT with the job's token seems to allow us to work around this issue.

**Comment by chrisknoll** [comment]
Thanks, @anthonysena , but I noticed in the other issues that the requested URL was not masked, so I'm glad the GITHUB_PAT variable fixes the issue, but maybe there's still an issue related to the URL?  Maybe the devs could clarify.

**Comment by jimhester** [comment]
I don't think the masking is the problem here, so I am going to close this issue.

**Comment by chrisknoll** [comment]
Can you at least point me somewhere that would explain the behavior?   From #638 

> Rscript -e 'remotes::install_github("r-lib/callr")'
> Using bundled GitHub PAT. Please add your own PAT to the env var `GITHUB_PAT`
> Error: Failed to install 'unknown package' from GitHub:
>   cannot open URL 'https://api.github.com/repos/r-lib/callr/contents/DESCRIPTION?ref=HEAD'
> Execution halted
> 

No masking there.  The main thrust of this issue was why the URL is being masked and if it's the reason for the URL failure.

**Comment by jimhester** [comment]
remotes bundles a GitHub personal access token with no scopes solely to increase the rate limits for API calls for users. A 3rd party was using this same token in their package code and GitHub token scanning automatically revoked it.

As noted above if you specify your own token rather than relying on the bundled one this issue will be resolved.

The masking is likely coming from the GitHub Actions log, not anything in remotes.

**Comment by chrisknoll** [comment]
Thank you!
