### ISSUE TITLE
Downloading right version, Building wrong version. 

### ISSUE THREAD

**Issue by WKIDSolutions** [r-lib/remotes#643]
I pushed a new release to github for a package that I help maintain (https://github.com/earthlab/cft), but the updates aren't propagating through to a new install. If I uninstall the package and then reinstall: 

```r
remotes::install_github("earthlab/cft@*release",force=TRUE)
```

It result in a downloaded version 0.4.0, but the build of 0.1.0: 
```r
**Downloading GitHub repo earthlab/cft@v0.4.0**
Running `R CMD build`...
* checking for file ‘/private/var/folders/.../earthlab-cft-eef47cf/DESCRIPTION’ ... OK
* preparing ‘cft’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘cft_0.1.0.tar.gz’
* installing *source* package ‘cft’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (cft)
```
Any suggestions?

**Comment by jimhester** [comment]
That is because in the DESCRIPTION file of the tarball for the latest release the package still has 0.1.0. You can download the tarball from the release page and inspect the DESCRIPTION file within to verify this.

It seems https://github.com/earthlab/cft/commit/85bb583d7f233b7fb2bc37a08dcc62265003e238 was not included in the 0.4.0 release.

**Comment by WKIDSolutions** [comment]
humm ok thanks. Apologies for how naive this is, but I think I fixed that after I pushed the release by updating the DESCRIPTION file. All I had to do was update the line that says "Version X.X.X" in the DESCRIPTION file correct? 

If yes, then I guess I've done that and can just rebuild and update the release with the new tarball.

**Comment by jimhester** [comment]
Yes, that is correct, just changing the `Version: X.Y.Z` line is what you need to do.

**Comment by WKIDSolutions** [comment]
@jimhester - this does not seem to be the case. I updated the Description as you can see in the Github DESCRIPTION file, but when I do a new release and check the tarball it still has the old version. How do I push the new files into this tarball?

**Comment by jimhester** [comment]
You would need to include the change in a commit before the release, not after it.

**Comment by WKIDSolutions** [comment]
I did. Is it because I deleted the old release and used the same release name?
