### ISSUE TITLE
.git folder not downloaded

### ISSUE THREAD

**Issue by mitch7744** [r-lib/remotes#647]
https://github.com/r-lib/remotes/blob/6a0e560de1fd48933cb2c4e9e795ebd50426d880/R/install-remote.R#L56

remote_download downloads tar.gz repo bundle but doesn't contain .git folder.
Upon decompression of the bundle, any subsequent 'git describe --tags' calls return a "fatal: not a git repository ...." error.

**Comment by jimhester** [comment]
Yes, this is intentional, `install_github()` does not require a git client or libgit2 to work. If you want the `.git` folder you can use `install_git()`.

**Comment by mitch7744** [comment]
Thanks @jimhester.

Regarding install_git(), does it work for https or is it restricted to ssh authentication only? 

I receive this S3 class error even when global option 'remotes.git_credentials' is set.

![image](https://user-images.githubusercontent.com/88300031/132778251-349ebbf6-e1ac-4659-9796-556729ce2171.png)

**Comment by jimhester** [comment]
It should work for both https and ssh.
