### ISSUE TITLE
install_git with credentials broken after 2.4.0

### ISSUE THREAD

**Issue by camitz** [r-lib/remotes#652]
Hello!

After remotes 2.4.0, devtools::install_git() passing credentials is broken. 

The following works.

```
devtools::install_version("remotes", version = "2.3.0")
rstudioapi::restartSession()
cred <- git2r::cred_user_pass("martin.camitz", rstudioapi::askForPassword("Lösenord"))
devtools::install_git(url="https://git.folkhalsomyndigheten.se/fohmverse/fohmdown", credentials = cred)

# Downloading git repo https://git.folkhalsomyndigheten.se/fohmverse/fohmdown
```

The following does not:

```
devtools::install_version("remotes", version = "2.4.0")
rstudioapi::restartSession()
cred <- git2r::cred_user_pass("martin.camitz", rstudioapi::askForPassword("Lösenord"))
devtools::install_git(url="https://git.folkhalsomyndigheten.se/fohmverse/fohmdown", credentials = cred)

# Error: Failed to install 'unknown package' from Git:
#  Line starting '<!DOCTYPE html> ...' is malformed!
```

I can give access to whomever needs it to reproduce but any private repository will do och github or gitlab.

I believe @niheaven 's [commit](https://github.com/r-lib/remotes/commits/a44d96b5ad6aa388b099c8146e94b9dddfd5524b/R/install-git.R) is the culprit, install-git.R, around line 148, but I'm only guessing.

**Comment by baslat** [comment]
Adding that this workaround is also necessary to install a package from Azure DevOps, as the [old method](https://github.com/r-lib/remotes/issues/439) has stopped working.

**Comment by achimgaedke** [comment]
Please check again with https://github.com/r-lib/remotes/pull/658 is included in the next release.

**Comment by camitz** [comment]
Tested and it appears to work. Thanks for great work @achimgaedke .
