### ISSUE TITLE
Feature request: auto-detect when update_packages() requires standalone mode

### ISSUE THREAD

**Issue by pnacht** [r-lib/remotes#653]
As discussed in #613, `update_packages` must be in standalone mode to update its own dependencies such as `curl`, etc.

However, this implies that if one wants to update packages, one must:

- run `update_packages()`
- have the relevant dependencies memorized
- check for those dependencies in the list of updateable packages
- if any are found, cancel the update
- set the Standalone Mode environment variable
- run `update_packages()` again

(I assume there's a reason to prefer using those dependencies whenever possible, so simply setting Standalone Mode every time doesn't seem reasonable)

Would it be possible to perform the check within `update_packages`? That is: fetch the list of updateable packages (or maybe the subset requested by the user), see if any of the relevant dependencies are on that list, and set Standalone Mode as needed?

**Comment by gaborcsardi** [comment]
That is a user choice, we can't auto-detect it.
