### ISSUE TITLE
Feature request: support system_requirements() of CRAN dependencies of Bioconductor packages

### ISSUE THREAD

**Issue by bersbersbers** [r-lib/remotes#660]
```r
remotes::system_requirements("ubuntu-20.04", package = "ComplexHeatmap")
```
returns nothing. As a human, I can see that `ComplexHeatmap` (despite not being on CRAN) depends on the `Cairo` CRAN package, which has system requirements: https://bioconductor.org/packages/release/bioc/html/ComplexHeatmap.html

I wonder if `system_requirements()` could resolve CRAN dependencies of Bioconductor packages. (`remotes::package_deps("ComplexHeatmap")` returns nothing, either.)

**Comment by gaborcsardi** [comment]
Take a look at pak, it does a better job at looking up system requirements of non-cran packages.
