### ISSUE TITLE
Bump Bioc version map for `R v4.1` to `3.14`

### ISSUE THREAD

**Issue by stufield** [r-lib/remotes#664]
After the recent Bioconductor release of `v3.14` on 2021-10-27, the version map version inside `bioc-standalone.R` looks like it still points to `v3.13`, however according to the recently updated BioC docs:

https://www.bioconductor.org/about/release-announcements/#release-versions

`R v4.1` should map to Bioconductor `v3.14`. 

After the Bioconductor update in October, this causes `bioc_version()` (current CRAN `v2.4.1` & `v2.4.1.9000`) to point to the wrong (old) version associated with its `R v4.1`. I think ...

```
sapply(c("3.6", "4.0", "4.1", "4.2"), remotes::bioc_version)
```

If I'm wrong, please feel free to close. Otherwise I'm happy to submit a PR.

**Comment by riccardoporreca** [comment]
Indeed @stufield, this is now biting as there is a unit test hard-coding the expected Bioconductor release version, see e.g. https://github.com/r-lib/remotes/runs/4086816248?check_suite_focus=true#step:6:148
```

```

**Comment by stufield** [comment]
I have a GitHub Action that runs `rcmdcheck()` but first installs a Bioconductor package that alerted me to this issue. Otherwise I may not have noticed.

**Comment by jimhester** [comment]
A PR updating the mapping would be great, thanks!

**Comment by bersbersbers** [comment]
Are there plans to make a release for this? I stumbled across his issue in #668. Specifically, a to-be-released package of mine depends on a recent version of some Bioconductor package (present only in 3.14), and I'd like to avoid having to add some `BiocManager::install(ask = FALSE)` to update outdated packages immediately after installation.
