### ISSUE TITLE
install_local(".")

### ISSUE THREAD

**Issue by krlmlr** [r-lib/remotes#67]
Fails for a simple package:

``` r
system("git clone https://github.com/krlmlr/tic.packagedocs.git")
withr::with_dir("tic.packagedocs", remotes::install_local("."))
#> Error: Don't know how to decompress files with extension yml
```

Succeeds with directory name as `path` argument:

``` r
system("git clone https://github.com/krlmlr/tic.packagedocs.git")
withr::with_temp_libpaths(remotes::install_local("tic.packagedocs"))
#> Installing package into '/tmp/Rtmpk1WkuT/temp_libpath7d12c71a3d7'
#> (as 'lib' is unspecified)
```

I can work around with `getwd()`, but it would be great if this just worked.

**Comment by gaborcsardi** [comment]
Maybe just needs a `normalizePath()`? PR? :)

**Comment by krlmlr** [comment]
Yeah, but that's only half of the story. Ideally I'd not copy the bundle to a temp directory, because this messes up the srcrefs in the installed package. Why did you decide to copy to a temp dir?

**Comment by gaborcsardi** [comment]
Verbatim copy from devtools: https://github.com/hadley/devtools/blob/d3482c5ee63356f7b6f042b494bed5f11861e933/R/install-local.r#L30-L37

**Comment by krlmlr** [comment]
Implemented three years ago in hadley/devtools@0c8a60777. Agree to change to use the original location? Side effects: Updated `.o` files. Need to check if the SHA1 remains stable between installs of the same package.

**Comment by gaborcsardi** [comment]
I think it is better to do it in the tempdir. Some packages mess with other things, not just compilation, e.g. copy executables, libs, etc. It is always cleaner to build/install in a temp dir.

**Comment by krlmlr** [comment]
The installation dir should be persistent, because srcrefs and native debugging information points to the files. How about using a subdirectory of the R library as installation dir? Say, copy to `file.path(.libPaths()[[1]], "remotes", pkg_name)` before installing, and keep the files there?

**Comment by gaborcsardi** [comment]
Given that `install.packages` does not keep source references, I am not sure if we should sweat over this. 

Keeping the source packages in the package library is a good idea, but quite a big change imo, so I would rather discuss this. Also, if we do this for `install_local()`, then we should probably do it for all installs, no?

**Comment by krlmlr** [comment]
I didn't care about srcrefs until I had the opportunity to actually navigate the stack trace with brushthat. It will currently die if the file cant' be found; this can be helped, but I wonder if we could do better in the context of this package.

For all installs, of course. Hence, independent of the issue at hand.

**Comment by gaborcsardi** [comment]
So how about we fix this issue using `normalizePath` and discuss the source references in another issue, involving others?

It would totally make sense to keep source references, but I think we need to think about the *how*.

**Comment by krlmlr** [comment]
Absolutely.

**Comment by krlmlr** [comment]
Actually, should `path = "."` be the default?

**Comment by gaborcsardi** [comment]
Doesn't it assume an already built package? Then `"."` might be misleading.

**Comment by krlmlr** [comment]
I'm using `install_local()` for GitHub clones, works well.

**Comment by gaborcsardi** [comment]
Coincidence? :) I think using `devtools::install()` is a better option.

**Comment by krlmlr** [comment]
I thought at some point `devtools::install()` would call `remotes::install_local()`.? `R CMD INSTALL` also works well for source directories. What am I missing?

**Comment by gaborcsardi** [comment]
Some packages need `R CMD build`. E.g. to ignore some files.

**Comment by krlmlr** [comment]
Should have opened a new issue right from the start. Feel free to close out-of-scope issues.
