### ISSUE TITLE
in `install_github` argument `ref` doesn't accept tags

### ISSUE THREAD

**Issue by OfekShilon** [r-lib/remotes#677]
As detailed in [this SO answer](https://stackoverflow.com/a/40179557/89706), this doesn't work:
```
remotes::install_github(repo="https://github.com/Rdatatable/data.table", ref="1.14.0")
```
(doesn't work == hangs indefinitely)  but this does:
```
remotes::install_github(repo="https://github.com/Rdatatable/data.table@1.14.0")
```

Maybe the fix is just to change the documentation - but hopefully the documented syntax can be made to work.

**Comment by gaborcsardi** [comment]
For the record 
```R
remotes::install_github(repo="https://github.com/Rdatatable/data.table", ref="1.14.0")
```
does work for me and if it does not work for you, then please reopen this issues with the details.
