### ISSUE TITLE
Test failures if SVN is not installed on test system

### ISSUE THREAD

**Issue by AshesITR** [r-lib/remotes#684]
`test-install-svn.R` could use a skip if SVN is not installed on the test system.
Currently it produces 4 failures in ll. 16, 45, 98 and 114:

```
Error (test-install-svn.R:16:3): install_svn
<install_error/error/condition>
Error: Failed to install 'unknown package' from SVN:
  SVN does not seem to be installed on your system.
Backtrace:
 1. remotes::install_svn(url, lib = lib, quiet = TRUE) test-install-svn.R:16:2
```

**Comment by AshesITR** [comment]
Sorry for being unclear, these are on my local machine, which doesn't have SVN installed. It occurred to me when I ran `devtools::test()`.

Since some other tests have skip rules, I thought they might have been missed in this case. Feel free to close if this is intentional.

**Comment by gaborcsardi** [comment]
Yeah, this is somewhat subjective, but personally I don't like skipping tests like this, because that makes it all too easy never to run them.
