### ISSUE TITLE
Update guidance on where to place GitHub PAT

### ISSUE THREAD

**Issue by hfrick** [r-lib/remotes#689]
usethis now strongly [discourages](https://usethis.r-lib.org/articles/git-credentials.html#tldr-use-https-2fa-and-a-github-personal-access-token) placing the PAT in `.Renvir` but a few functions in remotes still issue that guidance:

https://github.com/r-lib/remotes/blob/fcad17b68b7a19d5363d64adfb0a0426a3a5b3db/R/github.R#L183

https://github.com/r-lib/remotes/blob/fcad17b68b7a19d5363d64adfb0a0426a3a5b3db/inst/install-github.R#L2684

This could be replaced with ```"Use `gitcreds::gitcreds_set()` to add the token."``` or something similar? I'd make a PR but am unsure if this includes updating the corresponding line in `./install-github.R` as well?

**Comment by gaborcsardi** [comment]
A PR is welcome. :)  `install-github.R` is updated by running `make`.
