### ISSUE TITLE
Error: cannot open URL 'https://api.github.com/repos/xxx/yyy/contents/DESCRIPTION'

### ISSUE THREAD

**Issue by hongooi73** [r-lib/remotes#691]
I've seen this error in a couple of places now, while running CI/CD pipelines. The first is on R-Hub, and the second is with Github Actions.

https://builder.r-hub.io/status/Microsoft365R_2.3.3.tar.gz-7092d25930694650b1512d6268bf9b65#L136
https://github.com/RevolutionAnalytics/checkpoint/runs/4916498001?check_suite_focus=true#step:5:28

Has the Github API changed? I'm not bundling a PAT, as both repos are public.

**Comment by hongooi73** [comment]
Hi Gabor,

I'm not sure how using the latest actions will change anything. The full script is here: https://github.com/RevolutionAnalytics/checkpoint/blob/master/.github/workflows/R-CMD-check.yaml

You can see that I'm just calling Rscript to install remotes and then run `install_github`. The only (R-specific) actions I use are setup-r and setup-pandoc.

Will Rhub be updated to fix this?

**Comment by gaborcsardi** [comment]
> I'm not sure how using the latest actions will change anything.

The new actions are much better at everything, especially installing system requirements and packages. But if you don't want to switch, then you need to add your own `GITHUB_PAT` env var, e.g. like this: 

https://github.com/r-lib/actions/blob/fff6ffb826f98069b90e308beffd771d1dbd534b/examples/check-release.yaml#L15

> Will Rhub be updated to fix this?

No, you'll need to supply your own GITHUB_PAT, with the `env_vars` argument.
