### ISSUE TITLE
devtools::install_github forces upgrade of dependencies despite upgrade_dependencies=FALSE

### ISSUE THREAD

**Issue by carbocation** [r-lib/remotes#693]
This is essentially a duplicate of issue r-lib/devtools#863. My specific issue is that I'm on a Mac with systemfonts v1.0.2, installing packages with `devtools::install_github` that depend on `systemfonts`. Even when I pass `upgrade_dependencies=FALSE`, the program tries to upgrade systemfonts to v1.0.3, which is not currently working (compiler issues for objective c). 

If I install packages that depend on systemfonts via `install.packages`, there is no issue. But since `devtools::install_github` forces an upgrade of systemfonts to the latest version, even though I am trying to prevent it from doing so, I am unable to complete the installation of packages with `devtools::install_github`.

This is with R version 3.6.3 and devtools version 2.3.2 on x86_64-apple-darwin15.6.0 / macOS  10.16.

**Comment by gaborcsardi** [comment]
What is the version of remotes that you have installed? Do you see this for the latest remotes version, with the name of the argument correctly specified as `upgrade`?

**Comment by carbocation** [comment]
Thanks! `remotes` had a version of `remotes_2.2.0`. I have now upgraded to `remotes_2.4.2` and I no longer have this problem. (I cannot guarantee that the issue was present in remotes_2.2.0, I can just report that since upgrading I am no longer having the problem.)
