### ISSUE TITLE
Error: Missing commas separating Remotes

### ISSUE THREAD

**Issue by leifeld** [r-lib/remotes#699]
`dev_package_deps` can't seem to parse the package names in `Enhances` properly in some cases.

The issue was also reported [here](https://github.com/r-lib/remotes/issues/606) but dismissed.

Example:
```r
download.file("https://cran.r-project.org/src/contrib/Archive/texreg/texreg_1.37.4.tar.gz",
              destfile = "texreg_1.37.4.tar.gz")
remotes::dev_package_deps("texreg_1.37.4.tar.gz", dependencies = "Enhances")
```
This returns:

    Error: Missing commas separating Remotes: 'brms (>= 2.8.8)feisr (>= 1.0.1)'

Tested with `remotes` package version 2.4.2 on Kubuntu Linux.

**Comment by gaborcsardi** [comment]
I don't see this error (any more?), so I am going to close this issue. Please reopen it if you still have problems.
