### ISSUE TITLE
Error: devtools::install_github

### ISSUE THREAD

**Issue by DarianFlorianVoda** [r-lib/remotes#701]
Hello!
I am trying to put a package to GitHub, but is giving me this error:

```
devtools::install_github("DarianFlorianVoda/Diagram-Generator")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`DarianFlorianVoda`) and repo name (`Diagram-Generator`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
```

- Need to mention that my package is private
- I have generated a new token and tried to use auth_token = "[ThatTokenCode]" but it still gives me the same issue
- I have installed Rtools 4.2 and also 4.0 and still won't work
- I also put it public and still doesn't work
- I tried also with auth_token = "GITHUB_PAT" or "GITHUB_BAT" and it tells me `Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 47/60
  Rate limit reset at: 2022-03-21 21:54:32 UTC`

Any help would be useful 😄

**Comment by gaborcsardi** [comment]
> Need to mention that my package is private

It can't because there is no way to know that. 

> I also put it public and still doesn't work

I do not see any package at https://github.com/DarianFlorianVoda/Diagram-Generator so that is surely not public.

**Comment by DarianFlorianVoda** [comment]
> > Need to mention that my package is private
> 
> It can't because there is no way to know that.
> 
> > I also put it public and still doesn't work
> 
> I do not see any package at https://github.com/DarianFlorianVoda/Diagram-Generator so that is surely not public.

I wanted to mention that I tried it also that method of putting it public 😄  Sorry for misconception.
If you want I can put it public if there is a need.

**Comment by gaborcsardi** [comment]
Well, a lot of people use `devtools::install_github()` so I am pretty sure that it works in general. It may certainly have bugs, but to fix them we should be able to reproduce them. So please try to give me something reproducible.

**Comment by DarianFlorianVoda** [comment]
I found a workaround by pushing it manually to my main repository, since the R files were created, but I needed only to install the package with devtools, thanks!
