### ISSUE TITLE
Failed to install 'unknown package' from Bitbucket

### ISSUE THREAD

**Issue by harell** [r-lib/remotes#703]
This issue is related to a closed issue mentioned [here]( https://github.com/r-lib/devtools/issues/2118)

@jimhester this is still an open issue on R4.1.3 remotes v2.4.2. Could you please advise?

I'm trying to install a package on a public Bitbucket repo. This gives the following error

```
install_bitbucket('annalectnz/rianna')
> Error: Failed to install 'unknown package' from Bitbucket:
  cannot open URL 'https://api.bitbucket.org/2.0/repositories/annalectnz/rianna/src/HEAD/DESCRIPTION'
```

However, when I paste the [URL address ](https://api.bitbucket.org/2.0/repositories/annalectnz/rianna/src/HEAD/DESCRIPTION) to Chrome, I can see the DESCRIPTION file content

**Comment by lancefrench** [comment]
Seems highly likely that this is related to the [deprecation of Atlassian account passwords for Basic Authentication with the Bitbucket API or Git over HTTPS](https://bitbucket.org/blog/deprecating-atlassian-account-password-for-bitbucket-api-and-git-activity).  Have you re-tested using an [app password](https://support.atlassian.com/bitbucket-cloud/docs/app-passwords/)?

**Comment by harell** [comment]
I see. If the repo is public (as is the aforementioned repo), do you still expect this error?

**Comment by lancefrench** [comment]
Technically, no, I would not expect the change to basic auth to affect cloning of repositories marked publicly accessible.  (I should read more carefully!) Seems like the [actual function](https://github.com/r-lib/remotes/blob/918c506609858895177c02c4f38706d31bb843d2/R/install-bitbucket.R#L189-L198) should be passing `NULL` for `basic_auth` when downloading.

I might try just issuing a `download()` directly against https://api.bitbucket.org/2.0/repositories/annalectnz/rianna/src/HEAD/DESCRIPTION and seeing if that is successful.

**Comment by harell** [comment]
The following code successfully installs the package on the public repo:

```
remotes::install_git("https://api.bitbucket.org/2.0/repositories/annalectnz/rianna")
```

**Comment by gaborcsardi** [comment]
```
install_bitbucket('annalectnz/rianna')
```
works for me now, but please reopen this issue if you still have problems.
