### ISSUE TITLE
Should install_local() call R CMD build first?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/remotes#71]
Some packages seem to require it, https://github.com/r-lib/remotes/issues/67#issuecomment-311596532.

**Comment by gaborcsardi** [comment]
That would start morphing `install_local` into `devtools::install`. Not necessarily a bad thing, but the original plan was to keep `install()` in `devtools` and only deal with the remote stuff here.

**Comment by krlmlr** [comment]
Where does `devtools::install()` call `R CMD build`?

Perhaps installing local packages should be in pkgbuild instead?

**Comment by gaborcsardi** [comment]
> Where does devtools::install() call R CMD build?

https://github.com/hadley/devtools/blob/d3482c5ee63356f7b6f042b494bed5f11861e933/R/install.r#L135

> Perhaps installing local packages should be in pkgbuild instead?

You mean, build + install? `devtools` does a lot of things already in `install()`, so I would not move that, at least not for now.

**Comment by krlmlr** [comment]
Oh, but this is only for `build_vignettes = TRUE` which isn't the default.

We should document what `install_local()` is supposed to achieve. What is a "local" remote? Currently it's a

> path to a local directory, or compressed file (...)

I'm perfectly fine with forwarding to `?utils::INSTALL` and to declare that this function does whatever `R CMD INSTALL` supports.
