### ISSUE TITLE
Using sub_dir for Remotes: for R package dependency

### ISSUE THREAD

**Issue by Craig44** [r-lib/remotes#712]
Hi

When using the `Remotes:` in an R package dependency, is it possible to specify the sub directory (`subdir`)? 

I have been using the vignette found [here](https://cran.r-project.org/web/packages/devtools/vignettes/dependencies.html), but it is not that obvious to me.

**Comment by gaborcsardi** [comment]
Yes, the format is `user/repo/subdir`.
