### ISSUE TITLE
anybody knows why the connection timeout appear in `install_local()` function?

### ISSUE THREAD

**Issue by XinLi0111** [r-lib/remotes#713]
When I use the `remotes::install_local("/tmp/master.zip")` to install a local git repo. The `Timeout was reached: [api.github.com] Connection timeout after 10001 ms` always appears and then exit.

I don't understand why the network connnection is neccessary when install  a local package.

**Comment by gaborcsardi** [comment]
Because some dependencies are probably referring to packages on GitHub.

**Comment by XinLi0111** [comment]
Thank you, 👍
