### ISSUE TITLE
Unable to install devtools

### ISSUE THREAD

**Issue by alifarhat40** [r-lib/remotes#717]
My lab has a Ubuntu version 20.04.4 LTS (Focal Fossa) and I have spent this past week trying to install devtools to no avail. I tried so many things but cannot seem to install it.
I even tried following these sudo tips among other tips but also failed.
https://www.digitalocean.com/community/tutorials/how-to-install-r-packages-using-devtools-on-ubuntu-18-04

I also tried conda but that also failed:
https://anaconda.org/conda-forge/r-devtools

Has anyone faced something similar and can help me please?

- Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools")
I also tried all other options in the this link such as: https://stackoverflow.com/questions/20923209/problems-installing-the-devtools-package

sudo apt-get install libcurl4-openssl-dev libssl-dev

which outputs the following:

sudo apt-get install libcurl4-openssl-dev libssl-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libcurl4-openssl-dev is already the newest version (7.68.0-1ubuntu2.12).
libssl-dev is already the newest version (1.1.1f-1ubuntu2.16).
0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.

Did you post your log file? If not, add it now.
added below

if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
also installing the dependencies ‘zip’, ‘gert’, ‘usethis’

trying URL https://cloud.r-project.org/src/contrib/zip_2.2.0.tar.gz
Content type 'application/x-gzip' length 114391 bytes (111 KB)
downloaded 111 KB

trying URL https://cloud.r-project.org/src/contrib/gert_1.7.0.tar.gz
Content type 'application/x-gzip' length 118288 bytes (115 KB)
downloaded 115 KB

trying URL https://cloud.r-project.org/src/contrib/usethis_2.1.6.tar.gz
Content type 'application/x-gzip' length 342349 bytes (334 KB)
downloaded 334 KB

trying URL 'https://cloud.r-project.org/src/contrib/devtools_2.4.4.tar.gz'
Content type 'application/x-gzip' length 374492 bytes (365 KB)
downloaded 365 KB

ERROR: failed to lock directory ‘/usr/local/lib/R/site-library’ for modifying
Try removing ‘/usr/local/lib/R/site-library/00LOCK-zip’
ERROR: dependency ‘zip’ is not available for package ‘gert’

removing ‘/usr/local/lib/R/site-library/gert’
ERROR: dependency ‘gert’ is not available for package ‘usethis’
removing ‘/usr/local/lib/R/site-library/usethis’
ERROR: dependency ‘usethis’ is not available for package ‘devtools’
removing ‘/usr/local/lib/R/site-library/devtools’
The downloaded source packages are in
‘/tmp/Rtmp8Of1D0/downloaded_packages’
Warning messages:
1: In install.packages("devtools") :
installation of package ‘zip’ had non-zero exit status
2: In install.packages("devtools") :
installation of package ‘gert’ had non-zero exit status
3: In install.packages("devtools") :
installation of package ‘usethis’ had non-zero exit status
4: In install.packages("devtools") :
installation of package ‘devtools’ had non-zero exit status

**Comment by gaborcsardi** [comment]
Have you tried that suggestion?

**Comment by alifarhat40** [comment]
@gaborcsardi Which suggestion are you referring to? I tried all of the above recommendations. And I still cannot install dev-tools.

**Comment by mmokrejs** [comment]
I managed to install older version of `devtools` initially `0.5` but later up to `1.13.6`. Then I hit a barrier of `R-3.4.4` being too old. See https://github.com/r-lib/devtools/issues/2534 for some copy&paste series of commands to the deps installed manually. Neither `devtools` nor `remotes` can keep trying installing older and older version of whatever package to install one, which dependencies are fullfilled. `remotes` cannot even give you back a list of version of a package available in source code repo which you could then use for a series of a few blind attempts like e.g.

`install.packages("https://cran.r-project.org/src/contrib/Archive/somepackage/somepackage_2.1-1.tar.gz", repo=NULL, type="source")`

Too static listing of versions can be passed down do [repmis](https://christophergandrud.github.com/repmis/) package, see https://www.r-bloggers.com/2013/02/installoldpackages-a-repmis-command-for-installing-old-r-package-versions/

**Comment by gaborcsardi** [comment]
This issue is probably not relevant today, but please reopen if you still have problems.
