### ISSUE TITLE
`install_github` fails when package and repository name differ

### ISSUE THREAD

**Issue by david-cortes** [r-lib/remotes#721]
**Steps to reproduce:**
* Create some R package project with compiled code. Example to use that follows this and the next points: https://github.com/david-cortes/multinomial_probit
* Make the R package have a name with one or more periods (`.`).
* Upload the R package to a github repository, replacing the periods with underscores (`_`).
* Try to install the package with `remotes::install_github(..., build=TRUE)`.

**Expected behavior:** should install the package correctly, just like doing it through `R CMD build` and `R CMD INSTALL` does.

**Actual behavior:** fails to install the package.

To verify that the example package installs correctly, try the following:
```shell
git clone https://github.com/david-cortes/multinomial_probit.git
R CMD build multinomial_probit
R CMD INSTALL multinomial.probit*
```

**Comment by gaborcsardi** [comment]
What's the actual error that you see?

**Comment by david-cortes** [comment]
Oh sorry, just realized it was missing the `Makevars` in the github repository and was thus being compiled with different arguments by `remotes` than by `R CMD`.

**Comment by gaborcsardi** [comment]
> was thus being compiled with different arguments by `remotes` than by `R CMD`.

That seems unlikely to me, as your example failed for me with `R CMD build/INSTALL` as well, the same way as with remotes. Maybe you have a `~/.R/Makevars` file. 

In any case, I am glad you solved the issue.
