### ISSUE TITLE
Could not resolve host when lunching install_local()

### ISSUE THREAD

**Issue by Hainexx** [r-lib/remotes#723]
Hello,

I build a package and it works fine but when I try to install it locally as a package, it doesn't work because it says:
`Error: Failed to install 'pckg_NAME' from local: Could not resolve host: api.github.com`

Do you know why is this possible? what does GitHub has to do with a local installation?

**Comment by gaborcsardi** [comment]
Your package probably refers to a dependency on GitHub.
