### ISSUE TITLE
Does remotes list ALL private repos in a GitHub organization?

### ISSUE THREAD

**Issue by maelle** [r-lib/remotes#726]
I'm seeing a 404 error with `install_github()` for a private repository (while `pak::pak()` works for the same repository). It is an organization with many private repositories.

Could it be that there's an issue related to GitHub API paging?

Cc @yabellini

**Comment by gaborcsardi** [comment]
I don't think remotes list repositories, I would be very surprised if it did.

My guess is that pak uses the credentials from the git credential store, and remotes does not.

**Comment by maelle** [comment]
oooh this makes sense, thanks and sorry.
