### ISSUE TITLE
ga_account_list cannot parse response into dataframe

### ISSUE THREAD

**Issue by Rifmaz** [r-lib/remotes#731]
Hello,

I am currently unable to get an output from the ga_account_list() function as the function fails. The error message is copied below.

I'd like to mention that I've updated my R to version 4.2.1 and all my packages have also been updated to the most recent version (as of the 31st of October 2022):
 - googleAnalyticsR v1.1.0
 - googleAuthR v2.0.0
 - dplyr v1.0.10
 - vctrs v0.5.0

Previous versions installed that were still working:
 - googleAnalyticsR v1.0.0
 - googleAuthR v1.4.0
 - dplyr v1.0.7
 - vctrs v0.3.8

I have installed the previous version of the above packages but I'm still getting the error. I suspect there may be some other dependencies and that is why?

Regarding the gar_parse_error.rds file, I can't share it since it contains client information.

```
my_accounts <- ga_account_list()
Error in list_unchop(x = x, indices = indices, ptype = ptype, name_spec = name_spec,  : 
  Can't combine `x[[1]]` <data.frame> and `x[[1457]]` <list>.
Error: API Data failed to parse.  
             Wrote diagnostic object to 'gar_parse_error.rds', use googleAuthR::gar_debug_parsing('gar_parse_error.rds') to 
             debug the data_parse_function.
```

**Comment by Rifmaz** [comment]
Sorry, posted in the wrong tab :(

**Comment by gaborcsardi** [comment]
@Rifmaz no worries. You can close the issue yourself. :)
