### ISSUE TITLE
Suggestion: install_github() should sort the packages that it suggests

### ISSUE THREAD

**Issue by daattali** [r-lib/remotes#735]
When trying to install a package and `install_github()` tells you "here are 30 packages that can be updated"you may be wondering about one specific package that you know is important. But right now you have to scroll through the entire list and pay attention to each line. It would be much nicer if within each repository (GitHub/CRAN/etc) the packages would be sorted alphabetically.

**Comment by gaborcsardi** [comment]
We are not adding new features to remotes, as we are focusing on pak instead, which already has a much better display of what is going to be installed and from where. It also lists all packages that are going to be installed, before installing them.
