### ISSUE TITLE
Suggestion: install_github() should warn the user when a package doesn't match the version required by DESCRIPTION

### ISSUE THREAD

**Issue by daattali** [r-lib/remotes#736]
Related to #524

When installing a package with `install_github(), I get presented with all the packages that can potentially be updated. However, I noticed that if there's a package that requires a specific version in the DESCRIPTION and my existing version is lower, this package doesn't get installed automatically and {remotes} doesn't tell me that this package should be updated. 

I would think that any package in DESCRIPTION that isn't already installed should be installed (and this does indeed happen), but similarly every package with a version requirement should be upgraded if the version isn't met.

**Comment by gaborcsardi** [comment]
We are not adding new features to remotes, as we are focusing on pak instead, which already has a much better display of what is going to be installed and from where. It also lists all packages that are going to be installed, before installing them.
