### ISSUE TITLE
Packages problems 

### ISSUE THREAD

**Issue by Tdautov** [r-lib/remotes#740]
pacman::p_load(
rio, # for importing data
here, # for locating files
skimr, # for reviewing the data
janitor, # for data cleaning
lubridate, # for date cleaning
epikit, # creating age categories
gtsummary, # creating tables
scales, # percents in tables
viridis, # color scales
tsibble, # epiweeks
apyramid, # age/sex pyramids
flextable, # for making pretty tables
gghighlight, # highlighting plot parts
ggExtra, # special plotting functions
tidyverse # for data management and visualization
)
I am loading this script? but after it gives a problem. I try to reinstall all R and RStudio, but still have problems
Its from console
tidyverse installed
Предупреждения:
1: В download.file(url, destfile, method, mode = “wb”, …) :
** the ‘wininet’ method is deprecated for http:// and https:// URLs**
2: В pacman::p_load(rio, here, skimr, janitor, lubridate, epikit, :
** Failed to install/load:**
gtsummary, viridis, apyramid, gghighlight, tidyverse

**Comment by gaborcsardi** [comment]
You are using pacman, which is a different package than the one tracked in this repository.

**Comment by Tdautov** [comment]
other forms of installation also do not work, I tried all the options, maybe you need to update or install something

**Comment by Tdautov** [comment]
> You are using pacman, which is a different package than the one tracked in this repository.

other forms of installation also do not work, I tried all the options, maybe you need to update or install something
