### ISSUE TITLE
issue rolling back package wdman to previous version using install_version

### ISSUE THREAD

**Issue by sophk1** [r-lib/remotes#746]
I have been attempting to roll back the R package wdman to a previous version in order to hopefully solve a dependency issue with RSelenium. However, I am getting an error with this code:
`remotes::install_version("wdman",version="0.2.5",repos="http://cran.us.r-project.org")`
I get the following output:
`Downloading package from url: http://cran.us.r-project.org/src/contrib/Archive/wdman/wdman_0.2.5.tar.gz
Installing package into ‘C:/Users/abc/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/abc/AppData/Local/Temp/RtmpuCeY3j/remotes1aec32a03b15/wdman’ had non-zero exit status`
 Does anyone know of a fix for this? 
Session Details: Windows 10, R 4.2.2, remotes v2.4.2

**Comment by gaborcsardi** [comment]
I am fairly sure that this is not a remotes issue. Try to download that package and install it manually.

**Comment by gaborcsardi** [comment]
Please reopen this issue if you still have problems with this. Thanks!
