### ISSUE TITLE
Updated: "cannot open URL" with remotes::install_github()

### ISSUE THREAD

**Issue by phargarten2** [r-lib/remotes#750]
I have the same issue cited in #130 . 
```
remotes::install_github("yihui/testit")
# Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
# cannot open URL 'https://api.github.com/repos/yihui/testit/zipball/master'
```

The proposed solution was to change an option within Internet Explorer 10. 
That was. few years ago, and since it was closed, I decided to open a new issue. 

However, Internet Explorer was retired on June 15, 2022  and replaced with Microsoft Edge. <https://www.microsoft.com/en-us/download/internet-explorer.aspx>

I generally use Chrome, but I suppose `remotes::install_github()` uses something else. 

The same example from #130 applies; any thoughts would be appreciated.

```
─ Session info
 setting  value
version  R version 4.2.0 (2022-04-22 ucrt)
os       Windows 10 x64 (build 19044)
system   x86_64, mingw32
ui       RStudio
language (EN)
collate  English_United States.utf8
ctype    English_United States.utf8
tz       America/New_York
date     2023-02-21
rstudio  2022.02.2+485 Prairie Trillium (desktop)
pandoc   2.18 @ C:/PROGRA~1/Pandoc/ (via markdown)
```

**Comment by gaborcsardi** [comment]
@phargarten2 what is your OS and R version? What is the exact output you get?

**Comment by phargarten2** [comment]
@gaborcsardi  Thank you. Please see the updated information above.

**Comment by gaborcsardi** [comment]
Do you use a proxy? Do you have the curl package installed? If yes, can you try standalone mode (see README)?

**Comment by gaborcsardi** [comment]
Closing this for lack of information. Please reopen with more info if you still have this problem.
