### ISSUE TITLE
Unable to install 'remotes' in Amazon Linux 2 environment. Unable to install libgit2-devel

### ISSUE THREAD

**Issue by elsiel23** [r-lib/remotes#752]
I am using a Dockerfile to deploy an AWS Lambda function that depends on the R remotes package.

When building the Dockerfile below, I run into the error:

2023-03-07T06:39:37.2289962Z > install.packages('remotes',dependencies=TRUE, repos='http://cran.rstudio.com/')
2023-03-07T06:39:37.2338506Z [91mInstalling package into ‘/usr/lib64/R/library’
2023-03-07T06:39:37.2338885Z (as ‘lib’ is unspecified)
2023-03-07T06:39:38.2579141Z [0m[91malso installing the dependencies ‘pillar’, ‘sass’, ‘glue’, ‘vctrs’, ‘fs’, ‘fansi’, ‘rematch2’, ‘tibble’, ‘highr’, ‘prettyunits’, ‘bslib’, ‘stringr’, ‘lifecycle’, ‘pkgload’, ‘waldo’, ‘covr’, ‘git2r’, ‘knitr’, ‘mockery’, ‘pkgbuild’, ‘pingr’, ‘rmarkdown’, ‘testthat’, ‘webfakes’, ‘withr’
........
2023-03-07T06:40:16.1096298Z    Unable to find the libgit2 library on this system. Building 'git2r'
2023-03-07T06:40:16.1097084Z    using the bundled source of the libgit2 library.
2023-03-07T06:40:16.1097786Z 
2023-03-07T06:40:16.1098116Z    To build git2r with a system installation of libgit2, please install:
2023-03-07T06:40:16.1099040Z      libgit2-dev   (package on e.g. Debian and Ubuntu)
2023-03-07T06:40:16.1099614Z      libgit2-devel (package on e.g. Fedora, CentOS and RHEL)
2023-03-07T06:40:16.1100422Z      libgit2       (Homebrew package on OS X)
2023-03-07T06:40:16.1100839Z    and try again.

However, when I add `yum -y install libgit2-devel`, I run into the error that there is no package with that name. I've tried various work arounds, but nothing resolves it. Similar to this issue: https://community.rstudio.com/t/devtools-dependency-not-available-in-ec2-terminal/92701

My Dockerfile:
```
FROM public.ecr.aws/lambda/python:latest

RUN yum -y update 
RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN yum -y install R
RUN yum -y install tar

RUN yum -y install libcurl-devel
RUN yum -y install openssl-devel
RUN yum -y install udunits2-devel

RUN R -e "install.packages('sf',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('remotes',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "remotes::install_github('forsys-sp/forsysr')"
```

**Comment by gaborcsardi** [comment]
remotes does not have any necessary dependencies. `dependencies = TRUE` means that you are installing the optional and development dependencies as well, which are not needed to use remotes. (The same is true for sf, btw.)

However, ultimately the package you want to install needs R 4.0.3, and Amazon Linux 2 only has R 3.6.x, so this is still not going to work: https://github.com/forsys-sp/forsysr/blob/7b9641a5fd0be1e660944ef54c2d062bb2cd228c/DESCRIPTION#L28

Amazon Linux 2 is based on CentOS 7 (?), and we (Posit) provide R binaries for CentOS 7, see https://github.com/rstudio/r-builds. Unfortunately they do not seem to work on Amazon Linux 2, AFAICT. :(

**Comment by gaborcsardi** [comment]
Actually, I can install R 4.2.2 from rstudio/r-builds after 
```
yum -y install compat-gcc-48-libgfortran
```

But then sf needs gdal >= 2.0.0, which is also not available on Amazon Linux 2, and you need to install it from source, e.g.: https://gist.github.com/alanorth/9681766ed4c737adfb48a4ef549a8503

**Comment by gaborcsardi** [comment]
This might work:
```dockerfile
FROM public.ecr.aws/lambda/python:latest

RUN yum -y update
RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

# https://github.com/rstudio/r-builds/
RUN yum -y install compat-gcc-48-libgfortran
RUN curl -O https://cdn.posit.co/r/centos-7/pkgs/R-4.2.2-1-1.x86_64.rpm && \
    yum -y install R-*.rpm && \
    rm R-*.rpm

RUN ln -s /opt/R/4.2.2/bin/R /usr/local/bin/R && \
    ln -s /opt/R/4.2.2/bin/Rscript /usr/local/bin/Rscript

# https://pak.r-lib.org/reference/install.html#nightly-builds
RUN R -e 'install.packages("pak", repos = sprintf("https://r-lib.github.io/p/pak/devel/%s/%s/%s", .Platform$pkgType, R.Version()$os, R.Version()$arch))'

RUN yum -y install openssl-devel udunits2-devel tar

# https://gist.github.com/alanorth/9681766ed4c737adfb48a4ef549a8503
RUN set -x && \
    cd /tmp && \
    curl -LO https://download.osgeo.org/proj/proj-6.1.1.tar.gz && \
    tar xf proj-6.1.1.tar.gz && \
    cd proj-6.1.1 && \
    yum -y install sqlite-devel file && \
    ./configure && \
    make -j4 && \
    make install

RUN set -x && \
    cd /tmp && \
    curl -LO https://download.osgeo.org/gdal/2.4.2/gdal-2.4.2.tar.gz && \
    tar xf gdal-2.4.2.tar.gz && \
    cd gdal-2.4.2 && \
    yum -y install libzstd-devel sqlite-devel libwebp-devel hdf5-devel && \
    ./configure && \
    make -j4 && \
    make install

RUN echo 'options(repos = c(CRAN = "https://cloud.r-project.org"))' >> \
         /opt/R/4.2.2/lib/R/library/base/R/Rprofile && \
    echo 'options(repos = c(RSPM="https://packagemanager.rstudio.com/all/__linux__/centos7/latest", getOption("repos")))' >> \
         /opt/R/4.2.2/lib/R/library/base/R/Rprofile

RUN R -e 'pak::pkg_install(c("sf", "forsys-sp/forsysr"))'
```

**Comment by gaborcsardi** [comment]
Plus you also need to compile and install geos, after gdal:
```dockerfile
RUN set -x && \
    cd /tmp && \
    curl -LO https://download.osgeo.org/geos/geos-3.7.5.tar.bz2 && \
    yum -y install bzip2 && \
    tar xf geos-3.7.5.tar.bz2 && \
    cd geos-3.7.5 && \
    ./configure && \
    make -j4 && \
    make install
```

**Comment by elsiel23** [comment]
Thank you for your help! I was able to build my Dockerfile with the steps you mentioned above, but ran into a linking issue when actually running the Lambda. 

"errorMessage": "cannot load library '/opt/R/4.2.2/lib/R/lib/libR.so': libRblas.so: cannot open shared object file: No such file or directory",

**However, I've installed openblas with "RUN yum -y install openblas-devel" and can see:**
RUN ls /opt/R/4.2.2/lib/R/lib
libRblas.so
libRblas.so.keep
libRlapack.so
libR.so

**This result suggests to me that the R install might not be linked correctly:**
RUN ldd /opt/R/4.2.2/lib/R/lib/libR.so
 ---> Running in a51b1087a2ca
	linux-vdso.so.1 (0x00007fffa9341000)
	**libRblas.so => not found**
	libgfortran.so.3 => /lib64/libgfortran.so.3 (0x00007fec8baaf000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fec8b76f000)
	libquadmath.so.0 => /lib64/libquadmath.so.0 (0x00007fec8b531000)
	libreadline.so.6 => /var/lang/lib/libreadline.so.6 (0x00007fec8b2eb000)
	libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007fec8b074000)
	liblzma.so.5 => /var/lang/lib/liblzma.so.5 (0x00007fec8ae4f000)
	libbz2.so.1 => /var/lang/lib/libbz2.so.1 (0x00007fec8ac3f000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fec8aa2a000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fec8a822000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fec8a61e000)
	libicuuc.so.50 => /lib64/libicuuc.so.50 (0x00007fec8a2b1000)
	libicui18n.so.50 => /lib64/libicui18n.so.50 (0x00007fec89ec3000)
	libgomp.so.1 => /lib64/libgomp.so.1 (0x00007fec89c[960](https://github.com/OurPlanscape/Planscape/actions/runs/4387603270/jobs/7683098074#step:6:961)00)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fec89a78000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fec896cb000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fec8c498000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fec894b5000)
	libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007fec8928a000)
	libicudata.so.50 => /lib64/libicudata.so.50 (0x00007fec87cb7000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fec87935000)

**Comment by elsiel23** [comment]
A few stackoverflow posts suggest something like 'mv /usr/lib64/R/lib/libRrefblas.so /usr/lib64/R/lib/libRblas.so', but I'd like to use the optimized blas library

i.e. https://stackoverflow.com/questions/62857928/error-of-install-r-in-linux-red-haterror-while-loading-shared-libraries-librbl

**Comment by gaborcsardi** [comment]
Well, this is a package for CentOS 7 and we test it there. I don't really know how the BLAS libs might be missing on AL2 but not on CentOS 7. :(

**Comment by elsiel23** [comment]
That's fair, appreciate all the help. I think AL2 is based primarily on CentOS, but I'm sure there are many differences.

**Comment by gaborcsardi** [comment]
The `not found` is normal, R sets `LD_LIBRARY_PATH` from its startup script, so you would need to check it like this:
```r
LD_LIBRARY_PATH=/opt/R/4.2.2/lib/R/lib ldd /opt/R/4.2.2/lib/R/lib/libR.so
```

Also, my colleague says that our R build should already link to openblas on CentOS 7, and you can check this in R. This is what I get on CentOS 7:
```
> La_library()
[1] "/usr/lib64/libopenblasp-r0.3.3.so"
> La_version()
[1] "3.8.0"
```

**Comment by gaborcsardi** [comment]
I am closing this now, because it seems that there is nothing to do in remotes. Please reopen if you disagree.
