### ISSUE TITLE
`system_requirements` doesn't support debian, contra documentation 

### ISSUE THREAD

**Issue by eliocamp** [r-lib/remotes#759]
`remotes::system_requirements(os = "debian")` returns error: 

```
Error in match.arg(os, names(os_versions)) : 
  'arg' should be one of “ubuntu”, “centos”, “redhat”, “opensuse”, “sle”
```

However, its documentation states "see https://github.com/rstudio/r-system-requirements#operating-systems for the list of supported operating systems", which currently lists Debian 10, 11 and unstable as supported. 

From this code:

https://github.com/r-lib/remotes/blob/e199c1bdda3858600bbef8e4bbc3f5868b899587/R/system_requirements.R#L99-L111

I guess that Debian is not actually supported by r-system-requirements? 

It seems like a mismatch between documentation and code. Although I don't know if this is an issue for remotes or for the r-system-requirements repo.

**Comment by gaborcsardi** [comment]
A PR is welcome to fix this, or I suggest you try the pak package instead of remotes.
