### ISSUE TITLE
Possible for dependency installations to "inherit" the value of dependencies argument?

### ISSUE THREAD

**Issue by richarddmorey** [r-lib/remotes#761]
I have two packages:

`A`: https://github.com/richarddmorey/flexTeaching3.interface (Suggests `B`)
`B`: https://github.com/richarddmorey/flexTeaching3.examples (Suggests, e.g., `rsvg`)

Package `B` is in the Suggests for package `A`, and package `B` also has all of its dependencies in Suggests (because they are Rmd examples stored in `inst/`).

When I install package `A` with

```
remotes::install_github('richarddmorey/flexTeaching3.interface', dependencies = TRUE)
```

it installs Package `B`, as expected:

```
find.package('flexTeaching3.examples')
# [1] "/Users/saprm3/Downloads/test_remotes/renv/library/R-4.3/aarch64-apple-darwin20/flexTeaching3.examples"
```

But does not install any of the Suggests of package `B`, making the package incomplete:
```
find.package('rsvg')
# Error in find.package("rsvg") : there is no package called ‘rsvg’
```

I would like to be able to apply the value of the dependency argument (TRUE, in this case, so that Suggests are installed) in turn to the installation of dependencies. Is there a way to do this?

**Comment by richarddmorey** [comment]
I see, thanks - so I should install `B` explicitly with `install_github`, or move the dependencies to "Depends"?

**Comment by gaborcsardi** [comment]
Yeah, probably `Imports`, though, not `Depends`.
