### ISSUE TITLE
Unable to install more than one private repository at a time with devtools::install_git

### ISSUE THREAD

**Issue by g-pires** [r-lib/remotes#770]
Hi, 

I've been trying to install two private repositories from gitlab using 

`devtools::install_git("address-to-private-repo/package.git",
                                 credentials = git2r::cred_user_pass("username",
                                                                                         getPass::getPass()),
                                 ref = "DEV")`

I works well with the first package, however when I try ton install a second package (which directly depends on the first one) it fails with this error : 
`Error: Failed to install 'unknown package' from Git:
  Error in 'git2r_remote_ls'`

After removing the first package I was able to install the second one, but the problem is that the second one directly depends on the first one so it wouldn't install either. 

Do you have any idea of why it could throw this error ? 

Thanks in advance, 

Kind regards.

R FoReveR

**Comment by gaborcsardi** [comment]
@g-pires We are focusing on the development of pak now, please try this with pak (see https://pak.r-lib.org/reference/install.html for installation).

This works fine for two of my private repos:
```
❯ pak::pkg_install("git::https://github.com/gaborcsardi/private")

→ Will install 1 package.
→ Will download 1 package with unknown size.
+ private   0.0.0.9000 👷🏾🔧 ⬇
ℹ Getting 1 pkg with unknown size
✔ Got private 0.0.0.9000 (source) (96 B)
✔ Downloaded 1 package (96 B) in 471ms
ℹ Packaging private 0.0.0.9000
✔ Packaged private 0.0.0.9000 (964ms)
ℹ Building private 0.0.0.9000
✔ Built private 0.0.0.9000 (546ms)
✔ Installed private 0.0.0.9000 (git::https://github.com/gaborcsardi/private@eb2fead) (16ms)
✔ 1 pkg: added 1, dld 1 (NA B) [4.5s]

  128.34 MB ⌗ 2.9·2.9·2.8  ~  
❯ pak::pkg_install("git::https://github.com/gaborcsardi/installlite")

→ Will install 1 package.
→ Will download 1 package with unknown size.
+ installlite   0.0.0.9000 👷🏼‍♂️🔧 ⬇
ℹ Getting 1 pkg with unknown size
✔ Got installlite 0.0.0.9000 (source) (96 B)
✔ Downloaded 1 package (96 B) in 567ms
ℹ Packaging installlite 0.0.0.9000
✔ Packaged installlite 0.0.0.9000 (267ms)
ℹ Building installlite 0.0.0.9000
✔ Built installlite 0.0.0.9000 (788ms)
✔ Installed installlite 0.0.0.9000 (git::https://github.com/gaborcsardi/installlite@452b3f1) (18ms)
✔ 1 pkg: added 1, dld 1 (NA B) [3.6s]
```

**Comment by g-pires** [comment]
Hello, 

Thank you for your quick answers. I finally managed to install both package. 

For those who are still looking for the answer, when you want to install two packages (A and B) from two private repositories hosted on a private instance of gitlab (or github) and B is directly dependant of A, you will have to set an environment variable GITLAB_PAT (or GITHUB_PAT). That way you will be able to install both packages with the following command: 
`devtools::install_git("address-to-private-repo/package.git", credentials = git2r::cred_user_pass("username", getPass::getPass()), ref = "DEV")`

Thank you again. 

Kind regards, 

R FoRevR
