### ISSUE TITLE
Install github from public repo

### ISSUE THREAD

**Issue by byzheng** [r-lib/remotes#797]
When I updated to R 4.4.0 under Windows 11, I cannot install any R packages from github now with this error

```
Using GitHub PAT from the git credential store.
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials
```

I don't think any PAT credential store locally. Any idea to fix this problem?

**Comment by gaborcsardi** [comment]
> I don't think any PAT credential store locally.

remotes seems to think otherwise. Try to use
```
Sys.getenv("GITHUB_TOKEN")
Sys.getenv("GITHUB_PAT")
gitcreds::gitcreds_get()
gitcreds::gitcreds_get()$password
```
to see where the token is coming from, and then remove it.

**Comment by byzheng** [comment]
Thanks @gaborcsardi. `gitcreds::gitcreds_get()` finds a PAT. Where can I locate it?

**Comment by byzheng** [comment]
I have to remove the PAT using [Windows Credential Manager](https://faq.miniorange.com/knowledgebase/reset-saved-git-login-details-from-local-machine/).

**Comment by gaborcsardi** [comment]
For the record, there is also `gitcreds::gitcreds_delete()`.
