### ISSUE TITLE
package ‘install_github’ is not available for this version of R

### ISSUE THREAD

**Issue by nest125** [r-lib/remotes#812]
Hello all!

I am receiving the above message.  I have R 4.4.1.  

This is in relation to trying to install the package "rethinking" which also has this error message:

" package ‘rethinking’ is not available for this version of R"

Any help and/or assistance is greatly appreciated.

**Comment by gaborcsardi** [comment]
You are clearly doing something wrong.

**Comment by nest125** [comment]
Hello!

Yep - I can see that.  Any help and/or assistance in resolving this is greatly appreciated!  Thanks!

**Comment by gaborcsardi** [comment]
There is no R package called install_github. What are you trying to do? What is the code that you are running? What is the output you get?

**Comment by nest125** [comment]
Hello again!

Whoops!  The title should read:  'package 'rethinking' is not availabe for this version or R.  Thank you for pointing that out.  I appreciate it!

**Comment by gaborcsardi** [comment]
What is the code that you are running? What is the output you get? What is your OS? What is your R version? What is the output of `getOption("repos")`?

**Comment by nest125** [comment]
Hello again!  The package 'rethinking' is part of the Statistical learning book by McElreath.  OS = Windows and this is the output for 'getoption("repos"):
                       CRAN 
"https://cran.rstudio.com/" 
attr(,"RStudio")
[1] TRUE

**Comment by gaborcsardi** [comment]
What is the code that you are running? What is the output you get? What is your OS? What is your R version?

**Comment by nest125** [comment]
Hello again!

My R version is 4.4.1.  When I try an install the 'rethinking' I get this line:
 "package ‘rethinking’ is not available for this version of R"

**Comment by gaborcsardi** [comment]
What is the code that you are running? What is the output you get?

**Comment by dragosmg** [comment]
Maybe relevant piece of information from the {rethinking} Readme (https://github.com/rmcelreath/rethinking?tab=readme-ov-file#installation):
> Note that the rethinking package is not on CRAN, just on github. The rethinking package is never going to be on CRAN. So if you get an error about rethinking not being available for your version of R, it is because you tried to install from CRAN. Use the github code above.

**Comment by gaborcsardi** [comment]
I guess you are trying to install this: https://github.com/rmcelreath/rethinking
Which also needs https://github.com/stan-dev/cmdstanr
So this might work:
```r
remotes::install_github("stan-dev/cmdstanr")
remotes::install_github("rmcelreath/rethinking")
```

Or, if you want to give pak a try then
```r
pak::pkg_install(c("stan-dev/cmdstanr", "rmcelreath/rethinking"))
```

In any case, this is not an issue with the remotes package, so I am going to close this.

**Comment by nest125** [comment]
Hello again!

Thank you for the help!  I appreciate it!
