### ISSUE TITLE
install_local() tries to upgrade dependencies in "Remotes:", even if upgrade = "never"

### ISSUE THREAD

**Issue by mkoohafkan** [r-lib/remotes#815]
I have a package `packagetwo` with a dependency on `packageone` in the DESCRIPTION:

```
Package: packagetwo
Imports: packageone
Remotes: git::http://url/for/packageone.git
...
```

I install `packageone` locally:

```r
remotes::install_local('path/to/packageone')
# works!
```

I then try to install `packagetwo` locally, without upgrading dependencies. However, remotes still calls out to the remote repository for `packageone`, even though it is already installed:

```r
remotes::install_local('path/to/packagetwo', upgrade = "never")
```

This seems like a bug.

My current workaround is to install all of the dependencies for `packagetwo` (and specifically exclude `packageone`), and then install `packagetwo` with the argument `dependencies = FALSE`.

I **do** want it to install dependencies for `packagetwo`, just not those that are already installed (which I thought would be accomplished via the argument `upgrade = "never"`).

**Comment by gaborcsardi** [comment]
That's not a bug. remotes is not sure if version requested from `git::http://url/for/packageone.git` is installed, so it installs it.

**Comment by mkoohafkan** [comment]
But with `upgrade = "never"`, aren't we explicitly telling `remotes` to not do that check?

**Comment by gaborcsardi** [comment]
That does not apply to `Remotes`, only to CRAN packages.
